### ISSUE TITLE
HCFactions. /f show

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/HCFProblems#1]
It would be nice if we could remove and add things into the f show. 
So, in theory, if we don't want the enemies to show in f show, you can remove it. 
http://gyazo.com/4ca4e37646d0b6cadbdb07035bff6b93

**Comment by nsporillo** [comment]
A list in config.yml that takes TL values for what /f show outputs?

Example:
```
fshow:
- JOINING
- INVITATION
- UNINVITED
etc
```
You can hide the faction home from being sent to players who arent members of that faction with dtr.hide-homes in our initial release.

Let me know if the example above would satisfy your request :)

**Comment by SnakeDaoust1232** [comment]
Ok, I understand what you're saying but the only issue i have really is, the default relation on the server is enemy so when someone types /f who (faction) every faction on the server will show in there f who. Maybe just make it so when the default relation is set to enemy it doesn't show in the f who. That ^ up there is kind of confusing. If it does the same thing, can you clarify some more please.

**Comment by nsporillo** [comment]
You could simply leave out the TL value `ENEMIES` and it would not appear in the output sent to the player.

I think this purposed system, or similar system works to provide 100% /f show customization, after all you can change what messages get sent, in what order, and the very text using lang.yml

**Comment by SnakeDaoust1232** [comment]
Ok, that's sounds great, how long would this take to implement?

**Comment by nsporillo** [comment]
Not very long, we want to have this feature added by tomorrow at the latest. 
Thank you for the feature request.

**Comment by SnakeDaoust1232** [comment]
Thank you and that sounds great!

**Comment by nsporillo** [comment]
Still working on this request, had to spend the last few days working on critical bug fixes. 

Apologies for the inappropriate ETA, I'm thinking through the best way to implement 100% /f show customization

**Comment by nsporillo** [comment]
This feature has been added.
