### ISSUE TITLE
Decimal Places / DTR Freeze

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#10]
http://prntscr.com/6hltfv
This is the "f show" as I have set. I think it would be cool if there was an option to decide to what decimal place for example: 
0.00 instead of 0.000 if we so please.

I'd like to add 1 thing about the DTR Freeze. I like it the way it is, but it would be pretty cool if you had it say words instead of the numbers. 
For example (for 59 minutes, and 40 seconds)
DTR Freeze: 59:40
DTR Freeze: 59 minutes, 40 seconds.

See what I mean? 

Also might want to remove the fact that you can /f leave during DTR Freese bypassing the "not allowing to disband on DTR Freeze".

**Comment by nsporillo** [comment]
1) ![Lang](http://puu.sh/gDbp3/8effe06246.png)
- You can change the decimal format lang string in lang.yml.
- It's line 523, and '#.##' would accomplish the decimal place you're looking for.

2) You are right about the DTR freeze needing minutes and seconds. 
- I'll work on implementing this feature request, expect to see it in the next few builds on the CI. :+1: 

3) This bug fix request will be implemented in the next few builds on the CI as well :+1:
