### ISSUE TITLE
Offline Tag not working

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#101]
![sru9jka](https://cloud.githubusercontent.com/assets/9636316/6956258/036f3ec2-d8a0-11e4-833b-1a0dc599338e.png)

As you can see I have it in the config, It doesn't show up, the plugin just ignores the line..

Did some more tests, turns out that any line with the {offline} tag is ignored and doesn't appear.

**Comment by nsporillo** [comment]
Set hide-unused-fshow to false.

When there is no offline players, it will ignore the line when hide-unused-fshow is enabled.

**Comment by Doxify** [comment]
Thanks!
