### ISSUE TITLE
[Video] Lag w/ your plugin

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#104]
Video has it all:
http://youtu.be/JBqgpBYUhiQ

**Comment by MoeXIV** [comment]
Have you tried to make timing reports?
That explains what plugin is using what of your CPU. I've done reports on HCFactions, and there is no lag at all.

**Comment by TMNetwork** [comment]
@MoeXIV u just sparked an idea

it was coreprotect..



THANK YOU SO MUCH BABE. IDK WHA TIT WAS BUT WHEN I SAW UR NAME.,CORE PROTECT POPPED UP. I LOVE U.

**Comment by TMNetwork** [comment]
@nsporillo reopen as it still occurs when i type that command.

**Comment by drtshock** [comment]
Explain the issue in TEXT.

**Comment by TMNetwork** [comment]
When you f show a faction that isn't online, it lag spikes the server.

**Comment by drtshock** [comment]
On which part of f show specifically
