### ISSUE TITLE
./f stuck

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#107]
You need to make it where once u walk 5 blocks then it cancels it, cause going 1k blocks and then teleporting out is ridiculous.

**Comment by clerkk** [comment]
I was going to make a similar issue to this, maybe make it configurable in the config how many blocks one can move?

**Comment by nsporillo** [comment]
Working on this now, overhauling /f stuck quite a bit.

Adding command costs to it, as those were missing.

Will use essentials teleporting if essentials is installed, (their safe location code is much more comprehensive). If not we'll default to our method using the block blacklist in config.

Fix bugs with negative timers in certain cases.

**Comment by nsporillo** [comment]
This was added, it will be in the latest build when that is pushed.

Latest build is also going to include config breaking changes to variables, so going to put some sort of disclaimer to instruct everyone to get the [latest config](https://github.com/drtshock/HCFProblems/blob/master/config.yml) and translate what they had over.

**Comment by TMNetwork** [comment]
No no no. Essentials teleporting is usually set at 10 seconds. If another
player is in another factions territory then they need to wait 3 minutes to
get out so do NOT make this f stuck timer the same as essentials...

**Comment by nsporillo** [comment]
@TMNetwork that is not what this is doing. It is just using a method from Essentials that does safe teleporting, it doesnt do anything else you're talking about. 

Simply uses their code which finds a safe point to teleport too if essentials is enabled.
