### ISSUE TITLE
Nametag help

### ISSUE THREAD

**Issue by PlasmaHCF** [drtshock/HCFProblems#109]
i want to change this http://prntscr.com/6pmyoj to this http://prntscr.com/6pmzes

**Comment by PlasmaHCF** [comment]
can anyone help

**Comment by MoeXIV** [comment]
Simply use [FACTION] before {DISPLAYNAME} in the essentials chat format. Now all you have to do is add something nice. For example: &6[[FACTION]&6] {DISPLAYNAME}&if: {MESSAGE}

**Comment by PlasmaHCF** [comment]
thank you

**Comment by PlasmaHCF** [comment]
http://prntscr.com/6pndf3 like that

**Comment by PlasmaHCF** [comment]
do i keep chattagenabled : true or false

**Comment by PlasmaHCF** [comment]
http://prntscr.com/6pngrp

**Comment by PlasmaHCF** [comment]
can you send me you're essentials chat thing

**Comment by MoeXIV** [comment]
It's not {FACTION} it's [FACTION] with the [ ]

**Comment by MoeXIV** [comment]
P.S, is Plasma re opening?
Because like everyone from Plasma moved to Pure.

**Comment by PlasmaHCF** [comment]
plasma iis not coming back

**Comment by PlasmaHCF** [comment]
we are done forever

**Comment by MoeXIV** [comment]
Then why'd is you buy an HCF plugin then?
A new HCF server?
