### ISSUE TITLE
Member Online / Offline / Death

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#11]
Basically, I was looking through the configuation and lang.yml, and I found this:

faction-login: '&e%1$s &9logged in.'
faction-logout: '&e%1$s &9logged out..'

I thought this was the messages that showed when a member logged in or out. I can't seem to get it to work, that's if that is what they are for.

If there is a way to do it, could you please show me how? If not, that's be a cool feature to add.

Offline = "&6Member offline: &4**MoeXIV
Online = "&6Member online: &2**MoeXIV
Death = "&6Member death: &4**MoeXIV
              "&6DTR: &e0.51 / 1.02"

I also couldn't figure out how to edit the leaving messages, and entering messages for territories.
http://prntscr.com/6hpr1o
It would be great if you could explain on how to do it, I'm newish to Factions UUID.

**Comment by MoeXIV** [comment]
Sorry, when I did the "starts / astricks" it turned the font bold. ^.^

**Comment by nsporillo** [comment]
@MoeXIV This issue tracker is for HCFactions only, you mentioned you were new to Factions UUID that is why I say this.

https://github.com/drtshock/Factions/commit/8300b2ff2b783de2f02c6956abee0a11525ca676#diff-dba339e247b7e8d53bc67d10f53caf97R123

This commit introduced a toggle for that feature, /f login . 

Also, those 4 lines you referenced are configurable via the fshow list in config.

Please update to version v0.0.4 from the CI and let a new lang file and config generate. 
The command /f login will do what you need, and f show is configurable with HCFactions v0.0.4 and up.
