### ISSUE TITLE
F SHOW - Error After Making A Faction

### ISSUE THREAD

**Issue by RealRemedy** [drtshock/HCFProblems#110]
how to fix this http://prntscr.com/6pxglj

**Comment by nsporillo** [comment]
What HCF version are you using?

Post your config and your error from console into seperate gists. Paste the links to them as a reply on this issue.

Use http://gist.github.com/

**Comment by NauruMC** [comment]
@nsporillo @RealRemedy I have gotten this issue as well, a full restart of the server fixed it for me.

**Comment by nsporillo** [comment]
@NauruMC @RealRemedy regardless, still need his config and error from console to get any sort of idea what is causing this. It's most likely just an error with how it was configured.

**Comment by NauruMC** [comment]
@nsporillo EDIT: Got this error once more on b39. It crashed the server. I'll look for the logs and message them to you. I'll have to savage thou my cluttered OVH box for the logs..

**Comment by nsporillo** [comment]
Havent heard from @RealRemedy, and @Quizzes hasn't provided any logs.

Closing this issue since b39 with a good config appears to work completely fine.

**Comment by Quizzes** [comment]
All the servers will just have random crashes until b8263 because REMEDYG0D didn't provide logs ;(

EDIT: Couldn't post logs because i didn't pay for my OVH server and lost my files! *derp*
