### ISSUE TITLE
hide-unused-fshow Hides Faction Tag

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#112]
So basically, I planned to have the {tag} in the "f show", but it hides it. I don't understand how {tag} is an unnecessary space.

**Comment by MoeXIV** [comment]
Closing this because turns out I just had a few errors, not sure what caused them, but a few things went wack with Factions, including the chat tags. A complete restart resolved the issue,

**Comment by nsporillo** [comment]
@MoeXIV Plan on removing that value in config anyways, found a better way to handle what it did.
