### ISSUE TITLE
REQUEST: /f announcement

### ISSUE THREAD

**Issue by NauruMC** [drtshock/HCFProblems#113]
Basically when a faction officer does /f announcement [message] the message he types will be shown using the variable {announcement}. This variable should be hidden in /f show if there is no announcement to view, this should bypass hide-unused-fshow because i don't want everything else that is not used to be hidden, it should just hide the announcement if there is no announcement and nothing else.

EDIT: This should be stored using a flat file in the factions.json

**Comment by nsporillo** [comment]
Try /f announce or /f ann ?

**Comment by NauruMC** [comment]
Both could work

**Comment by nsporillo** [comment]
No I mean they already exist.

**Comment by NauruMC** [comment]
Oh really? I'm at school now. After this class i'll end up testing it.

**Comment by NauruMC** [comment]
I'll be closing this issue until i can test to see if this is what i need.

**Comment by NauruMC** [comment]
Closed, works as needed.
