### ISSUE TITLE
DTR Symbols

### ISSUE THREAD

**Issue by Quizzes** [drtshock/HCFProblems#114]
These symbols and colors would be nice if they were added to the {dtr} variable

These symbols will be shown in the {dtr} variable (This should be configuarble like 'show-dtr-symbols' or something along the lines of that..)

P.S: In these examples i'll just be using 1.0 DTR 

Max DTR (For the faction): 1.0 ◂(Green like &a or ChatColor.GREEN)

DTR Freeze: 1.0 ▾(Yellow like &e or ChatColor.YELLOW)

DTR is regenerating: 1.0 ▴ (Green like &a or ChatColor.GREEN)

Faction is raidable: 1.0 • (Red like &c or ChatColor.RED)

Example in f-show:

DTR: &a0.51 ◂&r

**Comment by nsporillo** [comment]
A bit more complex since f show is fully configurable. Would probably define TL values for those symbols and then define a new variable which is replaced with such TL based on some logic.

**Comment by MoeXIV** [comment]
I've seen a few plugins using fancifuls API, to add a biohazard symbol before the DTR if they are Raidable. I think it would be simply a cool effect to turn the DTR color ChatColor.RED whilst they are Raidable, as well as possibly a customizable symbol.

For example: DTR: 1.01 (Not Raidable)
DTR: &c<symbol>-1.01 (Raidable)

**Comment by MoeXIV** [comment]
It deleted something I added. I meant 
DTR: &c{symbol}-1.01 (Raidable)

**Comment by NauruMC** [comment]
That would be nice, but i wouldn't want the '-' in the DTR. It makes it look like another symbol.
Maybe a config.yml option?

fshow-dtr-symbol: true

That would remove the negative and replace it with symbols.
The symbols should be changed in the lang.yml aswell.

**Comment by MoeXIV** [comment]
You cannot remove the "-". It shows you have negative DTR. -.-

**Comment by NauruMC** [comment]
Not if you have symbols C: 
"Faction is raidable: 1.0 • (Red like &c or ChatColor.RED)"

**Comment by MoeXlV** [comment]
<code>Test<\code>
