### ISSUE TITLE
Faction prefix editing?

### ISSUE THREAD

**Issue by ScarOG** [drtshock/HCFProblems#115]
How do I go about editing the a factions prefix, I have tried but the config is very confusing and I would like a quick explanation 

Thank you

- ScarOG

**Comment by drtshock** [comment]
Prefix for chat or scoreboard?

**Comment by ScarOG** [comment]
Chat

**Comment by MoeXIV** [comment]
I don't think that's something you can do, endless you go into the Lang.yml and add your prefix before every word.

**Comment by ScarOG** [comment]
@MoeXIV I am talking about the prefix when a player speaks not a prefix for all messages.

**Comment by MoeXIV** [comment]
I must've misunderstood. That's alteay configurable through essentialschat

**Comment by ScarOG** [comment]
@MoeXIV Already tried, is there any specific variables for this plugin?

**Comment by ScarOG** [comment]
Fixed it.

**Comment by KriticalPvP** [comment]
@ScarOG How did you fix it?

**Comment by agusztin** [comment]
Yes how?

**Comment by KriticalPvP** [comment]
[[Faction]] @agusztin

**Comment by agusztin** [comment]
Thanks

**Comment by KriticalPvP** [comment]
Close this if it's solved
