### ISSUE TITLE
/f list relation color

### ISSUE THREAD

**Issue by MoeXlV** [drtshock/HCFProblems#116]
Title pretty much explains it all, when a user types /f list the faction's name isn't the color
of the relation color.

Example: < i >{faction} (Config) turns into this in minecraft chat &eTestFactionName (MC Chat)

I've already spoke to @nsporillo about this but i thought i would put it on here so other pepole
don't have to report it.

**Comment by nsporillo** [comment]
Already made the fix for this, but did not commit yet as I am waiting to make some more fixes for a build 40.
