### ISSUE TITLE
No way to customise player names / tablets

### ISSUE THREAD

**Issue by AlfieC** [drtshock/HCFProblems#119]
There's currently no way to just get someone's relation above their head, not their faction name. Is there a way to get this implemented?

**Comment by nsporillo** [comment]
@AlfieC try build 40, Build changed how variables were handled and it was a very large update. Build 40 addressed missing relation colors for all variables. Let me know this works for you.

**Comment by AlfieC** [comment]
Currently there is no way to customise the overhead/tab titles. Could you add a variable config setting?

**Comment by nsporillo** [comment]
It's default-prefix in lang.yml.
