### ISSUE TITLE
NameTags Corrupt in 0.0.4

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#12]
Basically, in the new 0.0.4 HCFactions version, the scoreboards do not work at all. The side bar, and the above the heads. If you try to edit the format, or change anything in the lang.yml file; it just disables itself.

I've tried everything. The only way to get it to work, only on default settings; is to delete the whole directory and restart the server.

**Comment by nsporillo** [comment]
Restart the server, try to customize the settings and see if they take effect. 

You probably could have gotten away with just removing the suspect file, shouldn't have *needed* to nuke the directory.

**Comment by MoeXIV** [comment]
I tied deleting each file by itself, and no use. We've restarted plenty of times. No use. Just a white base name. No errors, no nothing. It's like the configuration disables that tablist when it detects a simple change.

**Comment by nsporillo** [comment]
![2015-03-17_00 13 55](https://cloud.githubusercontent.com/assets/1480197/6681315/c84e928c-cc3a-11e4-888e-a5714058046c.png)
The scoreboards are working over head and in tablist.

![2015-03-17_00 20 55](https://cloud.githubusercontent.com/assets/1480197/6681363/9b277c0a-cc3b-11e4-8fdf-6ca1b039a297.png)
Faction info scoreboards are working and I was able to change "territory" to "land" without issues.

What values are you referring to in the lang file?

**Comment by MoeXIV** [comment]
The "default-prefix: '{relationcolor}" because I just wanted the color, not the faction name.

http://prntscr.com/6hsatu

I've tried everything. Scoreboards don't even come up for me. When I setup scoreboards, they don't come up. I'm on spigot 1.7.10 / 1.8 Protocol hack build 1649.

**Comment by nsporillo** [comment]
What do you expect just the color and not a faction name to look like..?

**Comment by Doxify** [comment]
He wants just the name colored.

So if someone is an enemy, there'd be no faction tag but just a red name.

**Comment by nsporillo** [comment]
This is more of a feature request then a bug report, as that functionality hasnt existed before (atleast afaik)

However, i'll work on some fixes to allow you to do this, as it is a good idea :+1:

**Comment by MoeXIV** [comment]
This is already possible. A change of Spigot versions did the job. Please close the thread. :+1:

**Comment by nsporillo** [comment]
![2015-03-17_01 58 13](https://cloud.githubusercontent.com/assets/1480197/6682102/327f1bd2-cc49-11e4-9b33-505e69226fea.png)

with:
    default-prefix: '{relationcolor}'

@MoeXIV glad it was resolved :smile:
