### ISSUE TITLE
Ally Spacing Issue

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#121]
My config: http://pastebin.com/raw.php?i=7nvYAfrK
Result: http://i.imgur.com/RDmK7zK.png (2 extra spaces)

**Comment by nsporillo** [comment]
You're not running the latest version, so I cannot say for sure what the issue is.

Why don't you try removing the color code before {allies}, it obviously doesn't get used anyways.

Also, deleted your rude comment on #120, if you continue to misuse the issue tracker you'll be removed.

**Comment by LOOOOOOOL** [comment]
@nsporillo mr. nick; u have no idea what the back story of that comment is; this is the same kid or maybe his co owner that told me that I am a terrorist due to my race so....
