### ISSUE TITLE
Hurting Faction members?

### ISSUE THREAD

**Issue by Quizzes** [drtshock/HCFProblems#124]
Is hurting faction members meant to be there? You're only supposed to be able to hit you're allys/truces not you're faction members. You should fix this. Once again, you can only hit Allys/Truces..

Here is the message when i hit a faction member

![b82a0e5b8f02cc39e74293327f62b5e0](https://cloud.githubusercontent.com/assets/9434234/7168445/7ede573c-e38b-11e4-912d-f7a1c00c04dd.png)

P.S: On my server DARK_GREEN (&2) is the Faction member color..

**Comment by nsporillo** [comment]
There's an option in config.yml for friendly fire, but no it should not allow you to hurt faction members, so this is a bug. Should be an easy fix. Thanks

**Comment by Quizzes** [comment]
No problem
