### ISSUE TITLE
Ver Question

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#125]
Ok so I have a question.

I use build 37.

Will I have an issue with my config.json and lang.yml or just config.yml?

**Comment by nsporillo** [comment]
An issue with regards to what..? Upgrading to a new build? Yes. Read [here](https://github.com/drtshock/HCFProblems/blob/master/UpdateToBuild39.md).

**Comment by Quizzes** [comment]
Yes @LOOOOOOOL as @nsporillo said. Just config.yml. Everything in that file was revamped, variables were changed and stuff. If you do some tinkering with wordpad you can compare the two files and merge them.

**Comment by LOOOOOOOL** [comment]
@nsporillo so just my config.yml? This is important and I'm just clarifying what you said in the read here.

**Comment by nsporillo** [comment]
@LOOOOOOOL Only your config.yml, yes.
