### ISSUE TITLE
f show ally bug

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#126]
Config: http://hastebin.com/iluwaheguw.xml
Problem: It has 2 extra spaces as you can see.
Picture: http://i.imgur.com/ipbGDFo.png

I'm on version 37 so that might be fixed. IDK, let me know ;)

**Comment by nsporillo** [comment]
![dotdotdot](http://puu.sh/hgD66/7570e7f569.png)
.. https://github.com/drtshock/HCFProblems/issues/121

Did you just ignore what I suggested trying?

This is not an issue with the code, rather an issue with how you're configuring the line in your f show. 

As you can see...
![worksfine](http://puu.sh/hgDrO/7b21c22a5f.png)

using

      - '<a>Allies(<i>{allies-count}<a>/<i>{max-allies}<a>): {allies}'
