### ISSUE TITLE
big error, idk why

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#127]
https://gist.github.com/nsporillo/bb1b56b66030193a7361

**Comment by nsporillo** [comment]
Post your error and config to https://gist.github.com/ and then link them in your issue.

**Comment by drtshock** [comment]
I don't recall you purchasing this. What's the transaction ID I can use to verify the purchase?

**Comment by Quizzes** [comment]
If i'm correct Lilmac is merging servers with Aaron (MoeXIV). There creating a network and i'm sure they have access to each others file. I may be wrong but from my sources, that is how he might have it.

**Comment by Quizzes** [comment]
Also @Lilmac12312 post you're errors/stacktraces in https://gist.github.com or http://hastebin.com

**Comment by MoeXIV** [comment]
Correct, me and Lilmac are opening another sub server for our Australian players as OVH is for US players usually. Since lilmac is more in the AU time, he is managing the server more then I am, I manage more of the US server.

I did not know I needed a new license to run the plugin on the same network but within a sub server.

**Comment by drtshock** [comment]
You should purchase it for each individual instance of it you are running.

**Comment by MoeXIV** [comment]
Alright, so are you suggesting that I pay the same price once again?

**Comment by drtshock** [comment]
Yes. You should wait until like... tomorrow as I'll have my new permanent site up :)

**Comment by Quizzes** [comment]
@drtshock  Can't wait to see it. I've heard that it looks fresh and spicy ;)

**Comment by nsporillo** [comment]
@Lilmac12312 when you have a license, we can address this issue.

**Comment by MoeXIV** [comment]
It's basically my licence. It's our network.

**Comment by Lilmac12312** [comment]
@nsporillo Moe / Aaron owns the server but is away at his cottage and till then I'm looking after the server, making sure it's running smoothly so on so forth.

**Comment by MoeXIV** [comment]
This issue can be picked back up and the no license can should be removed. Lilmac has purchased HCFactions for use.

**Comment by nsporillo** [comment]
@Lilmac12312 post your config.yml in a gist, and also include the build you're using.

**Comment by Lilmac12312** [comment]
https://gist.github.com/Lilmac12312/2e07034c1e27b0456801

**Comment by nsporillo** [comment]
@Lilmac12312 thank you, this one is going to take a bit to debug, but with what you provided it'll happen.

**Comment by nsporillo** [comment]
@Lilmac12312 going to set this to closed since it seems like it's an temporary/isolated issue. 

If this issue is still occuring on the very latest build, please make a new issue with the stacktrace in a gist. Thank you :smile:
