### ISSUE TITLE
5.51 / 0.51 dtr and tab doesn't update

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#13]
5.51/0.51 DTR

![c015fb8229aaf96c5c3f74fa5c541264](https://cloud.githubusercontent.com/assets/9636316/6681293/4cf1677c-cc21-11e4-9317-de849faaf3ff.png)

I was logged in on my other account and the problem was not there. Seems to only happen to some people. (As you can see there are two people online, I ran /list in console)

![lv2bq3r](https://cloud.githubusercontent.com/assets/9636316/6681342/1e7736a0-cc22-11e4-8686-7c26990f6022.png)

**Comment by nsporillo** [comment]
Try to run /fshow again, there may have been a temporary blip in the calculation. 

Make sure you're running the latest build, https://github.com/drtshock/HCFProblems/issues/6 referenced a issue similar to this and it should have been fixed in the newer builds.

As far as the tablist not updating, i'll run some tests with 2 clients right now and see what happens.

**Comment by Doxify** [comment]
I wasn't aware that there are new builds, this is what happens when I go to the link for downloads.

![uowns34](https://cloud.githubusercontent.com/assets/9636316/6681415/662c2568-cc23-11e4-9832-2a9826bf21a4.png)

**Comment by nsporillo** [comment]
On the readme, it links [here](https://gist.github.com/drtshock/d3105986088775fc6c20) if you don't have access to the builds (a 404).

If you've already purchased, contact @drtshock to get access to the dev builds :+1:

**Comment by Doxify** [comment]
![r6dcnwn](https://cloud.githubusercontent.com/assets/9636316/6681445/098c413e-cc24-11e4-8fe7-5b09926ba825.png)


He told me I was already added, should I contact him again?

**Comment by nsporillo** [comment]
@Doxify you have read access
![ss 2015-03-17 at 12 33 57](https://cloud.githubusercontent.com/assets/1480197/6681451/56d8c5e8-cc3d-11e4-97de-b41fb089c5a7.png)

Make sure you log into the CI page, in case you were logged out.

**Comment by Doxify** [comment]
I am logged in, HCFactions is not in his Jenkins or at least it doesn't show for me.

**Comment by Doxify** [comment]
@drtshock can you fix my name on Jenkins? It's "doxify" instead of "Doxify". Someone on irc tried to fix it but couldn't.

**Comment by Doxify** [comment]
Still happening on 0.0.4

https://imgur.com/64znEir
