### ISSUE TITLE
./f help

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#135]
Can you make it where we can select if we want to use the default /f help cause i dont want to configure an entire f help and i liked the orignial one better.

Maybe a true/false.

**Comment by MoeXIV** [comment]
*sigh* that's already a configurable feature. "use-old-help" I'm pretty sure. As Nick said, you may need to upgrade your build to see all the new features in the configuration,

**Comment by nsporillo** [comment]
![wastingmytime.png](http://puu.sh/hjMa9/f4e80e3aa5.png)

**Comment by LOOOOOOOL** [comment]
@MoeXIV stfu and let him answer;
