### ISSUE TITLE
Hitting faction members

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#136]
Within the latest build which was updated around 9-10 hours ago you're able to hit faction members

**Comment by MoeXIV** [comment]
The fix did not work? wut xddd
Because in the build 41 the hitting faction members bug should've been fixed 0.o

**Comment by Quizzes** [comment]
Build 42 has fixed this issue, i've done some testing seems to work fine

**Comment by drtshock** [comment]
'latest build' isn't a version. Please provide a specific version number where you're having the issue and older / newer versions where you aren't having the issue.

**Comment by Quizzes** [comment]
I've received the issue on b41, but once b42 i have never had this issue

**Comment by nsporillo** [comment]
@Quizzes really? I just tested locally and found I can in fact hit faction members, but not allys. 

I do believe this is a legitimate bug, and will write up a fix for it. (when I fixed damaging members, I accidentally removed the check so they can be damaged, which is erroneous!)

**Comment by nsporillo** [comment]
Fixed. Build 44 will have the fix. Going to try and get the ally bug fix in that build too.
