### ISSUE TITLE
Public chat role prefixes

### ISSUE THREAD

**Issue by Blowns** [drtshock/HCFProblems#139]
It would be way better if we could remove those

If we can, could you show me the file and line?

**Comment by Blowns** [comment]
http://prntscr.com/6wo13q

**Comment by nsporillo** [comment]
Located in the conf.json.

There is prefixAdmin, prefixMod, chatPrefixAdmin, and chatPrefixMod.

![conf](http://puu.sh/hmimi/792f7a368b.png)

is what you want to change, just set to "".

You might be asking what the prefixAdmin and prefixMod is used for? Commands like /f show when we list out members

**Comment by Blowns** [comment]
Hmm, 
  "chatPrefixAdmin": "",
  "chatPrefixMod": "",
still shows my faction role in public chat.

**Comment by Blowns** [comment]
Got it working, I had to update the prefixAdmin, then reload, then change it back then the chatPrefix worked.
