### ISSUE TITLE
Download Link

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#140]
Hey, where is the download link area now?
I'm getting this error.
http://gyazo.com/944be3c50b3c320008268650b8d60485

**Comment by nsporillo** [comment]
It hasn't changed, you're just not logged into the Jenkins..

If you're not logged in, it won't know you have access and will 404 you.

**Comment by LOOOOOOOL** [comment]
@nsporillo I cannot access it... I'm logged in.
http://gyazo.com/339d0f7e86058dff6ba68b470a26661c
