### ISSUE TITLE
Removed from CI?

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#141]
Can you add my username back to the CI?
I've been removed or something.

I'm logged in and I cannot access it.

usernam: temptingmc

**Comment by LOOOOOOOL** [comment]
@nsporillo @drtshock can you add me please quick? I need this asap as I deleted my plugin.

**Comment by drtshock** [comment]
Looks like Jenkins changed the case of your user id when I had to restart it last night. All fixed.
