### ISSUE TITLE
Question: lang.yml

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#147]
I have my old lang.yml from version 37, can I just use that with the new build 48 and then it auto gens the new lines, or do I have to reset it too?

**Comment by nsporillo** [comment]
There is no build 48.

You don't **have** to reset your lang.yml, but do not make new issues on this tracker about messages being wrong if you **dont** reset your lang. 

We're still in development, massively changed lang files aren't recommended unless you're prepared to add in / fix what is changed along the way in dev builds.
