### ISSUE TITLE
/F show without fac.

### ISSUE THREAD

**Issue by Chovpls** [drtshock/HCFProblems#149]
Please change the text in the command /f show (response). When you write as a player without a faction / f show, appears  ______. [Wilderness] ._____ it would be possible to change it and add the ability to change and go lang.yml. Please change it to "You're not in faction".

Thanks!

**Comment by Lilmac12312** [comment]
Can you elaborate with correct English?

**Comment by Chovpls** [comment]
My english is so bad. I modified the text as much as i can.

**Comment by nsporillo** [comment]
@Chovpls could you first verify you purchased the resource?

Should have asked this 20 days ago, sorry.
