### ISSUE TITLE
Land Change Messages?

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#15]
I've noticed that there's not a way to customize the leaving and entering messages of land.
This is an example of what I'm talking about.

 "&eLeaving &2Test&e, Entering &cTest"

**Comment by nsporillo** [comment]
Could you post a screenshot?

**Comment by MoeXIV** [comment]
http://prntscr.com/6hswfc
As messages when you leave and enter land.

This displaying once, not twice. For example, if I walk into safezone, I'd get that message, and that message only.

**Comment by nsporillo** [comment]
Ahh, I see now. 

Was looking in the wrong place on my end to fix this, the screenshot helps :)

**Comment by MoeXIV** [comment]
Do you mind if I submit some enhancments? 
Maybe a "{DTR}" and "{MAXDTR}" usable for most scoreboards. I can't get it to work for the scoreboard that shows perminamtly enless they type /f sb.

**Comment by nsporillo** [comment]
@MoeXIV Please separate your enhancement requests into specific issues. This allows me to address each one individually with commits and case by case support. Helps us organize things better. Thank you.

**Comment by MoeXIV** [comment]
Okay, ;)

**Comment by drtshock** [comment]
The second scoreboard in the config is for this if you want to use that. You can configure it 100%. The message itself is configurable in the TL.
