### ISSUE TITLE
Add more member/claim in faction !

### ISSUE THREAD

**Issue by Xcraft28** [drtshock/HCFProblems#155]
Hi i have buy the plugin yesterday, and i have change in the config file, the number max per faction member at 16 (Im french)
And claim : 20
But in my /f show it's still on ten. Screen : 
![claim](https://cloud.githubusercontent.com/assets/12109307/7332084/9aadc808-eb2e-11e4-82fc-00cdf5cfae9d.png)
It's claim on /10 but i want 20 claims per faction and 16 members.
And a other problem i want to delete line Balance and land value on my /f show command how i can do this ? 

Thanks for ur help i'm french.

**Comment by Chovpls** [comment]
Look in box / F show

![help1](https://cloud.githubusercontent.com/assets/1524393/7332261/274fe2a2-eb37-11e4-963d-37caa44a0f87.png)

**Comment by nsporillo** [comment]
"factionMemberLimit": 0,

in conf.json to set the faction member limit.

Setting

    faction-land-max: 20

in config.yml will work. Make sure you restart to have changes applied.

Also to remove a line from /f show just remove it from the show portion of config. Same goes with adding anything to /f show.
