### ISSUE TITLE
Lost access to CL

### ISSUE THREAD

**Issue by TJ1632** [drtshock/HCFProblems#157]
As the title states I've lost access to CL (the build server where I download it) and was wondering if I could get it back. My user name is TJ1632 and my name is Tyler Jackson.

**Comment by nsporillo** [comment]
Made sure you're signed in right?

I always ask this first because many people dont notice they're not signed in and think they lost access.

**Comment by TJ1632** [comment]
http://prntscr.com/6ytgxu

**Comment by drtshock** [comment]
All fixed :)
