### ISSUE TITLE
Tooltip translations

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#158]
The online tag in the /f who when you hover someone's name

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/config.yml#L87

**Comment by lyzha** [comment]
http://prntscr.com/6z2vhx I mean translate this online tag

**Comment by MoeXIV** [comment]
That's what Lang.YML is for. Take a look at it first.

**Comment by nsporillo** [comment]
@MoeXIV @drtshock it's hardcoded, it can't be changed in the lang. This is a legit issue.

**Comment by drtshock** [comment]
Ah. Apparently this isn't downstream yet. My bad :)

**Comment by lyzha** [comment]
:)
