### ISSUE TITLE
"Cool" Enhancments.

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#16]
It would be cool to add a couple variables to "f show" that would allow this:
http://prntscr.com/6hsyth

And some sort of variable to show DTR and MAX DTR in the scoreboard:
http://prntscr.com/6hsz22

**Comment by nsporillo** [comment]
Added the sidebar variables that were missing. 

You can now use dtr, maxdtr, land, maxland in the sidebar :+1: 

As far as the f show variable idea, will work on that tomorrow probably :smile:

**Comment by MoeXIV** [comment]
So theres DTR / MAXDTR now?
And when do you think this going to be added to the CI, I couldn't see the update.

**Comment by nsporillo** [comment]
https://ci.drtshock.net/job/HCFactions/10/

Sorry, had to push a build :tangerine:

**Comment by MoeXIV** [comment]
Won't work for me. It works for the scoreboard when leaving and entering different Faction land, but it doesn't work for the default scoreboard (The one that shows balance and your faction, with the default scoreboard named "i love dtr")

**Comment by nsporillo** [comment]
@MoeXIV for the first request, what does 30 stand for?

**Comment by MoeXIV** [comment]
Max number of people per Faction.

**Comment by MoeXIV** [comment]
Also, the "totalOnline" variable no longer works in the scoreboard.
http://prntscr.com/6iisnv

**Comment by Doxify** [comment]
It's been changed to {online}
