### ISSUE TITLE
Default factionl-less sidebar

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#161]
I was thinking about removing or having a different scoreboard on the right for factionless players

**Comment by nsporillo** [comment]
Not sure if this is really a good idea. Added complexity for questionable benefit.

Develop the idea a bit more so I can see what you mean.

**Comment by drtshock** [comment]
ehh. Can you provide justification?

**Comment by lyzha** [comment]
yes for example, the dtr tag for factionless people is fall to 0 which can be confusing for new players...

**Comment by MoeXIV** [comment]
True. Instead of having that there, it could say something such as "Type /f create to start" or some shit :)

**Comment by nsporillo** [comment]
Could just change code to let you change the 0 for facionless players dtr to like "Nil" or something.

Complicating the scoreboards for something so very minor is not good justification

**Comment by drtshock** [comment]
I agree with Nick. The justification given isn't enough to warrant us adding another scoreboard handler. We can however, add another option to show something else for DTR as well as something else instead 'factionless' if the player doesn't have a faction.

**Comment by MoeXIV** [comment]
That works! I like it.

@drtshock when do you think these features will be added to FactionsUUID, such as the new scoreboard features and custom f shows. I really would like to see it soon, and can you not just copy the code over?

**Comment by nsporillo** [comment]
@MoeXIV Isn't as easy as that, HCF currently uses a new method of handling variables which is elegant, but not necessarily something you transplant into UUID without something likely breaking. 

I'm going to work on this *someday*, but now my focus is HCF. Not sure if anyone else is going to want to work on this either. 

The customization of /f show, /f list, and the /f help is one of the star features of hcf :tongue:

**Comment by nsporillo** [comment]
Just noticed this is actually not an easy change because of the fact that the default DTR line in, for example, is 

    {dtr}/{max-dtr}

We'd have to handle both variables, and even so the `/` would still exist. Our current form of variable handling does not easily allow this enhancement. 

Will reconsider a different scoreboard for players that have no faction.
