### ISSUE TITLE
Fully configurable /f list header

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#162]
We can fully change the header in the f who why not in the f list :)

**Comment by nsporillo** [comment]
You can change the header? 

    header: 'Faction List {pagenumber}/{pagecount}'

**Comment by Quizzes** [comment]
I think he means like we can remove/make our own header. That just changes the text inside the ------.[ ].------ thingy.. I may be wrong, but i'm sure i'm correct.

**Comment by lyzha** [comment]
You're right Quizzes :)

**Comment by nsporillo** [comment]
Okay, this was added.
When you update to a new build, update the list.header value in config
The default is:

    header: &e&m----------&r&e[ &2Faction List &9{pagenumber}&e/&9{pagecount} &e]&m----------

but if you leave it how it is, then you'll have an unformatted /f list header when you update :grin:
