### ISSUE TITLE
How to fix block glitching.

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#163]
Block glitching seems to be a big issues on HCF, players are often in safe rooms which have wooden doors or other blocks you can right click to open. The thing is, that sometimes you can hit the player when you open a door for example, and even if the player is in a safe room protected by a door they can get killed.

My fix would be to place players in adventure mode when they are in other people's claimed land unless they are raidable, not sure if this is even possible but it's just an idea.

**Comment by nsporillo** [comment]
That.. that is actually a very interesting solution and would be extremely easy to implement..

Would need to explore ALL the possible cases to determine if it'd be a good idea. 
Adventure mode would eliminate using ender pearls inside enemy territory and such I think. I guess we'd really need to test it out on a live server to figure out if theres any quirks.

**Comment by HCFPvP** [comment]
I don't want to see this added. My developers fixed this a different way.

Infact @Doxify himself said in this that it shouldn't be fixed in this plugin.
https://github.com/drtshock/HCFProblems/issues/84

Do not add this as this would cause major issues with my plugin.

**Comment by MoeXIV** [comment]
I do really think this should be added, but if it's not compatible with other people then maybe an alternative. Kohi HCF has it so if you're within 2 blocks and you ender pearl onto a corner or non solid block, it bumps the pearl teleportation 0.5 blocks back.

Either way, this needs to be added.

**Comment by HCFPvP** [comment]
@drtshock close this ticket as you closed the #84 :+1:

**Comment by nsporillo** [comment]
@HCFPVP Who are you again? What is your username on the jenkins?

Your developers fixing a bug in the plugin means absolutely nothing. If there is an issue that should be addressed, just because you have a solution does not mean I shouldn't work on it for the project..

**Comment by Doxify** [comment]
Yeah, please don't close this, it would solve a huge issue on my server along with other hcf servers.

**Comment by MoeXIV** [comment]
@nsporillo , @HCFPvP is "TemptingMC" / "LOOOOOOOOOOOL".

But I also agree. This needs to be resolved one way or another, despite your developers plugins. That's like telling Nick to remove DTR because your plugin "conflicts" with it.

**Comment by HCFPvP** [comment]
nick, this suggestion you said yourself isn't going to work so why not close it? Us servers worked hard to fix the bug and now that all of a sudden they want it, they are saying random suggestions to fix it.


Either way, If this is added, make it configurable (default: false) as it would interfere with my plugin.

And @Doxify you shouldnt be lazy. Just get your devs to code an anti block glitching plugin.
TIP: NCP

**Comment by nsporillo** [comment]
@HCFPvP you were blocked from the tracker and thus receive no support. 

Your server fixing a bug and keeping it private only makes me want to fix it more. I do not care about exclusiveness what so ever, my goal is to provide a solid plugin for everyone.

**Comment by HCFPvP** [comment]
I don't need support. And I said, I just want it confirguable. Is that so
hard? Treat all the users here the same.

**Comment by Lilmac12312** [comment]
@HCFPvP Maybe @nsporillo will treat you like the rest once you gain some respect and quit evading your punishment.

**Comment by drtshock** [comment]
So HCFPvP is just LOOOL evading his ban. Rebanned him.

RE this issue: Factions isn't an anti cheat plugin.

**Comment by Doxify** [comment]
Yea, his server is called hcfpvp as well.

On Monday, April 27, 2015, Trent Hensler <notifications@github.com> wrote:

> So HCFPvP is just LOOOL evading his ban. Rebanned him.
>
> RE this issue: Factions isn't an anti cheat plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drtshock/HCFProblems/issues/163#issuecomment-96907818>
> .
>


-- 
Website - www.hydrapvp.com
Twitter - twitter.com/hydrapvp
Contact E-Mail - admin@hydrapvp.net
