### ISSUE TITLE
Pressure Plate Bug #3

### ISSUE THREAD

**Issue by HCFPvP** [drtshock/HCFProblems#164]
So I found another pressure plate bug.

Basically you can throw like a block, for example, a potato on an enemies pressure plate and then it would open their door.

If you need more info. I can record a demonstration video.

**Comment by drtshock** [comment]
You were banned from my issue tracker for 1 month. Stop evading your ban or you will be reported to github.

**Comment by MoeXIV** [comment]
LOOOOOL
