### ISSUE TITLE
enable pvp in neutral territory

### ISSUE THREAD

**Issue by NeThEr117** [drtshock/HCFProblems#165]
I can activate the pvp in a neutral faction? I tried hitting a neutral user within your terrotorio but will not let me. I tried to find solution in the settings but I have not found could help me?

-
I also want to know how to disable using a precione plate in a neutral territory and / or enemy that's possible?

**Comment by nsporillo** [comment]
You cannot hurt neutrals in their own territory.

You can hurt neutrals in your own territory if 

     enablePVPAgainstFactionlessInAttackersLand

is enabled in conf.json. (It is not by default)

![ah](http://puu.sh/htvsX/cab13fafeb.png)

Set that to true. Let me know if that fixes your issue (It was a little hard to understand what you mean from the issue description.. default relation is enemy)

**Comment by NeThEr117** [comment]
I modified the relationship default settings that are neutral, and with respect to the option I have selected but has not worked for me: /

http://i.gyazo.com/7f8677ea86bdcdede498dd5764a398d1.png
http://i.gyazo.com/08e097515755ae4a52950eaa6684f78f.png

**Comment by nsporillo** [comment]
There is no option to allow neutrals to hurt someone in their own faction. 
That is why the message says **declare them as an enemy**.

**Comment by NeThEr117** [comment]
You could add an option? in the future?

**Comment by nsporillo** [comment]
Not going to add an option for that. Declare the faction as an enemy...

If you set the default-relation in config.yml to true, then players wont need to explicitly declare factions as an enemy to pvp. It is by default. 

Hardcore Factions (HCF) typically has the default relation set to enemy. This plugin is for HCF servers. It doesn't make sense to go against the idea of an HCF server and request an option that is **not even present in FactionsUUID** on this plugin.
