### ISSUE TITLE
F status

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#166]
It seems like when it try to f status i can online get my status which is dumb because i obviously know if i'm online or offline (http://prntscr.com/6z2xl8) and i was thinking making 2 differents messages when someones is offline and online
For example i /f status player1 which is oline i get the message "Player 1 is online"
and i /f status a player2 which is offline  and i get "player 2 is offline since 5hours"

**Comment by nsporillo** [comment]
@lyzha 
/f status takes no arguments, it only displays the status of your faction.

/f show can be used for other factions.

**Comment by lyzha** [comment]
Alright but what about the second part of the suggestion ? Do you think its easy enough ?

**Comment by nsporillo** [comment]
@lyzha don't think it's a justifiable change, at least not with the information you provided..

Going to set this as closed for now, if you'd like you can continue and reply to this issue with a better explanation of what you're looking for. Language barriers may play a role here, and while it's unfortunate, we can't have incoherent issues clogging the tracker.
