### ISSUE TITLE
Faction Color Variable

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#169]
As the title states, I'm looking for a variable that basically color codes something the faction relationship.

For example if I do "/f show"
{color}<>&e-------{color}<>

That would make the <> green, and the "-----" yellow

**Comment by nsporillo** [comment]
Ehm, going to have to ask for more information. It is not clear what needs to happen for whatever you suggested to be added / fixed / whatever.

Please elaborate :grin:

**Comment by MoeXIV** [comment]
It's basically a colour code, but the colour code changes based on your relationship with said faction.

**Comment by Quizzes** [comment]
Or {faction-relation}, {color} could be used for other things. :+1:  Would like to see this added :hamburger:

**Comment by nsporillo** [comment]
So if this variable was used and you executed */f show*, it'd use the member relation color.

If you did */f show* **test**, and **test** was an enemy, it'd use enemy relation color? etc..

**Comment by MoeXIV** [comment]
Yes

**Comment by nsporillo** [comment]
Could I ask what this would be used for? @Lotteries @MoeXIV 

Without knowing the purpose, having trouble seeing where it'd be used.

**Comment by Lotteries** [comment]
If i'm correct, Moe no longer is running a HCF server.

But i think it would be used for lets say you wanted a fancier way of showing you're relation color instead of just coloring the name the old way, you could add colorful icons etc in the corner or what ever and it would be the relation color

**Comment by MoeXIV** [comment]
Who said I wasn't making a server using the HCF plugin? :P
Anyways, this could be used to colour things such as the header and basically the whole f show based on your relationship with said faction.

Really useful for fancy f show looks. I think it would be pretty cool to be honest.

**Comment by Lotteries** [comment]
@MoeXIV I see it now 'fancy f show looks'.. Maybe a few pointy arrows here and there.. xD

**Comment by MoeXIV** [comment]
Yeah, XD

**Comment by nsporillo** [comment]
This was added as `{color}`, did some testing and it seems to work how you guys asked.
