### ISSUE TITLE
Names in "f show" Do not Color

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#17]
Yes, I know by now you're most likely furious by the amount of times I post. All I'm trying to do is get all the bugs into your knowledge so you know how severe or not they are.

Basically, in "f show" the usernames that show, should be colored depending on the relationship you have with that faction; currently they are all just white.

http://prntscr.com/6hszxj

Also, if you have no Faction, most HCF servers (Not all, just pointing out), usually have an icon to show you're factionless. Instead of a blank space before your name, it's usually a "-" or "*". For example:
Faction: "[Test] [Owner] MoeXIV:"
Factionless "[-] [Owner] MoeXIV:"
Instead of: "[] [Owner] MoeXIV:"

**Comment by drtshock** [comment]
The no color thing is on purpose. The tag of the faction should have the color though.

We can add an icon for chat for factionless players.

**Comment by MoeXIV** [comment]
Why are the players supposed to be white?
Is there a way to change it, in the configuration?

**Comment by Doxify** [comment]
I'd like both the icon and colored "tag" or name for players not in a faction please.

**Comment by MoeXIV** [comment]
Good to see the waiting tag. I'm glad this was taken into consideration. :)

**Comment by nsporillo** [comment]
Albeit this was made first, since it's a split issue I'm going move support for the feature to https://github.com/drtshock/HCFProblems/issues/51.

**Comment by MoeXIV** [comment]
@nsporillo What about the color for usernames in "f show"?
