### ISSUE TITLE
Donkey glitch

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#170]
I was given information about being able to glitch into bases using donkeys / horses. Basically what happens is when you stand on a flat surface with an air space of about 3-4 blocks and try jump on the donkey/horse you get glitched into the base.

I'm not 100% if this exactly works as the information was passed on by a member who plays my server but I'll try re-duplicate the glitch.

**Comment by drtshock** [comment]
Reopen this when you can duplicate it. Preferably in a video that you can show us.
