### ISSUE TITLE
Infinite claims/power

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#171]
A faction classic faction could claim as much as they want, op faction for example :) When i say classic faction it's not safezone or warzone

**Comment by Quizzes** [comment]
Make sure a operator/owner/admin is not in that faction. If i'm correct they can bypass the claim limit. I may be wrong.

**Comment by nsporillo** [comment]
@Quizzes 

    if (ownedLand >= myFaction.getMaxLand() && forFaction.isNormal()) {
            error = P.p.txt.parse(TL.CLAIM_LIMIT.toString());

@lyzha is more or less looking for an API method to set a specific factions max land, which is missing from our current implementation.

**Comment by lyzha** [comment]
Quizzes is right but if a operator is not here they wont be able to do it on their own

**Comment by nsporillo** [comment]
@lyzha how do you purpose we allow op factions..? A setting somewhere that lets ALL factions claim unlimited..? Is it per faction?

**Comment by lyzha** [comment]
Per faction sir! :)

**Comment by nsporillo** [comment]
How exactly do you plan on making an OP faction?

I can add some more logic to allow for this, but I don't think an entire new command just for OP factions is appropriate..?

**Comment by nsporillo** [comment]
@lyzha for example, adding the logic would allow for 3rd party plugins to handle the OPFaction part. After all this is HCF, not OPF. I dont mind adding the code but I do mind adding a command.. maybe i'll release a OPFaction jar to work with HCF...?
