### ISSUE TITLE
Allies with Invis potion effects - Can't see name & Ally Damage.

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#172]
Basically when an ally drinks an invisible potion, you cant tell who the person invisible actually is, until you hit them as it displays in chat. Is there a way to make it so if allies are invisible, their nametag will still show up?

Also I've noticed that when you hit an ally, their health is taken off as normal, could you make it so they take reduced damage, so they don't die in 3 hits, as its happened a few times & players are complaining, making making it configurable how much percent of damage they'd take?

**Comment by Lilmac12312** [comment]
+1 for this idea. So basically when the ally or faction member drinks an invis potion you can see there name tag but if they're not an ally you cannot see their name tag

**Comment by MoeXIV** [comment]
I personally like the reduced damage part. The tag part will be always be invisible for 1,7 clients as that's how it's programmed. It's basically like favouring those using 1,8 ;(

**Comment by Quizzes** [comment]
:+1: ProtocolLib could do this, but that would make it a dependency :(

EDIT: Psst.. @nsporillo hates ProtocolLib :hamburger:

**Comment by drtshock** [comment]
Their name tag will show up no matter what if you are on 1.8+ and are using the name tag feature.

**Comment by Quizzes** [comment]
@drtshock Most *all* HCFactions servers use 1.7, 1.8 ruins the pvp aspect of the game. I've only seen one 1.8 HCFactions server out of the 100+ Servers out there. It would be nice to have it added anyway, the more the better? :hamburger:

**Comment by Lilmac12312** [comment]
@Quizzes I agree with you as 1.8 pvp is ruined.

**Comment by nsporillo** [comment]
If the invisible potion is a splash one, we could listen for that event and *try* to do something with nametags. If it's a regular potion then we'd have to do something like check for potion effects when a player moves. Even then we would probably run into issues if we're messing with the nametags (specifically with the tablist..?)

I suppose this needs more justification. If a fix was concise, then I guess we wouldn't need some convincing that it should be added.
