### ISSUE TITLE
Mobs don't attack you in your own territory

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#173]
Make it configurable... of course.

**Comment by MoeXIV** [comment]
I'm only waiting for TemptingMC to comment:
"remove this, never add it. my developersz alredy fixed it!!!!!!!"

But in all honesty, this is a nice idea. c;

**Comment by Doxify** [comment]
aha that's why I added the "make it configurable... of course" part

**Comment by MoeXIV** [comment]
Haha!

**Comment by Doxify** [comment]
Bump.

**Comment by Lilmac12312** [comment]
:+1: for this idea, would be really nice.

**Comment by KriticalPvP** [comment]
+1

**Comment by nsporillo** [comment]
This can be done, thinking to just cancel the entity target event on a player if that player is in their own faction and it is configured.

**Comment by nsporillo** [comment]
Came up with some experimental code if anyone wants to test it out a bit? 

During my testing there was a few situations where monsters would still target / attack a player in their own faction. So what I guess I want to see if you guys feel the experimental code is sufficient.

Contact me @ nsporillo@gmail.com with your CI username for a copy. It will be Build 51+, with just this experimental addition with some debug code built into it.

**Comment by nsporillo** [comment]
Placing this issue on hold. Did not find a very effective way to prevent mobs from targeting players in their own territory. Furthermore, should we even be worrying about this? It is after all, hard-core.

**Comment by nsporillo** [comment]
Closing this, havent had any interest nor did I find an consistent and efficient way to accomplish this. Not to mention we're talking about HCF, not Light-core factions :stuck_out_tongue:
