### ISSUE TITLE
ownedAreaPainBuild set to false but still hurting players

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#174]
![pain](https://cloud.githubusercontent.com/assets/9636316/7403908/20bf623a-ee90-11e4-8409-1e9d01bd4993.gif)

Also I should add that all the other options with "pain" in them are set to false.

**Comment by Doxify** [comment]
Bump.

**Comment by Lilmac12312** [comment]
Would be nice to have the implemented :)

**Comment by Doxify** [comment]
Bump

**Comment by KriticalPvP** [comment]
Vouch +1

**Comment by nsporillo** [comment]
Try setting

    ownedAreaDenyBuild: false

**Comment by Doxify** [comment]
Nope, doesn't work.

**Comment by Doxify** [comment]
Ah, I see, that option only makes it so when you mine blocks in someone's land it doesn't hurt you.

It still hurts me if I try to open a door.

**Comment by nsporillo** [comment]
@Doxify 

Try 

    territoryEnemyPainBuild: false

**Comment by Doxify** [comment]
That was already set to false, in my original post I already stated that I had all "pain" options set to false.

**Comment by lyzha** [comment]
:+1:

**Comment by Doxify** [comment]
Can we please get a fix for this nick? It's really important to HCF as players should not be able to use the saferooms of others and to do that I would need to disable the use of pressure plates in claimed land, however when you do that if a player steps on them for one second they instantly die due to the harm feature.

**Comment by nsporillo** [comment]
Set 

    actionDeniedPainAmount: 0

for now, will look into a fix though.

**Comment by Doxify** [comment]
![](http://hydrapvp.com/ahh.gif)

I've already tried that, nothing works :/

**Comment by nsporillo** [comment]
snippet:

        boolean deny = rel.confDenyBuild(online);

        // hurt the player for building/destroying in other territory?
        if (pain) {
            player.damage(Conf.actionDeniedPainAmount);
            if (!deny) {
                me.msg(TL.PLAYER_PAIN_CLAIM, action, otherFaction.getTag(myFaction));
            }
        }

if it is set to 0, no damage will be made... does not make sense how it everything just `doesnt work`..

**Comment by Doxify** [comment]
My dev told me how to fix it, there's another setting you need to disable.

![exmtprk](https://cloud.githubusercontent.com/assets/9636316/7558465/ccb1d5ce-f759-11e4-937a-a3a156830900.png)

**Comment by nsporillo** [comment]
This should be all set then.
