### ISSUE TITLE
Translate Login messages

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#175]
When you edit the login/logout messages you can't translate the True Or False tag that would be nice :)

**Comment by nsporillo** [comment]
Screenshot please?

Need some context

**Comment by lyzha** [comment]
http://prntscr.com/72k918

**Comment by nsporillo** [comment]
.. what is it in english so I can find what TL isn't being translated?

**Comment by lyzha** [comment]
There you go :) http://prntscr.com/72wel0

**Comment by nsporillo** [comment]
Note to self: Perhaps individual TL for true / false and then use that throughout the plugin if not already. @nsporillo

**Comment by lyzha** [comment]
It's not done already I have looked into :) :+1:

**Comment by lyzha** [comment]
Note to @nsporillo done? <3

**Comment by nsporillo** [comment]
@lyzha not yet, will work on it when i get a chance (i've been really time constrained lately)

**Comment by nsporillo** [comment]
Whats new:

![aye](http://puu.sh/iy8bI/05d6261d4f.png)

you can now configure the TL appropriately. Sorry for the super long wait on this.
