### ISSUE TITLE
{online} and {offline} give error(s) in chat

### ISSUE THREAD

**Issue by Quizzes** [drtshock/HCFProblems#176]
Title pretty much sums it up. Build 44 and up cause this. It does not put out a error in MY console, (or atleast i don't see it, haha) here is a picture.

![ofi3al7](https://cloud.githubusercontent.com/assets/9434234/7435732/42526c1e-f014-11e4-9191-161d4b66cdc6.png)

**Comment by clerkk** [comment]
It works fine for me, weird.

**Comment by Quizzes** [comment]
Seems to have fixed it, apparently you HAVE to have a permissons plugin for it to work, because of the tooltips showing what rank the player is. Closed.
