### ISSUE TITLE
/f home doesnt cancel when moving.

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#177]
I don't use essentials teleport time, so I use the one in HCFactions, although the time is set to 10 seconds, players can run around during this time. Are you able to make it so if they move, the teleport is canceled?

**Comment by nsporillo** [comment]
@SaiCoFlu what is your username on the jenkins?

**Comment by SaiCoFlu** [comment]
@nsporillo My username is "Flu".

**Comment by nsporillo** [comment]
@SaiCoFlu thank you.

What do you mean you dont use essentials teleport time? Do you not have essentials installed?

**Comment by SaiCoFlu** [comment]
Nope, I do have essentials now, but I was planning to not use it until this problem popped up. But I'd assume others would want to see this to, as it's done by most HCF servers.

**Comment by nsporillo** [comment]
was this solved when you installed essentials or is there still an issue with the cancel on move?

**Comment by MoeXIV** [comment]
You shouldn't rely on other plugins for yours to work properly. That would require essentials to be a dependency.

Some people don't use essentials (me), and I had to install essentials for the soul purpose of the f home

**Comment by nsporillo** [comment]
@MoeXIV It was merely a question to gain some more information. I did not design how /f home works nor were there any requests to change anything about it. When I wrote the /f stuck code, it works with and without essentials, but with essentials obviously slightly better.

**Comment by SaiCoFlu** [comment]
yes it was solved @nsporillo , But I'd prefer not using Essentials.
