### ISSUE TITLE
How can I disable the damage a player takes when they try to use something in someone's claimed territory?

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#178]
Title

**Comment by Lilmac12312** [comment]
Isn't there an option within the config.yml? Correct me if I'm wrong.

**Comment by Doxify** [comment]
It doesn't work :/

**Comment by nsporillo** [comment]
territoryEnemyPainBuild: false

and players still get damaged when they use something?

Perhaps it is:

    ownedAreaPainBuild: false

if neither solve the issue, i'll look into the source code and figure out exactly.

**Comment by nsporillo** [comment]
@Doxify try the above but this is a duplicate of https://github.com/drtshock/HCFProblems/issues/174 so gonna close this one.
