### ISSUE TITLE
Can't change colour of Allies!

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#179]
Hello,

  "colorAlly": "BLUE",

Whats wrong with this?
why is it not working?

also how do I change how chat looks

so instead of test (username) 
 Its &6[&(faction)(relationcolor)&6]

?

Thanks!

**Comment by Lilmac12312** [comment]
If you're wanting the blue which is &9 it's called "DARK_BLUE"

**Comment by KriticalPvP** [comment]
No, &9 is "BLUE"

**Comment by KriticalPvP** [comment]
But I got it fixed, thank anyways @Lilmac12312 :D
