### ISSUE TITLE
Chat Formatting?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#180]
Hello I am running EssentialsChat, because ChatEX doesn't work with this plugin : p

How do I format my chat like Kohi's?

So &6[[faction{relationcolor}]&6] 

The prefix?

Thank You!

**Comment by Lilmac12312** [comment]
You do so within Essentials configuration file under "Essentials Chat". It's quite basic and straight forward.

**Comment by KriticalPvP** [comment]
I am aware of that, but I don't know what to put? what are the strings?

**Comment by KriticalPvP** [comment]
Limit reached.You can't claim more land!

**Comment by KriticalPvP** [comment]
@drtshock ?

**Comment by drtshock** [comment]
Add more power. This is an issue tracker, not a dumb question tracker :(
