### ISSUE TITLE
I have made a permanent faction. but I can only claim 36 land?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#181]
Hello, I have made a perm faction for my KoTH plugin however, I cannot claim more than 36 land.
I don't want normal factions to be able to claim more than 36, I know I can edit this in the config, and I believe it's default 36.
However my permanent faction needs more than 36 claims?

is there a command or do I have to change the value, and then change it back? 

Thank You!

**Comment by Lilmac12312** [comment]
You might be able to bypass the limit by doing /f admin but not sure if that would work.

**Comment by KriticalPvP** [comment]
/f admin is the command to leader someone?

**Comment by nsporillo** [comment]
./f admin does not bypass the limit. This is similar to https://github.com/drtshock/HCFProblems/issues/171

**Comment by KriticalPvP** [comment]
I fixed this, I set the max land to what I needed and then set it back,
