### ISSUE TITLE
/f admin BUG?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#182]
Problem:

I am leader of a faction. and if I /f admin ( myself ) it disbands the faction? : p

**Comment by clerkk** [comment]
Try & keep all your problems into one, posting loads of small problems in separate issues clogs up the open issues.

**Comment by drtshock** [comment]
No, keeping separate issues in separate tickets is the point of having a tracker vs a support forum.

As far as your issue, the functionality is supposed to be nothing happening.

**Comment by nsporillo** [comment]
@KriticalPvP could you provide a screenshot of this?

Also, the steps to reproduce the issue?

I'm assuming it's just something like:

1) make faction
2) do /f admin
3) faction disbands and it shouldn't?

If you could provide some more details that'd be great

**Comment by Lotteries** [comment]
@nsporillo  That is correct, if you are the only one in a faction and you type /f admin it should say something along the lines of "&cYou are the only one in a faction, you can not admin you'reself!" and if you're not the only one in the faction say something like "&cInvalid Arguments! /f admin <username>!"

**Comment by KriticalPvP** [comment]
Yeah, sorry @Lotteries is right, when you type /f admin (yourname) it disbands it.

**Comment by nsporillo** [comment]
Odd. Will need to go in and test this but it doesn't appear to be a critical bug. If the faction is of 1 then they will probably be fine to set their faction back up. 

Will tag as a bug so it gets my attention next time I check the tracker, but still need to confirm.

**Comment by nsporillo** [comment]
@KriticalPvP what is the intended functionality? I tested this and it seems if you are already the faction admin then running /f admin on yourself will kick you out of the faction and it is a one man faction it will disband..

What did you want it to do..?

**Comment by nsporillo** [comment]
@KriticalPvP going to need some more information here if we're going to get anywhere with this. It does not appear to be a bug, and the functionality isn't that much of a game-breaker...

Low priority fix that needs justification.

**Comment by KriticalPvP** [comment]
If you are in a solo faction ( You are leader ) and you /f admin yourself it disbands the faction. Not a huge issue but still worthy of fixing
