### ISSUE TITLE
HCF Chat / Essentials Chat Fix Needed Urgently!

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#185]
Hello,

I am unaware on how to set a prefix for the faction name?

so put it in brackets.

so it looks should like this http://prntscr.com/71g034

I think I'm just overlooking something?
but I have the thing set right?

Here is what I have: from conf.yml

  "factionOnlyChat": false,
  "chatTagEnabled": true,
  "chatTagRelationColored": true,
  "chatTagReplaceString": "[FACTION]",
  "chatTagFactionlessSymbol": "?",
  "chatTagInsertAfterString": "&6[",
  "chatTagInsertBeforeString": "&6]",
  "chatPrefixAdmin": "",
  "chatPrefixMod": "",
  "chatTagInsertIndex": 0,
  "chatTagPadBefore": false,
  "chatTagPadAfter": true,
  "chatTagFormat": "%s§f",

Here is what I would like:

http://prntscr.com/71g034

Thank You!

**Comment by KriticalPvP** [comment]
@drtshock @nsporillo

**Comment by drtshock** [comment]
DO NOT FUCKING TAG US OR BUMP YOUR ISSUE. WE SEE ALL ISSUES POSTED AND ALREADY GET NOTIFICATIONS.

**Comment by drtshock** [comment]
As far as your issue, you already asked this on another ticket and you have some weird values that you changed here. Reset your conf.json to default and it should work by just throwing ess chat on there with the chat tag in its config.
