### ISSUE TITLE
/f who Internal Error.

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#186]
Hello, after doing what drtshock instructed on fixing faction prefixes.

everytime I type /f who i get this message:

http://prntscr.com/71huza

Also it didn't fix the chat. it completely broke it. if someone has any idea on how to fix it ( like kohi's ) that would be amazing! Thank you.

Sorry for the truckload of threads. just got a new plugin & got to play with it!

Chat now looks like: http://prntscr.com/71hwqz

And I would like it to look like: http://prntscr.com/71hxd6

Thank You!

- Michael

**Comment by drtshock** [comment]
What is the error?

**Comment by KriticalPvP** [comment]
http://pastebin.com/ddQLg2CT

**Comment by drtshock** [comment]
Do you have a permissions plugin?

**Comment by KriticalPvP** [comment]
pEX & ChatEx

**Comment by KriticalPvP** [comment]
- Update -

Fixed Chat & Error I just need the internal error problem fixed. : D

I uninstalled ChatEx & replaced it with EssentialsChat.

Being Truthfully honest I don't know how I fixed the error. I wasn't in a group since I had recently reset my pEX Users. so that may have been why. Thank You Very much!

- Michael
