### ISSUE TITLE
Where is the download?

### ISSUE THREAD

**Issue by ScarOG** [drtshock/HCFProblems#188]
I have had this plugin for about a month, I checked ci.drtshock.net for the plugin, I have seen nothing there retaining the plugin, and went to ci.drtshock.net/job/HCFactions/ as well nothing worked maybe I lost access or there is a whole new download system?

**Comment by ScarOG** [comment]
Problem accessing /job/HCFactions/. Reason:

    Not Found

**Comment by Lilmac12312** [comment]
This is because you're either not added to the Jenkins

**Comment by drtshock** [comment]
What's your username on my CI? When I rebooted that VPS, all usernames got reset to lowercase so I'll just have to adjust yours in the permissions.
