### ISSUE TITLE
Leaving / Entering messages?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#189]
Hello!

How do I change this: http://prntscr.com/71ukh9

To This!: http://prntscr.com/71unho And how can I add the text &e(&cDeathban&e) after the name of the fac? What would I change it to?

**Comment by KriticalPvP** [comment]
- Update!

- Fixed Msg

Can't make it two lines?

Here's what I got. http://prntscr.com/71vpmr

I have gathered that it's not \n but what do I use instead?

**Comment by nsporillo** [comment]
It is a single line message sent. A newline won't change that.

**Comment by KriticalPvP** [comment]
How do I make it two lines?

**Comment by nsporillo** [comment]
You don't, it's a single line message that is sent to a player.

**Comment by KriticalPvP** [comment]
http://prntscr.com/71ukh9 Uses your plugin? : p

**Comment by KriticalPvP** [comment]
Well I know they use it : p

**Comment by nsporillo** [comment]
You're showing me a screenshot of someone leaving wilderness, and then entering wilderness. 
Of course there will be 2 separate line messages being sent..

**Comment by KriticalPvP** [comment]
I think I sent you the wrong screenshot. http://prntscr.com/71unho  is the right one?

**Comment by MoeXIV** [comment]
PurePVP, ParaPVP and HCTeams all use that sort of entering and leaving message. They also all have custom faction plugins

**Comment by KriticalPvP** [comment]
Yes, and the screenshot I provied was not from any of those servers, but from a server I Know uses This Plugin : p

**Comment by drtshock** [comment]
Please create more clear and concise tickets. If you are requesting a feature, lay out EXACTLY what you are looking for instead of us having to say "what" 20 times to get you to say anything useful.
