### ISSUE TITLE
Ability to configure commands header

### ISSUE THREAD

**Issue by Russiaa** [drtshock/HCFProblems#19]
Add a config option to the header and footer of the commands.

Configure these: http://prntscr.com/6i0nop
In my opinion the default doesn't look to great, and It would be nice to change it.

**Comment by Doxify** [comment]
I'd like this too.

**Comment by nsporillo** [comment]
Good suggestion. Will work on this :+1:

**Comment by Doxify** [comment]
Until it's added, you can actually add a footer yourself in the config.yml

![510wpwp](https://cloud.githubusercontent.com/assets/9636316/6701421/a0f7e2de-ccd9-11e4-9745-c6ceabc7d936.png)

**Comment by Russiaa** [comment]
Yeah that is true, I can just add a footer myself.
So It isn't that important, but the header definitely needs improvement

**Comment by nsporillo** [comment]
Set this to waiting, will work on when I wake up :)

This enhancement in particular won't have very high priority though, as it isn't critical to the functionality of the plugin and is relatively difficult to implement. (need to redesign how we titleize something, which changes based on the input size).

**Comment by MoeXIV** [comment]
Good to hear. Hope to see an update soon. :+1:

**Comment by Russiaa** [comment]
Any update on this?

**Comment by nsporillo** [comment]
@Russiaa this was added for /f show in builds 29 and up. /f list will come soon.

Going to close this issue as it was added.
