### ISSUE TITLE
New thread fully explaining feature I would like added

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#190]
Pretty much. I would like to be able to do this: http://prntscr.com/71unho

So instead of a leaving and entering msg.
I would like a 
Leaving:
Entering:

so right now there is only

faction-leave:

I am requesting that you add

faction-enter:

so we can have two lined msg's

like this one: http://prntscr.com/71unho

Instead of this http://prntscr.com/71ukh9

so chat will send this:

Entering: faction
Leaving: otherfaction

**Comment by Doxify** [comment]
you can easily just do this with worldguard farewell and entering flags............

**Comment by KriticalPvP** [comment]
I mean while entering Faction Territory?

**Comment by MoeXIV** [comment]
What server is the one you "swear" is using this plugin with that requested feature?

**Comment by Quizzes** [comment]
This can already be done using \n in you're message. If you didn't know \n creates a new line. (This works in most plugins and stuff, but it might not work here. But i'm pretty sure it will!)

**Comment by KriticalPvP** [comment]
It doesn't work.

**Comment by KriticalPvP** [comment]
@Quizzes I tried that first : p

**Comment by Quizzes** [comment]
Maybe spam you're space bar until it makes a new line in chat, thats what i did.. But it requires lots of trial and error. I don't think this should be added. Most  people like the current one (Unless it was configurable such as <code>two-line-message</code> or something like that..)

**Comment by nsporillo** [comment]
@Quizzes @KriticalPvP Looks like a \n does not work unless it is specifically accounted for in the code base, which I believe is not. [bukkit thread](https://bukkit.org/threads/new-line-line-break-in-messages-or-chat.47939/)

I believe a single line is sufficient, and adding complexity for two line messages is a bit too much of an ad hoc request for this branch.

**Comment by KriticalPvP** [comment]
@Quizzes what HCF do you run? : D

**Comment by KriticalPvP** [comment]
Thank You @nsporillo!

**Comment by MoeXIV** [comment]
You never answered my question,
"What server so you swear has this feature and is using this plugin to do so?"

**Comment by KriticalPvP** [comment]
@MoeXIV Sorry, Hcfpvp.net TemptingMC owns it. I know him a mile away. whatever username he uses. : p he is the one with the short temper LOL :)

**Comment by MoeXIV** [comment]
You're right. He does use this plugin and he does so that. I wonder how :/

**Comment by KriticalPvP** [comment]
@MoeXIV I'm guessing he uses spaces? just like the other person

**Comment by KriticalPvP** [comment]
@MoeXIV You run pot-up.com right?

**Comment by KriticalPvP** [comment]
@MoeXIV Fixed it! http://prntscr.com/731zod 43 spaces & a ton of trial & error I got it!
