### ISSUE TITLE
tps lag problems?

### ISSUE THREAD

**Issue by NeThEr117** [drtshock/HCFProblems#191]
hello I posted earlier here and I haven't managed to solve this problem. wanted to see if any of you who are here in this forum knows how this problem solution :).
I leave you pictures of my timings and photos of my tps maybe some of you will also step. and you can help me :D
I have a dedicated server only 32GB of RAM for the factions. and still fall tps :/ on 200 players online 

TIMINGS: http://timings.aikar.co/?url=11016123
SCREENSHOT TPS AND USERS ONLINE : http://i.gyazo.com/af42d4a971b94a0fdcde5df4fb58ca85.png

please if anyone knows why this happens that I can help I'd appreciate it :)

SORRY FOR MY BAD ENGLISH <3

**Comment by nsporillo** [comment]
![screen shot 2015-05-07 at 7 03 08 pm](https://cloud.githubusercontent.com/assets/1480197/7527655/cb47103e-f4eb-11e4-8038-0d1fac5cc9a6.png)

Looks like only %2. I'm 90% sure it says "Factions - tickEntities" because your world is named "Factions".

**Comment by NeThEr117** [comment]
there any way to fix it? if they could help me I would appreciate it :D

**Comment by nsporillo** [comment]
Do something with the entities in your main world, i guess. 

Aside from that, theres not much I can help with. This issue is not with HCF, but something else, so it'll be closed.

**Comment by MoeXIV** [comment]
Maybe install "ClearLagg".

**Comment by KriticalPvP** [comment]
@MoeXIV @NeThEr117 ChunkEntityLimiter works well too. Kohi uses it : D
