### ISSUE TITLE
Lang.yml variable

### ISSUE THREAD

**Issue by youngpvprock** [drtshock/HCFProblems#192]
I would like to know if you can replace the variable You for the name of the player, so for example if i translate to spanish "You give the leadership of the faction ...blabla" , in spanish it appear like "You le has dado el lider de la faction.." So here it's a problem for translate it, i think it would be better if just appear the name of the player for servers in other lang.

**Comment by Quizzes** [comment]
Could you please try to explain this better? I fail to see what you want.. There are pre-defined language files for download somewere i'm pretty sure. ᕙ༼ ◉_◉༽ᕗ

**Comment by youngpvprock** [comment]
So i can't translate the variable "You" and if a message that uses this it's in other lang, then the phrase is so strange. 

Another question that i have while i was trying to config, the nametags and the tab show the relationship with other factions and also the fac name, it's possible to remove the faction and just let the colour relation?

**Comment by lyzha** [comment]
Yes, I see he wanted to replace you with the player username which is a good idea I guess because I get trouble translating these kind sentences too... So either make the username show instead of the "you" or make two different messages and both can be custom

**Comment by nsporillo** [comment]
English is the main lang for this plugin, the defaults are set to make sense in English. I guess we could rephrase the sentence and introduce a string replacement for player usernames... but it's a bit of a stretch and the author of this issue has been gone forever.

**Comment by lyzha** [comment]
You're not planning on adding that then?
