### ISSUE TITLE
Prevent certain chunks for being claimed

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#193]
All in the title i guess ;)

**Comment by Doxify** [comment]
claim them as warzone or safezone

**Comment by MoeXIV** [comment]
lol, exactly xddd

**Comment by lyzha** [comment]
nah warzone or safezone prevent also blocks from being destroyed only want non claimable...

**Comment by Doxify** [comment]
You can allow users to break blocks in warzones.

**Comment by drtshock** [comment]
huh

**Comment by nsporillo** [comment]
@lyzha could you provide more justification for this issue?

Why should it be added? we'd have to go a bit out of the way to track chunks you dont want to be claimed and there is already a way to do this as @Doxify noted.

**Comment by Lotteries** [comment]
@nsporillo Here is my justification, i think it should be added because it would be useful for KOTHs, you should be able to configure the message that you get when you break a block in the un-claimable chunk, such as &eYou can not break that block here!

**Comment by lyzha** [comment]
Yes :)

**Comment by lyzha** [comment]
But also to prevent claimed base near the spawn but without player not being able to break blocks

**Comment by KriticalPvP** [comment]
Make a selection e.g. hat

/rg flag hat f claim deny

**Comment by drtshock** [comment]
Scaredy: or you could just deny /f claim in the worldguard region.

**Comment by drtshock** [comment]
We won't be adding this. Claim it with a permanent faction, disable claiming in that world, or region it with WG and deny claim commands (though they could still claim radius).
