### ISSUE TITLE
Removed From CI?

### ISSUE THREAD

**Issue by SweetHomeHCF** [drtshock/HCFProblems#195]
Removed from CI?
Jenkins Name: xSander_

**Comment by clerkk** [comment]
Probably because you leaked the plugin on LeakForums.

**Comment by Lotteries** [comment]
@clerkk Can confirm, found the link. And it was shortly removed after.. @drtshock @nsporillo Keep a eye on LeakFourms.org ;)

**Comment by SweetHomeHCF** [comment]
That is another HCF Plugin but not this HCF Plugin I didnt leak this one
can i get it back?

**Comment by Doxify** [comment]
lol

**Comment by SweetHomeHCF** [comment]
Hi @Doxify

**Comment by SweetHomeHCF** [comment]
I closed The LeakForums Thread

**Comment by Doxify** [comment]
I don't think it matters if you closed it or not.. should have never leaked it man.

**Comment by SweetHomeHCF** [comment]
its not this plugin so it doesnt matter

**Comment by SweetHomeHCF** [comment]
Im starting up a plugin thats the reason why i buyed this plugin so @drtshock can give my money back :D

**Comment by Lilmac12312** [comment]
There is no refunds bucko. Good luck with getting your well spent $30 which you then made fly away due to leaking the plugin, or at least trying to leak it lmao. 10/1 would leak again.

**Comment by drtshock** [comment]
ass
