### ISSUE TITLE
HCF /f show problem

### ISSUE THREAD

**Issue by bigbubba69** [drtshock/HCFProblems#196]
I am getting an internal error while doing /f show
http://prntscr.com/73adua

**Comment by KriticalPvP** [comment]
@bigbubba69 I have been getting this error too, However I fixed it. /f disband. & /f create (name) You need to re-create the faction. Hope this helped!

**Comment by drtshock** [comment]
What's the error? And what's your username on the CI so I can confirm you purchased this?

**Comment by Lilmac12312** [comment]
Instead of disbanding the faction and re-creating it why don't you check the console for any logs and post them in a file so the developers can find the issue?

**Comment by KriticalPvP** [comment]
@Lilmac12312 I'm not saying do that for a permanent fix, but for short term.

**Comment by nsporillo** [comment]
Closing this because we cannot confirm if @bigbubba69 has a license or not.
