### ISSUE TITLE
Constant error in Console - Latest Build.

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#198]
Okay, so me & my developer have a plugin which hooks into Factions, but this error always seem to persist and we don't have any idea what is causing this, and I imagine you guys would.

Here is the error I'm receiving. It happens every time I or a player hits each other.
https://gist.github.com/SaiCoFlu/2cb407bf5a8575399044

My Developer doesn't know if he'd be allowed on here as he wasn't the one who purchased the plugin, but he asked why ""FPlayers.getInstance().getByPlayer(player)" is giving the errors.

**Comment by drtshock** [comment]
Use a gist please.

**Comment by SaiCoFlu** [comment]
@drtshock Updated with the gist.

**Comment by drtshock** [comment]
Don't use /reload or plugman.
