### ISSUE TITLE
f stuck bug/glitch

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#199]
When doing /f stuck you can use it to glitch into bases.

people go up against walls and type /f stuc & at some locations it tps them into the base instead of ontop

**Comment by nsporillo** [comment]
f stuck is certainly not perfect, thinking a good fix would be to search for the nearest, safest location inside the wilderness?

**Comment by Lilmac12312** [comment]
I think that would be a good idea or maybe check the blocks around the player and if most consists of air then cancel the f stuck?

**Comment by KriticalPvP** [comment]
@Lilmac12312 +1

**Comment by nsporillo** [comment]
there's a ton of different ways to do this, think going to run a spiraltask to find the nearest chunk of wilderness within `radius`. For now maybe just take away perms to use the command if it's bothersome.
