### ISSUE TITLE
new variables in sidebar do not work with latest build

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#20]
![oynwxrr](https://cloud.githubusercontent.com/assets/9636316/6703179/bc54ee94-ccf4-11e4-9d97-483b42a74e7e.png)

**Comment by nsporillo** [comment]
Is this the default sidebar? 

In https://github.com/drtshock/HCFProblems/issues/16 , reporter noted it was not working with default boards. 

I'm finishing up the update now, so that both work great. Also going to go in and make the config and default settings pretty

**Comment by Doxify** [comment]
Yes it is the default sidebar.

**Comment by MoeXIV** [comment]
Thank you!

**Comment by nsporillo** [comment]
![Example](http://puu.sh/gF4FV/17fea0dd06.png)

Completed fixes which will produce the above. 

Remember, decimal format from the lang file is used to format the scoreboard dtr as well!
