### ISSUE TITLE
Change Faction Header

### ISSUE THREAD

**Issue by MindServers** [drtshock/HCFProblems#200]
I would like a way to change the faction header. What I mean is that for example if you do /f show, it shows up as like:

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ .[faction]. _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

However this is a really long header with all the underscores and it wraps onto 2 lines which looks like this:

--->      _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ .[faction]. _ _ _ _ _ _ _ _ _ _ _ _ 
--->      _ _ _ _ _ _ _ _ _ _ 

I would like a feature to change the amount of underscores in the header for all messages (not just f show). This way it doesn't wrap to a new line. Also I know some PvPers use a thinner chat bar so it doesn't get in the way of your hearts while you pvp so I could see this as a very useful feature for many. Thanks.

**Comment by SaiCoFlu** [comment]
This is in the config I'm pretty sure.

**Comment by nsporillo** [comment]
Don't use the {header} variable if you do not like the default functionality of the "titleized" header. 

It is found in the config.yml.

**Comment by MindServers** [comment]
But for like /f map for example I can't change the header for that. And where is it in the config?

**Comment by nsporillo** [comment]
![c](http://puu.sh/hHEBu/2e71f29e53.png)

and right, you can't change the header for other commands just yet.. havent found a good way to make that configurable. It's not configurable in any other factions version, but probably should be
