### ISSUE TITLE
Issue - Combat Log

### ISSUE THREAD

**Issue by Odie680** [drtshock/HCFProblems#202]
I use the plugin CombatTagPlus (http://www.spigotmc.org/resources/combattagplus.4775/), and when I combat log, it spams console with errors related to /f stuck.

http://pastebin.com/XjbGDZgN

The error happens when I punch the NPC. Also, another issue is that when you combat log and die, you don't lose DTR, which is a major problem, because people would just combat log, when they know they will die, so they don't become raidable.

Thank you :)

**Comment by nsporillo** [comment]
Do factions lose `power` when someone combat logs, in factions uuid?

**Comment by MoeXIV** [comment]
CTP already works for HCFactions as a development build. Don't make pointless tickets.

**Comment by Odie680** [comment]
@MoeXIV And why are you assuming that I'm not?

**Comment by Odie680** [comment]
@nsporillonsporillo
Unfortunately, I do not own FactionsUUID. I'll go ahead buy it, and try it out when I'm home.

**Comment by MoeXIV** [comment]
No need to buy it. I've tried it already and it does in fact make you lose power.
Go to Minelinks CI and doekad the development builds. Most I've you're errors will be fixed.

**Comment by Odie680** [comment]
@MoeXIV I was not talking about CTP. I ALREADY have the latest dev version...
