### ISSUE TITLE
/f who / show problem.

### ISSUE THREAD

**Issue by oSaphyre** [drtshock/HCFProblems#203]
When the users do f who or f show, this message is displayed: http://prntscr.com/74478p

After the message, if i do pex user <player> group set user, they can do f show, i dont know  why it is happens to me.

**Comment by drtshock** [comment]
What permissions does the user have when this happens? Sounds like you didn't give them any permissions.

**Comment by oSaphyre** [comment]
this plugint doesnt need any permissions, right?

groups:
  User:
    default: true
    permissions:
    - ob.receive
    - ob.broadcast
    - essentials.kits.fishing
    - essentials.msg
    - essentials.signs.use.kit
    build: true
    prefix: '&a'
  Admin:
    prefix: '&c&o'
    permissions:
    - '*'
  owner:
    prefix: '&d&o'
    permissions:
    - '*'
  mod:
    prefix: '&3[Mod] &9'
    permissions:
    - ob.receive
    - ob.broadcast
    - essentials.invsee
    - essentials.fly
    - essentials.god
    - essentials.list
    - essentials.msg
    - essentials.ban
    - essentials.ban.offline
    - essentials.ban.notify
    - essentials.banip
    - essentials.ban.notify
    - essentials.invsee
    - essentials.kick
    - essentials.kick.notify
    - essentials.mute
    - essentials.mute.notify
    - essentials.tempban
    - essentials.tempban.offline
    - essentials.ban.notify
    - essentials.tempban.offline
    - essentials.vanish
    - essentials.tp
    - essentials.spawn
    - essentials.back
  mod+:
    prefix: '&3[Mod&9+&3] &9'
    permissions:
    - ob.receive
    - ob.broadcast
    - essentials.invsee
    - essentials.fly
    - essentials.god
    - essentials.list
    - essentials.msg
    - essentials.ban
    - essentials.ban.offline
    - essentials.ban.notify
    - essentials.banip
    - essentials.ban.notify
    - essentials.invsee
    - essentials.kick
    - essentials.kick.notify
    - essentials.mute
    - essentials.mute.notify
    - essentials.tempban
    - essentials.tempban.offline
    - essentials.ban.notify
    - essentials.tempban.offline
    - essentials.vanish
    - essentials.tp
    - essentials.spawn
    - essentials.back
    - essentials.unban
    - essentials.ban.notify
    - essentials.unbanip
    - essentials.ban.notify
  seniormod:
    prefix: '&8[&cSeniorMod&8] &6'
    permissions:
    - ob.receive
    - ob.broadcast
    - essentials.invsee
    - essentials.fly
    - essentials.god
    - essentials.list
    - essentials.msg
    - essentials.ban
    - essentials.ban.offline
    - essentials.ban.notify
    - essentials.banip
    - essentials.ban.notify
    - essentials.invsee
    - essentials.kick
    - essentials.kick.notify
    - essentials.mute
    - essentials.mute.notify
    - essentials.tempban
    - essentials.tempban.offline
    - essentials.ban.notify
    - essentials.tempban.offline
    - essentials.vanish
    - essentials.tp
    - essentials.spawn
    - essentials.back
    - essentials.unban
    - essentials.ban.notify
    - essentials.unbanip
    - essentials.ban.notify
  seniormod+:
    prefix: '&8[&cSeniorMod&6+&8] &6'
    permissions:
    - ob.receive
    - ob.broadcast
    - essentials.invsee
    - essentials.fly
    - essentials.god
    - essentials.list
    - essentials.msg
    - essentials.ban
    - essentials.ban.offline
    - essentials.ban.notify
    - essentials.banip
    - essentials.ban.notify
    - essentials.invsee
    - essentials.kick
    - essentials.kick.notify
    - essentials.mute
    - essentials.mute.notify
    - essentials.tempban
    - essentials.tempban.offline
    - essentials.ban.notify
    - essentials.tempban.offline
    - essentials.vanish
    - essentials.tp
    - essentials.spawn
    - essentials.back
    - essentials.unban
    - essentials.ban.notify
    - essentials.unbanip
    - essentials.ban.notify
  Vip:
    prefix: "&a\xe2\u0153\xbc&lVip>&5"
    permissions:
    - ob.receive
    - ob.broadcast
    - essentials.signs.use.kit
    - essentials.msg
    - coloredanvils.color.*
    - EasyKits.kits.cooldown
    - EasyKits.cmd.list
    - EasyKits.kits.comida
    - EasyKits.kits.vip
  Famous:
    prefix: '&6[&e&l&oFamous&6] '
    permissions:
    - ob.receive
    - ob.broadcast
    - essentials.signs.use.kit
    - essentials.msg
    - coloredanvils.color.*
    - EasyKits.kits.cooldown
    - EasyKits.cmd.list
    - EasyKits.kits.comida
    - EasyKits.kits.vip

**Comment by Lilmac12312** [comment]
@oSaphyre Please paste your permissions into a gist via gist.github.com

**Comment by oSaphyre** [comment]
https://gist.github.com/oSaphyre/950472559044cb350836
