### ISSUE TITLE
Variable Issue

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#205]
Simple variable issue with the {x} {y} and {z}.

This is what I have in the configuration: http://pastebin.com/tLwjyx1F
This is the output, using /f show: http://prntscr.com/746lei

No console errors.

**Comment by nsporillo** [comment]
Just means no home is set, and {ig} is an internal variable that should be replaced by the no home TL but for whatever reason is not. I suggest finding a different /f show format.

**Comment by MoeXIV** [comment]
It's the f show format? Why won't that specific one work? That makes no sense

**Comment by nsporillo** [comment]
because of how the {ig} variable is replaced internally. There is 3 separate variables for the x,y, and z that need to be replaced by a single TL.
