### ISSUE TITLE
Support \n in configurable messages

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#208]
Hey, well I am customising my leaving/entering land, and I have an issue. Obviously each player has a different chat layout. So when I customise my leaving/entering message, its not exactly perfect & the way me or the players would like it.
 For example, here is one players message: http://prntscr.com/74ftjq
& here is completely different players message: http://prntscr.com/74fu94

I'm requesting a new variable like %newline% to be implemented, or just a simple feature in the lang.yml, where it is "faction-leave:", you could also add one for "faction-enter:"

This would make it look a bit better.

**Comment by nsporillo** [comment]
I guess separate TL for leaving and entering isn't a bad idea.. except it prevents people from having it them both on one line which is the default functionality. We don't change default functionality unless it has an explicit issue. 

The only thing I can see changing is supporting \n in all messages...

**Comment by SaiCoFlu** [comment]
I'm guessing "/n" is new line? Personally I think that'd be a good idea then, just support /n in all messages, instead of add the "faction-enter" as I do understand it would mean not everyone may want this.

**Comment by Lotteries** [comment]
Yes \n is a new line. This can be used in most bukkit things. Such as you're MOTD.

**Comment by KriticalPvP** [comment]
Yeah, How do we add Colons in the message? I just use spaces for the newline : p

**Comment by SaiCoFlu** [comment]
Any updates on when this feature would be added?

**Comment by SaiCoFlu** [comment]
@nsporillo Any idea when this could possibly be added buddy?

**Comment by nsporillo** [comment]
@SaiCoFlu will look into it sometime today.

**Comment by nsporillo** [comment]
The update will recognize the sequence `/n/` as a newline marker. 

    faction-leave: <b>Leaving %1$s/n/<b>Entering %2$s
