### ISSUE TITLE
Updated to latest build, now recieving error when /f who.

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#209]
This was working before on Build 47, but since I updated to the latest build 48, I'm getting an error when I do /f who.

Here is the message: http://prntscr.com/74g30d
And here is my layout: http://prntscr.com/74g41a

**Comment by nsporillo** [comment]
... what is the error

The fact that there was an internal error helps nil, we need the error output from console to determine what went wrong and thus how to fix.

**Comment by SaiCoFlu** [comment]
Okay, I'll get it now. Forgot about that.

**Comment by SaiCoFlu** [comment]
https://gist.github.com/SaiCoFlu/bd21c00c22c2266ff0bd Here you go. @nsporillo

**Comment by nsporillo** [comment]
is an issue with tooltips, the offline player is null, so probably an issue with how we're handling offline players..

**Comment by Lotteries** [comment]
I've seen multiple people report this including Aaron. 

@nsporillo

**Comment by nsporillo** [comment]
@Lotteries none posted the actual error until now, so couldn't do anything about it.

**Comment by nsporillo** [comment]
I can't reproduce this error. 

What permissions system do you use?
Does the player in that faction have a group?

What happens if you `remove the 2nd line` from the `tooltips.show`

    show:
        - "&6Last Seen: &f{last-seen}"
        - "&6Balance: &a${player-balance}"

Please get back to me so we can see what is wrong.

**Comment by KriticalPvP** [comment]
Do Not use plugman or /reload.

**Comment by SaiCoFlu** [comment]
@nsporillo I currently use GroupManager, and I'm pretty sure some of them have donator ranks, but this problem has never happened until now.

@KriticalPvP I done neither of them.
