### ISSUE TITLE
newest update broke other variables

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#21]
![bjdnpsf](https://cloud.githubusercontent.com/assets/9636316/6703466/6535c4e4-ccf9-11e4-999f-323892580085.png)

Not sure which other variables are broken, haven't tested them all.

**Comment by nsporillo** [comment]
This is how the sidebar is handled, without knowledge of java-it should still be readable. 

      
        s = s.replace("{name}", fplayer.getName()).replace("{balance}", String.valueOf(Econ.getFriendlyBalance(fplayer.getPlayer().getUniqueId())));
        s = s.replace("{faction}", !faction.isNone() ? faction.getTag() : TL.GENERIC_FACTIONLESS.toString());
        s = s.replace("{dtr}", dc.format(faction.getDTR())).replace("{maxdtr}", dc.format(faction.getMaxDTR()));
        s = s.replace("{online}", String.valueOf(faction.getOnlinePlayers().size())).replace("{members}", String.valueOf(faction.getFPlayers().size()));
        s = s.replace("{leader}", String.valueOf(leader)).replace("{land}", String.valueOf(faction.getLand())).replace("{maxland}", String.valueOf(faction.getMaxLand()));
        s = s.replace("{raidable}", raidable ? TL.RAIDABLE_TRUE.toString() : TL.RAIDABLE_FALSE.toString());
        s = s.replace("{warps}", String.valueOf(faction.getWarps().size()));

There is no {totalOnline}, but I'm assuming you're looking for the total number of players online?

Can add that. If you're looking for any other basic variables, let me know

**Comment by Doxify** [comment]
If you look at #20 you will see that there was a {totalOnline}.
