### ISSUE TITLE
New doors and fences 1.8

### ISSUE THREAD

**Issue by youngpvprock** [drtshock/HCFProblems#213]
The new doors and fences can be open by enemy or neutral facs, i know plugin it¡s mostly for 1.7 servers, but i'm using 1.8 and need that fix.
Maybe also 1.8 is what make a bug in #201

**Comment by drtshock** [comment]
Can you verify that you purchased the resource? Either give me your mcexchange or ci username.

**Comment by drtshock** [comment]
Nvm, verified that you purchased.

In your conf,json, there is a section for denying materials in territories. https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/Conf.java#L224-L227

You can put materials in there. You'll find a list of all possible materials here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
