### ISSUE TITLE
Task #114 Error 

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#214]
No Idea why this occured, was AFK for about 45 mins, and this popped up in my console on my local pc.
https://gist.github.com/SaiCoFlu/a6b8cf53a06128f8a0e9

**Comment by drtshock** [comment]
Did you delete your file or did it become inaccessible?

**Comment by SaiCoFlu** [comment]
Nope I added it to a new test server I created which had no factions data on it.

**Comment by drtshock** [comment]
Can you give us your exact steps to *reproduce* (do it again) this?

**Comment by SaiCoFlu** [comment]
I have no idea what I did. All I did was drop the file into my plugin folder, start the server up then I was AFK for about 45 minutes, I came back & looked at console and saw that message.

**Comment by drtshock** [comment]
The error shows that gson is null, which should never be possible and I have never seen in 3 years. If you can reproduce this, feel free to reopen it :)
