### ISSUE TITLE
New "Member Death:" Feature

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#217]
Instead of commenting on something that was closed, I'm creating basically what that guy had as a question, as I'd also like to see this be implemented.
"Member Death: name dtr/max-dtr" Is similar to the Member Online/Offline message we receive if enabled, but this displays when a faction member dies, and also tells the faction their new DTR out of the Max DTR. I was going to request this, but someone beat me to it. And maybe display if it goes below 0.00 it will also display a message "&cYour faction is now RAIDABLE!"

Here is an example of what I mean, credits to oSaphyre for the screenshot:
http://prntscr.com/755ayp

**Comment by Lotteries** [comment]
:+1: I would love to see this added. It is a very useful feature that every HCF server has.

It should be like

&6Member Death: {relationcolor}{faction-role-tag}{username} &6(&e{dtr}&6/&e{max-dtr}&6)

P.S: Update the DTR before pushing out that message.

**Comment by nsporillo** [comment]
The code is there, just commented out because it wasn't quite working correctly. 
All the messages are configurable in lang.yml, under PLAYER_DTR_....

        // TODO: Get this working again
        // Send the message from the dtr event
        //final String msg = dtrEvent.getMessage();
        //if (msg != null && !msg.isEmpty()) {
        //    fplayer.msg(msg, faction.getDTR(), faction.getMaxDTR());
        //}

**Comment by Lotteries** [comment]
What is exactly wrong with that code? I could make-shift a plugin using the API to get this feature added on my own. Haha.

**Comment by nsporillo** [comment]
Added, when updating to new build check lang.yml for FACTION-DEATH value, near the bottom of the file. It's default to how you specified in this issue.

**Comment by KriticalPvP** [comment]
Whens the new version? Is it out?
