### ISSUE TITLE
Suggestion: Territory Notifications

### ISSUE THREAD

**Issue by Russiaa** [drtshock/HCFProblems#22]
When you leave/enter a territory it would display a message similar to this:

http://prntscr.com/6ijcgz

It would also do this for faction land:
"Leaving (Faction Territory Left), Entering (Faction Territory Entered)"

Not an important suggestion, but something nice to see :)

**Comment by Doxify** [comment]
I'd also like this.

**Comment by MoeXIV** [comment]
As do I. ^.^
Please consider asking, as I previously made a post about this.

**Comment by drtshock** [comment]
One of the few messages we have that isn't configurable ;c

**Comment by MoeXIV** [comment]
One of the, like, 400? xD
Figures it's un configurable.

Maybe make a toggle feature? It's a lot more clean in my opinion.
P.S, the entering and leaving would only show the name of the faction with the relationship thing. No description <33

**Comment by drtshock** [comment]
600ish*.

Well I wanted to add titles but Spigot has yet to add API for it yet ._. We have a scoreboard that can pop up for a few seconds. We'll make it a configurable chat message as well.

**Comment by MoeXIV** [comment]
When do you think this will be done? And are you talking about the leave and entering messages for faction land? I'm somewhat confused ;c

**Comment by RydanMC** [comment]
This feature would be loved, most HCF servers/plugins have something similar to this.

**Comment by nsporillo** [comment]
Added. Check out the latest download on the build server.

Make sure your lang file is fresh.

By default, we now have
![territory notifications](https://cloud.githubusercontent.com/assets/1480197/6790145/1a4ec2e6-d17c-11e4-82b6-0d374836abd4.png)

Thank you @Russiaa for the suggestion.
@Doxify @MoeXIV @RydanMC hope you like this as well :+1:

**Comment by MoeXIV** [comment]
Thank you!
