### ISSUE TITLE
Plugin Combat log

### ISSUE THREAD

**Issue by EnzoCARP** [drtshock/HCFProblems#220]
I do not speak Inglés so here I leave you in Spanish.
Hay algún plugin que sirva para el hcf de combat log o tag? 
por lo menos ayúdenme en eso -.-
nose que les causa risa? traten de hablar en argentino... los quiero ver y todas las preguntas que hice las tuve que resolver solo thx(?

**Comment by SaiCoFlu** [comment]
Esto es sólo una facción plugin, esto no tiene ninguna relación con etiqueta para luchar contra de registro o combatir.

**Comment by SaiCoFlu** [comment]
You guys can probably close this, hes basically asking for a combat log/tag plugin

**Comment by drtshock** [comment]
We only provide support in english unfortunately. Blame America's shitty education system.
