### ISSUE TITLE
Internal Error when doing /f who

### ISSUE THREAD

**Issue by Shicking** [drtshock/HCFProblems#226]
Pastebin of the problem here:
http://pastebin.com/tifnuTv8
In chat it lists most of the info but then it says "An internal error occured while attempting to perform this command" where the online and offline players should be. Players are complaining they cannot see the members in the faction.

I purchased the plugin via mcexchange.org

**Comment by nsporillo** [comment]
What version are you running? /f version

Try removing all the tooltips from tooltips.show and see if you still get any errors. It's probably something to do with a null player group or balance, or something along those lines.

**Comment by Shicking** [comment]
Version - 0.0.7-b44

How do I disable the tooltips?

**Comment by nsporillo** [comment]
You can disable them by removing each line from the list. 

![a](http://puu.sh/hRsNZ/33536d5bbb.png)
