### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by HeyImYellow** [drtshock/HCFProblems#227]
Hey, there are 2 commands which I would like to be added into as a type of Alias as such.

With /f money you need to /f money deposit and /f money withdraw.

It would be great if you could add:

/f deposit
/f withdraw

**Comment by SaiCoFlu** [comment]
F stuck is configurable.

**Comment by drtshock** [comment]
Removed the second part of your ticket. Keep one thing per ticket please so feel free to open another one with the separate issue :)

**Comment by Lotteries** [comment]
I would like to see this as well, /f money is a very unknown command, most HCF servers use these alias's now. It would be much more similar for players.
