### ISSUE TITLE
Customizable /f who for Permanent Factions.

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#228]
Ok, so with Permanents factions, say if it's an Admin claim and has no players in it etc, it has a lot of even that doesn't even need to be shown, like DTR, Faction Home co-ordinates. Would you be able to implement a configurable permanent faction layout like the normal one? This would really tidy up the /f who for example an event such as KOTH.

**Comment by SaiCoFlu** [comment]
It has a lot of stuff that doesn't even need to be shown*.

**Comment by Lilmac12312** [comment]
So in other words something like this? http://prntscr.com/77ll8v

**Comment by SaiCoFlu** [comment]
Yeah @lilmac12312.

**Comment by Lilmac12312** [comment]
Then in that case I wouldn't mind something like this.

**Comment by KriticalPvP** [comment]
+ 1 @SaiCoFlu , @Lilmac12312

**Comment by Lotteries** [comment]
:+1: Useful for Koths!

**Comment by lyzha** [comment]
+1

**Comment by nsporillo** [comment]
Will likely be a new section somewhere in config.yml for this. When it is implemented, I will be using 
![dd](http://i.imgur.com/wq42j4C.png) 
as the specification. If anyone has any tweaks or suggestions let me know.

**Comment by KriticalPvP** [comment]
+1 Thanks @nsporillo and welcome back! :)

**Comment by Lilmac12312** [comment]
Where can we configure this? Using the latest version and I'm unable to find it.

**Comment by SaiCoFlu** [comment]
I don't think it's been implemented yet.

**Comment by Lilmac12312** [comment]
@SaiCoFlu I'm sure it was said within the latest update change log?

**Comment by lyzha** [comment]
:+1:

**Comment by SaiCoFlu** [comment]
Any update when this and #208 could be added @nsporillo ?

**Comment by SaiCoFlu** [comment]
@nsporillo Sorry for the second tag, as you never responded the first time. you got any estimation on when this could be implemented? I'm eager for this to be added 😁.

**Comment by SaiCoFlu** [comment]
Was this ever added?

**Comment by nsporillo** [comment]
@SaiCoFlu .. yes
![yes](http://puu.sh/iy9RV/690200b79f.png)

Use latest dev build and make sure your config has the new list. It does not auto generate, thus if you don't update anything then ./f show will probably be blank for a permanent faction with no players.

Please stay informed when your issues are resolved. Check dev builds.

**Comment by SaiCoFlu** [comment]
I was keeping up to date, but nothing was mentioned in the build changes/features about f show for this. But thank you :)

**Comment by nsporillo** [comment]
![what](http://puu.sh/iyac2/6147b7b948.png)

![the](http://puu.sh/iyacz/572c48d517.png) <----------- click here

![heck](http://puu.sh/iyadY/b657cb856f.png)

All this information is available to you as a logged user IIRC. There is no better changelog then the build server itself. I do not write any other forms of changelogs, I just document my commits. Please read them if you're interested or curious.

**Comment by SaiCoFlu** [comment]
Thanks, I must've not noticed. :P
