### ISSUE TITLE
F Stuck is a little strange...

### ISSUE THREAD

**Issue by HeyImYellow** [drtshock/HCFProblems#229]
So basically f stuck works sort of fine except if you move more than the defined amount of blocks, it doesn't cancel it immediately it just waits until the teleport is ready then tells you it failed.

Could you please make it so there is an option to make it cancel instantly?
Thanks :)

MCExchange Username: HeyImYellow

**Comment by nsporillo** [comment]
I would say the only real impact it makes is it just wastes the players time a little bit, by not canceling right away and then they can just re-do the command and sit still.

The purpose is still served however, the idea was to not have the command just let people execute it and then run away from say PVP until the timer ends and then they escape. I chose to go this route as it keeps code off player move event.. in the name of efficiency. But really it's not a big check, would not impact performance.

**Comment by TemptingMC** [comment]
Yea, it was broken for me so I had my developers code a different one and override the sub command for /f stuck too. I'd get your developer to do that to be honest.
