### ISSUE TITLE
Is there a way to remove enemies off of fshow

### ISSUE THREAD

**Issue by nscwalk** [drtshock/HCFProblems#23]
If there is a way to remove enemies off of f show That would be great because I have my default relationships set to enemy and whenever anyone does /f show it spams there chat

**Comment by MoeXIV** [comment]
It's all configurable if you haven't looked through the configuration before..

There's "f show" edits you can make really easily. Look around before you post ^.^

**Comment by nscwalk** [comment]
Is that in the lang file????

**Comment by Doxify** [comment]
Reset your config.yml, that's what I had to do.
