### ISSUE TITLE
Stop the broadcast of faction name changes?

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#231]
How would I do this? I can stop description changes but not tag changes it seems.

**Comment by KriticalPvP** [comment]
+1 Spam @ SOTW

**Comment by nsporillo** [comment]
Isn't a way currently, but will probably lump this in with https://github.com/drtshock/HCFProblems/issues/236

Only problem is, /f desc sends two messages 1 TL and then the new faction description, so would probably just add some fancy {description} tag TL value which can just be replaced with {null} (along with the 1st TL) to avoid the broadcast to everyone. (but add in a check to still send to faction members)

**Comment by nsporillo** [comment]
Actually, there is a way to do this, I missed it!

`Conf.broadcastDescriptionChanges`

Look in conf.json

**Comment by Doxify** [comment]
Nick isn't that for description changes?

I'm looking for tag changes.

**Comment by nsporillo** [comment]
@Doxify Oh right, lol. Sorry about that. Then yes there is no current way to stop the broadcast of these messages. Will add a new value to conf.json for this.

**Comment by Doxify** [comment]
Alright thanks, players use it to spam chat when I have it muted.

**Comment by SaiCoFlu** [comment]
Maybe send it to their faction members only?
