### ISSUE TITLE
Fix DTR evading

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#233]
Players can unclaim all while frozen then make a new faction and overclaim or overclaim their land with an alt.

Can you please make it so players cannot unclaim land while frozen?

**Comment by SaiCoFlu** [comment]
+1 I also ran into the same issue

**Comment by Lotteries** [comment]
:+1: Make this configurable, would be great if added!

**Comment by KriticalPvP** [comment]
They can also /f admin themselves to disband the faction!

**Comment by Lotteries** [comment]
@KriticalPvP I see you one every issue i post! Haha! I also just saw you're comment asking what HCF server i run, i own PrismaHCF. The first and only (as far as i know) Swedish HCF server.

**Comment by KriticalPvP** [comment]
@Lotteries XD Congrats! : D

**Comment by nsporillo** [comment]
@KriticalPvP don't try to merge two issues into one via comment, make a new issue so it can be addressed separately, thank you.

**Comment by nsporillo** [comment]
@KriticalPvP I fail to see where /f admin plays any role in bypassing the configurable freeze-disband setting.

**Comment by KriticalPvP** [comment]
If You are in a faction with negative DTR you /f admin (yourname) it disbands the faction
