### ISSUE TITLE
Loss of access

### ISSUE THREAD

**Issue by Insanity14** [drtshock/HCFProblems#234]
I lost access to the plugin after purchase how might I regain access to the plugin so that I may future updates.
Username for MCExchange: Insanity14

**Comment by drtshock** [comment]
MCExchange doesn't have a way to remove access so there's now way you could've lost it. Can you paste your transaction id?

**Comment by nsporillo** [comment]
Closing this since @Insanity14 hasn't replied in almost two weeks..

**Comment by Insanity14** [comment]
Sorry forgot my login info. Whats the email it was sent to on paypal so that I can search for it in the payments?

**Comment by drtshock** [comment]
billing@puzlinc.com or trenthensler@live.com

**Comment by Insanity14** [comment]
Here is the Trans ID: Unique Transaction ID #57394914BX366712G
