### ISSUE TITLE
Faction Scoreboard Not Working

### ISSUE THREAD

**Issue by MindServers** [drtshock/HCFProblems#235]
The tab list color, scoreboard when entering faction land, and the custom player head are all not working. They do work, however, when I do /plugman restart factions, however if I relog after that point then they will be broken when I log back in. I know @Lotteries has had a similiar issue here: https://github.com/drtshock/HCFProblems/issues/43.

What's the solution?

**Comment by SaiCoFlu** [comment]
Don't use plugman.

**Comment by MindServers** [comment]
I tried it before installing plugman and still didn't work.

**Comment by Lotteries** [comment]
Factions relies on scoreboards, my issue was with NexGenKoths. I went into the config and disabled everything to do with scoreboards and factions worked again. So if you have any other scoreboard plugins remove them and it should work.

**Comment by MindServers** [comment]
I have NexGenKoths ^. I will go ahead and tweak it as you did and hopefully it will work again. Thanks man!

**Comment by MindServers** [comment]
@Lotteries Your solution worked. You're a god among men my friend. Closing this now.
