### ISSUE TITLE
Remove certains messages

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#236]
Would be nice if we could but DISABLE or NONE for some messages in the lang.yml if you dont want a message to show just put the tag and its fine

**Comment by nsporillo** [comment]
Maybe something like {null} to indicate a message that is never sent. I could see how this could be useful.

**Comment by nsporillo** [comment]
@lyzha I can add this very easily, but there is several TL that are components of other TL, so I'm thinking just not sending any message which contains {null} as opposed to equals {null}.

**Comment by lyzha** [comment]
I understand but that would be super cool to be able to disable messages since some messages are not obligatory

**Comment by lyzha** [comment]
So, you're planning on adding this feature? :100:

**Comment by nsporillo** [comment]
Yeah, will get to it in the next few days, have been very busy with a lot of things lately.

**Comment by lyzha** [comment]
:+1:  Thanks
