### ISSUE TITLE
Request: Built in Anti wither

### ISSUE THREAD

**Issue by Lotteries** [drtshock/HCFProblems#238]
All HCF servers do not allow Wither raiding, currently we have to have a standalone plugin to deny this, but i thought it would be simpler if there was one built in as it is part of HCF. Withers should not break faction claimed land but should break other things. 

P.S: Yes i know /gamerule doMobGriefing false, but that resets its self on most reloads (not all)!

**Comment by KriticalPvP** [comment]
Fixed? How?
