### ISSUE TITLE
New Feature?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#239]
I was hoping you could disable join / leave msg's and only display Factions leave & join msg's..
so it doesn't announce to everyone if someone logs on, only those in your fac.

Make it configurable please.

Thanks! =D

**Comment by HeyImYellow** [comment]
It is configurable if you use essentials I believe.

It's some like:
essentials.silentjoin
essentials.silentquit or silentleave

**Comment by nsporillo** [comment]
Are you referring to the default minecraft leave / joins, or another plugins messages?

**Comment by KriticalPvP** [comment]
Yeah, default leave & join

**Comment by SaiCoFlu** [comment]
It does display members online/offline, you just need to set it to true

**Comment by KriticalPvP** [comment]
I know that
Im talking about

Player Joined the game
I only want HCF leave / join

**Comment by MoeXIV** [comment]
Get hide stream or get it in your core like most people.
