### ISSUE TITLE
Exceeding ally limit glitch

### ISSUE THREAD

**Issue by nscwalk** [drtshock/HCFProblems#24]
So there is a glitch where if you have the maximum set to 2 ally's and you send 3 ally requests and they already don't have 2 ally's all 3 can accept your request giving you 3 allies. A fix would be a message that would say. This faction (name) has already reached it's ally limit. Because what the plugin is doing now is just not letting you do /ally (name) when you have 2 ally's. But when you have 1 ally and send 2 ally requests and they both accept then you get 3 allies.

**Comment by nsporillo** [comment]
Just went through and tested and found no issue. 

Please make sure you have max relations enabled, and then set to 2.

**Comment by TMNetwork** [comment]
Please fix this soon @nsporillo

**Comment by nsporillo** [comment]
@TMNetwork it was fixed, try out the latest build of HCF.

Also, you might want to go into your lang file and change the TL for 

    RELATIONS:
      ...
      EXCEEDS:
        MAX: <i>Failed to set relation wish. You can only have %1$s %2$s.

The `%1$s` will probably be `%1$d in your lang file, which will say like 2 %s when it formats.
