### ISSUE TITLE
FeatherBoard Support? Halp! Important

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#240]
Is there a way I can use a scoreboard plugin? I'd like to be able to use HCF nametag colors & scoreboards for enderpearl cooldowns and KoTH Timers?

@drtshock You would know best if this is possible and @nsporillo is still on holiday, any replies appreicated! ^.^

**Comment by drtshock** [comment]
Currently no.

**Comment by KriticalPvP** [comment]
Awh, okay, I'll close this for now

**Comment by Doxify** [comment]
Can I pay the 40/hour rate to make this happen?

**Comment by KriticalPvP** [comment]
=D @Doxify I see you want this too! =D

**Comment by nsporillo** [comment]
Integrating this with the main HCF repository would be a no go. However, even a side repository managed by myself to add this is still not really feasible.

Featherboard is a premium plugin, and it is obfuscated. It's just not something I wanna work on lol.
