### ISSUE TITLE
/f c f problem. 

### ISSUE THREAD

**Issue by PatManGames** [drtshock/HCFProblems#244]
I dont know if I have this wrong, but when someone types in /f c a, or /f c f chat, their chat is not only put in ally/faction chat, but global chat as well. Is there a configuration for this, am I missing something?

**Comment by drtshock** [comment]
Which version of the plugin are you on?

**Comment by PatManGames** [comment]
Version 0.0.7 that I downloaded on MCExchange.

**Comment by PatManGames** [comment]
v0.0.7-b44

**Comment by PatManGames** [comment]
Is there a way to fix this?

**Comment by drtshock** [comment]
Can you paste your full server log in a gist.

**Comment by PatManGames** [comment]
OK wait. I figured out the problem. With Essentials, when you talk in chat with /f c a, or /f c f, it says 
**FactionName PatManGames: Hi
[Owner] PatManGames: Hi
My problem is with essentials, it not only chats in /f c a, or /f c f, but it also talks in global chat. Is there any way to fix this, can I use essentials or do I have to delete it and find something else?

**Comment by SaiCoFlu** [comment]
I use Essentials and it works perfectly fine.

**Comment by nsporillo** [comment]
This is an essentials issue it looks like, not HCF.
