### ISSUE TITLE
/f create and /f leave crash.

### ISSUE THREAD

**Issue by PatManGames** [drtshock/HCFProblems#245]
With the version of HCFactions that I'm running, every time a user types /f create, /f leave, or /f disband their minecraft crashes. Is there a fix for this?

**Comment by nsporillo** [comment]
Can you confirm the username you used on MCExchange, or your Jenkins username?

**Comment by HeyImYellow** [comment]
Nsporillo where can I find the latest update to HCFactions?

**Comment by nsporillo** [comment]
Also, what version of hcf are you using? do /f version and post the version string as a reply.

**Comment by PatManGames** [comment]
PatManTheGreat is my MCExchange thing, Im already logged in and my I have the newest version that I downloaded on MCExchange.

**Comment by nsporillo** [comment]
Okay. So is there any way you can confirm this with your client?

If so, could you provide any sort of log from the client..?

There isnt anything we're doing on our end that could do this, and I've never had anyone report this issue before...

**Comment by nsporillo** [comment]
Closing this because @PatManGames failed to reply in 3 weeks.. :unamused:
