### ISSUE TITLE
Pressure plates in other's land

### ISSUE THREAD

**Issue by HeyImYellow** [drtshock/HCFProblems#246]
So yes, the title says it all.

You can stand on Pressure Plates when they are claimed by another faction which greatly impacts the effect of traps which we would like to change.

Or is there an option to do it, if so how?

**Comment by nsporillo** [comment]
There already exists an option to prevent this, and it is located in the conf.json. Please spend some time to go through the plugins files so in the future you'll know where to look right off the bat :p

**Comment by HeyImYellow** [comment]
Oh really :o

Sorry i'll look better next time :)

**Comment by Doxify** [comment]
The correct name is "STONE_PLATE".

**Comment by HeyImYellow** [comment]
Are you sure?

It keeps being replaced to

"null",

**Comment by drtshock** [comment]
Use the material javadocs http://vq.lc/jd/org/bukkit/Material.html
