### ISSUE TITLE
Scoreboard related lag on PlayerJoinEvent

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#247]
http://aikar.co/timings.php?url=11457188

**Comment by MoeXIV** [comment]
It seems as if everything that listens to players movements is high :/

**Comment by Doxify** [comment]
Fixed this by disabling everything that has to do with scoreboards.

@drtshock please look into this

**Comment by drtshock** [comment]
90.26%	7,244.98%	 36.22 s	 3,622.49 ms	 0.9	       0.0k	    Connection Handler

What's up with your connection handler?
