### ISSUE TITLE
DTR Freeze Adition

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/HCFProblems#25]
Add-on. Make it so players cannot join factions that are on DTR freeze. (Configurable)

**Comment by nsporillo** [comment]
You want this to be configurable? Seems like something that should always be enabled... it's like adding a config toggle for DTR...

At any rate, it is already implemented. I'm going to set this as closed, but if you have a case for it being configurable, comment again. We want to add feature, yes - but config clutter is no good.
