### ISSUE TITLE
Minimal F Show 

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#250]
I didn't know how to word the title so I just left it at that.

Is there something you can put on the line to make it show if minimal f show is on? I like minimal f show, but there's one line / certain lines that I prefer to be shown all the time.

**Comment by nsporillo** [comment]
You mean like a {variable} tag to toggle minimal-show on a specific line?

**Comment by MoeXIV** [comment]
Exactly,  @nsporillo

**Comment by MoeXIV** [comment]
Is this going to be added. I justified. ;(

**Comment by lyzha** [comment]
I think it got added check the logs on the jenkins
