### ISSUE TITLE
Translate lang.yml and other

### ISSUE THREAD

**Issue by BeStrenght** [drtshock/HCFProblems#251]
Hi how to make this : http://prntscr.com/7c52n1 
Ver :  #53 
And they have a fr-FR language file ?

**Comment by Lilmac12312** [comment]
This is all configurable within the config file, use your eyes.

**Comment by nsporillo** [comment]
You can change the scoreboard format in lang.yml.

You can change the /f show output in config.yml.

**Comment by BeStrenght** [comment]
Where ...

**Comment by BeStrenght** [comment]
And i don't want [FACTION] name just want Name in relation color

**Comment by BeStrenght** [comment]
Username of jenkins : Kwizzy

**Comment by nsporillo** [comment]
![duh](http://puu.sh/i9wYK/b76843a1f5.png)

**Comment by BeStrenght** [comment]
Thank's :)
