### ISSUE TITLE
The time till regen doesnt work for me?

### ISSUE THREAD

**Issue by ItsPotions** [drtshock/HCFProblems#252]
Im using {timeleft} from the build 0.0.6 but in 0.0.7 it does not work for me is there a new {thing} for it

**Comment by SaiCoFlu** [comment]
All {} things are within the config.yml at the bottom with a description of what it is.

**Comment by ItsPotions** [comment]
@SaiCoFlu I understand that but in the old update you could show the time till regen why is that no longer in the new build

**Comment by nsporillo** [comment]
It was changed to {time-left}. 

This happened with Build 39, which was released 4/7/2015.
