### ISSUE TITLE
Can you add me to the CI on Jenkins?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#253]
I haven't been added yet? I would like to get some dev builds, thanks!

**Comment by nsporillo** [comment]
KriticalPvP <- exactly like that?

**Comment by KriticalPvP** [comment]
Yes sir,

**Comment by nsporillo** [comment]
You should have access now.

![lel](http://puu.sh/idykg/ab28adffd9.png)

**Comment by KriticalPvP** [comment]
Thanks!
