### ISSUE TITLE
The colors of tab disappear

### ISSUE THREAD

**Issue by Starwerty** [drtshock/HCFProblems#255]
The colors of the tab disappear when activated a scoreboard that can i do?

**Comment by nsporillo** [comment]
What version (include the build #) are you using?
What is your username on either MCExchange or the Jenkins?
Can you provide a better text explanation of the problem?
and, can you provide maybe a video of the issue...

Otherwise, have no idea what you even mean...

**Comment by Doxify** [comment]
He's using a different scoreboard plugin, probably featherboard.

You need to be using the scoreboard that is integrated into the factions plugin if you want to see relation colors above heads and in tab.

**Comment by MarckF** [comment]
Yes Doxify, I agree with you, but when we add others plugins like Koth plugin or BattleZ_Border which also have their own Sb, it makes factions tag disappear. Do you know how can we fix that?
