### ISSUE TITLE
Loss of access

### ISSUE THREAD

**Issue by Insanity14** [drtshock/HCFProblems#256]
OK So I lost access and the other post I had made was closed because I didnt respond. I forgot my login info. I've found the trans ID for the thing.
Jenkins ID: Insanity14
MCExhange ID: Insanity14
Trans ID: Unique Transaction ID #57394914BX366712G

**Comment by lol768** [comment]
Previous issue for context: https://github.com/drtshock/HCFProblems/issues/234

**Comment by drtshock** [comment]
Added back to the CI.

**Comment by Insanity14** [comment]
I still dont have access to the plugin on the Jenkins page nor do I have access to it on the MCMarket.
