### ISSUE TITLE
Invisbility issues

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#257]
When a player drunk an invisibility pot we can still see their tags which is an issue for me...
I'm using spigot (http://prntscr.com/7e5s05) and factions (http://prntscr.com/7e5rq9)

**Comment by HeyImYellow** [comment]
I don mean to sound like a dick, but this feature is something 99.99% of us want to keep added as it plays an important role in teamfights when it comes down to working with your faction and allies. I highly doubt they wil remove this feature :P

**Comment by lyzha** [comment]
I dont think thats an intended feature is it? I agree with you that the colored tag is AN AMAZING feature but when it come to invisibility fights its a big issue

**Comment by HeyImYellow** [comment]
I think you could be getting me confused, do you mean you can see ENEMY tags when they are invis?

**Comment by lyzha** [comment]
yes sir! allies enemies neutral ect..

**Comment by HeyImYellow** [comment]
Oh, I see why you made this issue now. That's really weird as I've never had that issue myself, try updating to the newest version of HCFactions if you haven't already.

**Comment by SaiCoFlu** [comment]
Already made an issue about this a while ago, this can't be fixed unless you stop running 1.8 / 1.7.10 loading 1.8 as its a bug within 1.8 and would take to much effort as @nsporillo doesn't like working with TagAPI.

**Comment by drtshock** [comment]
This is part of scoreboards.

**Comment by lyzha** [comment]
I know a server using HCF plugin have fixed that bug and they are using 1.7 and 1.8 they arent good developers so I think everyone could fix that we just have to figure out how they have done that...

**Comment by MoeXIV** [comment]
On 1.8 it's client side. That's not something you can fix without adding dependencies and major effort for something that's meant to be in the new version.
