### ISSUE TITLE
Hey, Help :D

### ISSUE THREAD

**Issue by ItzWid13** [drtshock/HCFProblems#258]
Yo, how do i do to claim SafeZone exactly?

**Comment by drtshock** [comment]
[19:39:18]  <@Korobi>	.claim: To claim a warzone or safezone, do /f claim <radius> <warzone/safezone>

**Comment by ItzWid13** [comment]
EXACTLY?

**Comment by ViperCobra** [comment]
f claim just claims for the faction im in and I cant join safezone...

**Comment by ItzWid13** [comment]
Yeah

**Comment by lyzha** [comment]
I cant claim safezone either using lastest ci build

**Comment by nsporillo** [comment]
Use /f claim 1 safezone

**Comment by lyzha** [comment]
Thanks
