### ISSUE TITLE
Quit of CI?

### ISSUE THREAD

**Issue by ItzWid13** [drtshock/HCFProblems#259]
Hey, You kicked me of seeing the download of Jenkins.
ID: ItzWid

**Comment by Lilmac12312** [comment]
Maybe because you're either trying to re-sell the plugin or you've done something wrong.

**Comment by ItzWid13** [comment]
Nope, i buy it and im not in the ci

**Comment by Lilmac12312** [comment]
Well maybe you're not added within the CI or you got removed for a reason.

**Comment by drtshock** [comment]
I don't see your name on any download list so you must've been leaking the plugin which led to you being removed.
