### ISSUE TITLE
Chat Format

### ISSUE THREAD

**Issue by Aireesan** [drtshock/HCFProblems#262]
Is there a way I can have the chat format as such?

Factionless: &8[&c-&8] &7{PREFIX} {DISPLAYNAME} &c» &7{MESSAGE}
Factioned: &8[{RELCOLOR}{FACTIONTAG}&8] &7{PREFIX} {DISPLAYNAME} &c» &7{MESSAGE}

**Comment by drtshock** [comment]
Use your chat plugin.
