### ISSUE TITLE
Enable/disable deathbans in certain areas

### ISSUE THREAD

**Issue by Aireesan** [drtshock/HCFProblems#263]
I've seen other servers do this while using this plugin.
I want it so in safezone, entering will say this:
Entering SafeZone (No Deathban)
but for WarZone it'd be:
Entering WarZone (Deathban)
... and for road it'd be Road (Deathban)

You can see this on many servers.

**Comment by SaiCoFlu** [comment]
Road would be a faction, but I like the idea, although this plugin is literally turning into a HCT copy.

**Comment by Lotteries** [comment]
@SaiCoFlu I agree :/ Why not try Kohi people! ;o

**Comment by nsporillo** [comment]
Death-banning is handled by a separate plugin, therefore we cannot toggle it inside HCF. It is the responsibility of your death banning plugin to handle this using the factions api...

However, there is [this](https://bukkit.org/threads/hcteams-related-death-ban-plugin.364163/) thread which appears to be what you're looking for, except it's just an idea.
