### ISSUE TITLE
Requesting player kill count in /f who

### ISSUE THREAD

**Issue by AlfieC** [drtshock/HCFProblems#265]
Hey, 

I'm requesting a way to view players kill counts in /f who. Could be achieved using: 
````java
Player player = ...
return "&4[" + Integer.toString(player.getStatistic(Statistic.PLAYER_KILLS)) + "&4]";
```
Would be really useful for servers that track player kills. We currently track it for achievements and such. Not sure how FPlayer to Player would work though, haven't looked into the Factions API in a while. Could be cached on join, kill and leaving whilst the object is still active?

**Comment by nsporillo** [comment]
Thanks, didn't know it was as easy as that. Must have missed whenever the statistics system was added.

The new variables are `{faction-kills}`, `{faction-deaths}`, `{player-kills}`, and `{player-deaths}`.

Use build 54 or higher.

**Comment by SaiCoFlu** [comment]
@nsporillo I'm having a problem with {player-kills}, on /f show it currently looks like this:
http://prntscr.com/7fwv1t

And in the config, I have it set to the follow:
  - '&e- Online Members: {online}&6[&b{player-kills}&6]'

**Comment by AlfieC** [comment]
It uses the Statistics system so yeah supports UUIDs. You can clear these by deleting the player data in the world folder.

**Comment by SaiCoFlu** [comment]
Thanks @AlfieC , do you know how the other issue could be fixed though?
