### ISSUE TITLE
{player-kills} Issue.

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#267]
@nsporillo I'm having a problem with {player-kills}, on /f show it currently looks like this:
http://prntscr.com/7fwv1t

And in the config, I have it set to the follow:
  - '&e- Online Members: {online}&6[&b{player-kills}&6]'

**Comment by nsporillo** [comment]
You're looking for the player kills variable after each player in the members list correct?

Just affirmed, as this was requested already and i'm working on it now.

**Comment by nsporillo** [comment]
@SaiCoFlu you could always add it to the tooltips, that was the idea of adding tooltips (additional player info)

    show:
        - "&6Last Seen: &f{last-seen}"
        - "&6Rank: &f{group}"
        - "&6Balance: &a${player-balance}"
        - "&6K/D: &b{player-kills}&6/&c{player-deaths}"

Same goes with the factions, it's neater and requires less hackish methods on my end to piece together the specific request.

**Comment by SaiCoFlu** [comment]
@nsporillo I mean, I could do that, but meh not everyone enjoys the necessary hovering over someones name to just view kills, when it could be clearly stated beside their name on the /f show, in my opinion its a lot better, I'd like for you to make it compatible and for it to be put after the name, instead of before the players name if possible and I can assure you, others would like this to.

**Comment by nsporillo** [comment]
@SaiCoFlu that feature is not and will not be planned for addition. Already investigated and determined that is not worth the trouble to add this (a lot of work needs to be done to add this, it's not as easy as it would be with a private, custom plugin since it's just hard-coded that way)
