### ISSUE TITLE
Add option to disable over claiming

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#27]
Please.

**Comment by RydanMC** [comment]
Agreed, this is really needed.

**Comment by Doxify** [comment]
PLEASE someone.

**Comment by Doxify** [comment]
I'm will pay you guys to get this out faster, it's very important.

**Comment by nsporillo** [comment]
I'm in canada on vacation, i'll be home monday. 

That being said, you're going to have to explain this because overclaiming should already be disabled afaik.

**Comment by Doxify** [comment]
I explained to Trent but it's a bug actually. 

Players are able to overclaim anyone's land no matter what. Even if they're no raidable. I'd like to completely disable / remove over claiming if possible.

**Comment by drtshock** [comment]
It looks like the over claiming logic was completely removed in HCF causing it to not even pass through a check if it can or not. Will add it back in here in a sec.

**Comment by nsporillo** [comment]
@drtshock im looking at it now as this seems to be a pretty severe bug... didn't catch in initial testing.

**Comment by Doxify** [comment]
If you can remove it it'd be better or add an option to remove it, overclaiming isn't a thing in HCF.
