### ISSUE TITLE
{Bug} Tab color

### ISSUE THREAD

**Issue by KriticalPvP1** [drtshock/HCFProblems#271]
Please support could put the tab compatible with battle_border and Koth
Thx.

**Comment by KriticalPvP1** [comment]
by closed?

**Comment by MoeXIV** [comment]
Not a bug they're willing to fix. Those plugins are conflicting with HCFactions

**Comment by KriticalPvP1** [comment]
Where I can report this problem?

**Comment by nsporillo** [comment]
@KriticalPvP1 where did you buy hcf? Can you confirm you have a license?

Plus like @MoeXIV mentioned those plugins conflict with hcf. We'll have better integration someday.

**Comment by KriticalPvP1** [comment]
@nsporillo I buy the plugin in http://mcexchange.org/resources/hcfactions.2/ my nick is KriticalPvP

**Comment by nsporillo** [comment]
@KriticalPvP1 there is another account already receiving support and that is @KriticalPvP ...

**Comment by KriticalPvP** [comment]
WHAT THE FUCK
Thats not me

**Comment by KriticalPvP** [comment]
He tried to scam the plugin from me.

**Comment by Doxify** [comment]
lol ^

**Comment by KriticalPvP** [comment]
@Doxify I get tonnes of PM's on MC-Exchange for people asking for the plugin, lots of idiots... :/ someone actually stole my name... That is pathetic...

**Comment by Doxify** [comment]
Yeah that's pretty funny

**Comment by KriticalPvP** [comment]
Deleted my review on mcexchange

**Comment by KriticalPvP** [comment]
Hopefully they wont find me now >:)

**Comment by KriticalPvP** [comment]
Next they'll be stealing someone elses... O_o

**Comment by KriticalPvP** [comment]
Identity theft... @KriticalPvP1 Get the fuck out of here. I am the only @KriticalPvP You'll ever see.

**Comment by drtshock** [comment]
So that solves that mystery.
