### ISSUE TITLE
{color} variable bugging with Wilderness Factions

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#272]
As the title states. When you f show a real faction the color variable works as a header and footer, if you're in Wilderness the {color} variable just shows as "{color}" instead of the relationship. 
http://prntscr.com/7hqd4j

In this case, I really feel that there should be a custom section to customize the header for "f show"ing wilderness factions as I've seen plenty of servers using this plugin with just a line as the header. This means when you "f show" someone it's a blank line that's not informative.

Without this, server owners are forced to use the header with the {faction} variable in it, limiting creativity.

**Comment by nsporillo** [comment]
Not quite sure what you're getting at here, the {color} tag is working just fine. I think what you're asking for is a way to customize what is sent for a wilderness faction..? 

Default functionality is we send the first line of the show section (which now that I look at it, needs some work ;p)

**Comment by MoeXIV** [comment]
Wilderness Factions are meant to be enemies (as a wilderness names in tab are red indicating enemy).

**Comment by nsporillo** [comment]
@MoeXIV you're going to have to try to see if build 57 fixes your issue, and if not then post your /f show section and what the problem is...

The {color} tag works fine for me whenever I use it, not quite sure what is going wrong with yours so you're gonna have to provide more information.
