### ISSUE TITLE
Can't Find Long string that bugs the scoreboard

### ISSUE THREAD

**Issue by IlPicasso** [drtshock/HCFProblems#273]
Here is my Lang.yml

I can't get my scoreboard work
By the error log it says it is a long string but I can't find the long string and I dont understand why it happens either if lang.yml has not anything to do with scoreboards

This is the error log:
(edit, pasting this in for you): https://gist.github.com/nsporillo/45a1a5881978e0cdede7

**Comment by nsporillo** [comment]
Please post your errors in [here](https://gist.github.com/) and link the gist to us. Posting the raw log in your issue is unacceptable.

**Comment by nsporillo** [comment]
That aside, the issue isn't that a string is too long, it is that the string is empty and the method is using an index in the string that is out of bounds...

**Comment by IlPicasso** [comment]
Mt Lang file
http://pastebin.com/kNx8PTpg

**Comment by nsporillo** [comment]
Noticed you translated quite a bit so far. I dont really want to tell you to completely regen your lang file but if you're **still** having issues with this then perhaps it's worth a try. 

Also make sure to use the latest HCF unless you have some other reason not too.

**Comment by IlPicasso** [comment]
This strong was too long

default-prefix: '&r[&3{faction}&r]{relationcolor}'


After long testing :)
