### ISSUE TITLE
Where do I get new builds?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#274]
Where can I get the new version of HCF with the {player-kills} ? Has it even been fully released? I cannot find it on mc exchange? I'm a tiny bit confused?! All help is appreciated!

**Comment by nsporillo** [comment]
https://github.com/drtshock/HCFProblems/wiki/Frequent-Issues#access-to-ci--dev-builds

Latest features are found on the CI, in dev-builds. Developer builds are a big portion of why purchasing a license is a good ideas as opposed to using a leaked build - you get updates and support ;)

**Comment by KriticalPvP** [comment]
http://prntscr.com/7i3mx4

**Comment by KriticalPvP** [comment]
That happens, and thank you!
