### ISSUE TITLE
More than the set members?

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#276]
http://gyazo.com/74783467d0953cdc379bcbcc24531cda

I have no idea how it happened I was just reported the issue via one of my staff members. Currently running build 53

**Comment by drtshock** [comment]
Reproduce the issue and show us your config.yml and conf.json please.

**Comment by nsporillo** [comment]
@Lilmac12312 make sure that `factionMemberLimit` in conf.json matches the hard number you have in your show output. There isn't a current way to get actual factionMemberLimit via variable tags (but there should), so it's possible it could say 15 but really be unlimited.

**Comment by Lilmac12312** [comment]
Alright I'll double check on that, Thanks.

**Comment by Lilmac12312** [comment]
Never mind it was an issue with the conf.json as nsporillo said.
