### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by TemptingMC** [drtshock/HCFProblems#277]
Is there perm. nodes for /f dtr and /f unfreeze?

**Comment by Lilmac12312** [comment]
Yep not sure what they are though.

**Comment by TemptingMC** [comment]
@Lilmac12312 no help

**Comment by Lilmac12312** [comment]
Well you asked "is there" not "what are they".

**Comment by TemptingMC** [comment]
Your so technical. Stop commenting on my issue, you are no help.

**Comment by Lilmac12312** [comment]
I'm not being "technical", I'm just pointing out the problem within your post regarding if there is permission nodes for those commands.

**Comment by nsporillo** [comment]
https://github.com/drtshock/HCFProblems/wiki/Permissions-list

**Comment by KriticalPvP** [comment]
Oh look, @TemptingMC being an asshole again?
