### ISSUE TITLE
Invis potions

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#278]
When drinking an invisibility potion you are able to see faction members but I was wondering if you could make it so you can also see your allies too?

**Comment by SaiCoFlu** [comment]
I requested this before, they don't like working with TagAPI.

**Comment by Lilmac12312** [comment]
Ugh that's annoying but I'm sure it'd be the same as how they're doing it with faction members?

**Comment by nsporillo** [comment]
Closed this because moved issue and discussion to #279.
