### ISSUE TITLE
/f home command

### ISSUE THREAD

**Issue by Scarcee** [drtshock/HCFProblems#282]
When players go to do /f home it does not let them. But if they type the command in two times it lets them tp.
For example.  
when they type it in the first time it says wait 10 seconds. (Then does not TP)
When they type it in the second time it will work.

**Comment by drtshock** [comment]
Which version are you on?

**Comment by Scarcee** [comment]
Factions v0.0.7 -b59

**Comment by lyzha** [comment]
Works fine for me try to update maybe

**Comment by nsporillo** [comment]
This issue has been resolved here: https://github.com/drtshock/HCFProblems/issues/307

If for some reason you are still having issues, make a new issue.
