### ISSUE TITLE
Prevent pearl glitching?

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#283]
Would it be possible to prevent pearl glitching into bases?

Such as prevent people being able to pearl through fence gates by making the fence gates a full block.

If you want a demo on how to do this just lemme know and I can upload one soon :)

**Comment by Lilmac12312** [comment]
Bump

**Comment by lyzha** [comment]
There are plugins for that

**Comment by Lilmac12312** [comment]
@lyzha I don't want to use a separate plugin. It's just one thing and half out there are shit.

**Comment by Lilmac12312** [comment]
Bump

**Comment by SaiCoFlu** [comment]
You could easily get someone on Bukkit to make this.. no offence but this is a Factions plugin, not a core plugin or glitch prevention plugin.

**Comment by Lilmac12312** [comment]
Alright whatever lmao. Won't be surprised if someone else wants this in a months time.
