### ISSUE TITLE
Save Task Using Almost 100% of CPU

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#286]
http://prntscr.com/7nff4l
Simple enough. Server has been lagging during tests; did timings and I figured out Factions is causing all the lag :/

**Comment by drtshock** [comment]
Can you paste the full timings

**Comment by Doxify** [comment]
Same issue but mine is worse.

Also getting this error constantly in console:

http://hastebin.com/adejufanih.avrasm

Here are my full timings:

http://timings.aikar.co/?url=11825503

**Comment by drtshock** [comment]
@Doxify is your disk full? Did you reload / use plugman? Are your file permissions setup correctly?

**Comment by nsporillo** [comment]
Since some fixes seemed to have been pushed to factionsuuid, this is a real problem with some real solutions. I'll work on porting over the code to HCF.

**Comment by Doxify** [comment]
Uh this wasn't actually the cause of the issue for me, I thought it was the saves but It was a change I made in my multiverse config.

I made it look for portals in a 600 block radius rather than the default 150.

**Comment by drtshock** [comment]
Odd since factions doesn't care about portals when saving. I'll migrate the new save code over to hcfactions soon though.
