### ISSUE TITLE
Safezone/Warzone Unclaiming

### ISSUE THREAD

**Issue by Permiting** [drtshock/HCFProblems#287]
Hello, is there any type of command to unclaim all safezone or warzone's claimed land? cause for the time being all i know how to do is be in /f bypass and /f unclaim and it auto unclaims for warzone or safezone. but if there is a command to unclaim all of it, that would be ALOT easier!

  -Thanks Permiting!

**Comment by drtshock** [comment]
not for warzone or safezone. unclaimall only works for your own faction.

**Comment by Permiting** [comment]
Dang, This is really confusing trying to claim my spawn with safezone and out to 500 blocks with Warzone in every direction from spawn :(
