### ISSUE TITLE
Conf.json

### ISSUE THREAD

**Issue by LegitLanden** [drtshock/HCFProblems#289]
HCFactions doesn't allow you to edit the conf.json. I't will revert it back to it's default settings upon edit.

**Comment by Lilmac12312** [comment]
It works fine..

**Comment by nsporillo** [comment]
@LegitLanden it is completely possible to edit the conf.json while the server is running and then /f reload.

**Comment by OGCalee** [comment]
Is there anyway to be able to edit that chat format?

**Comment by drtshock** [comment]
Using a chat plugin.

If you're having issues editing it, then you're doing something wrong.

**Comment by LegitLanden** [comment]
what im trying to do is edit the colors of the names using the conf.json
for members to dark green instead of green i've tried doing DARK_GREEN,
DARKGREEN and nothing worked when i reloaded i also tried editing some
other stuff and it just went back to the default file and it didnt reset
the whole plugin so idk how this happened

**Comment by drtshock** [comment]
Edit the conf.json, save it to your server, then /f reload.
