### ISSUE TITLE
lang.yml

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#290]
http://hastebin.com/zunacezesu.xml I need help with my lang.yml :(

**Comment by drtshock** [comment]
in what way

**Comment by lyzha** [comment]
well it seems broken the plugin doesnt want that lang.yml for some reason

**Comment by lyzha** [comment]
Its maybe the {null} thinggy but idk

**Comment by lyzha** [comment]
Its broken i just need to know where i've been wrong please, thanks

**Comment by nsporillo** [comment]
[Yaml Parser](http://yaml-online-parser.appspot.com)
