### ISSUE TITLE
/f show remove undefined lines

### ISSUE THREAD

**Issue by WFloydBoy** [drtshock/HCFProblems#292]
So I see that some lines for /f show don't appear if the variable is blank but for some others, that's not the case.

  - '<a>Allies(<i>{allies-count}<a>/<i>{max-allies}<a>): {allies} ' # only shows if allies are made
  - '<a>Members Online: (&e{online-count}&6): {online}' # only shows if members are online
  - '<a>Members Offline: (&e{offline-count}&6): {offline}' # only shows if members are offline

I read an issue from back in March that supposedly added a config option to make something like this possible but the option wasn't specified and I can't seem to find it myself. Any help is appreciated, thanks!

**Comment by drtshock** [comment]
I'm not sure what the question / issue is.

**Comment by nsporillo** [comment]
The config comments are slightly out of date, because `minimal-show` was re-added. Therefore the lines show unless minimal-show is enabled.

![meep](http://puu.sh/iPxg8/0d67b64194.png)
