### ISSUE TITLE
Solo Faction Max Land

### ISSUE THREAD

**Issue by WFloydBoy** [drtshock/HCFProblems#293]
Could you possibly add an option to allow for us to configure what the max land should be for solo factions? If added, all factions would start with the configured amount and then each additional player adds the value set for the "land-per-player" option.

**Comment by nsporillo** [comment]
What exactly is wrong with the current set up? Based on your description, you want a solo faction to have say `5` max land. A 2 player faction would have 5 + `land-per-player`... and so on.

**Comment by WFloydBoy** [comment]
What's wrong with the current setup is that if I wish for a solo faction to have 10 land, a faction of 3 would be able to have a max land of 30. If there was a separate config value for solo-max-land, a solo faction could have 10 land and I could configure land-per-player to be 2 so a faction would have 14 land rather than 30.

**Comment by nsporillo** [comment]
Config update: https://gist.github.com/nsporillo/8b345266bbbf2ccede30

Servers updating to a build with this addition should not have any issues. 

@WFloydBoy sorry for the 2 month+ wait time on this easy update.
