### ISSUE TITLE
Config.json

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#294]
I cant edit prefixes and suffixes for in the conf.json you said we needed a third plugin which one you think about i would like to have a space between the name of the players and the faction name but no space before the name for faction less players

Afactionlessplayer
Faction_player

**Comment by drtshock** [comment]
get a chat plugin.

**Comment by lyzha** [comment]
Which one thats what im asking xd

**Comment by drtshock** [comment]
I use essentials chat :)
