### ISSUE TITLE
Combine this into one?

### ISSUE THREAD

**Issue by SaiCoFlu** [drtshock/HCFProblems#299]
Okay, so you guys added the Leader variable to display who the leader of the faction is and thats cool, although, when using the variable, this happens: http://prntscr.com/7s8xzy
It duplicates the two of them. I was hoping, this could be done a little better, and they'd only be displayed in the Leader variable, if used of course, as it looks a little silly two of them in my opinion. And also possibly supporting the tooltips in the leader variable if possible?

Thanks for reading.

**Comment by nsporillo** [comment]
I'll look into this, but with the way our variables are handled now - each line is independently parsed and thus removing the leader from the online members list is really the job of another config value somewhere, so i guess that's what we'll do.
