### ISSUE TITLE
People are not able to kick, leave, or invite while on dtr freeze

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#30]
I'd like this changed, can we allow users to do these things while on dtr freeze?

**Comment by nsporillo** [comment]
The system needs some time to work out the kinks :p 

When players leave a faction or get kicked, it should fine the faction some DTR so they can't just kick someone to boost their DTR when frozen.

Likewise, when players join a frozen faction, should just suspend the DTR addition until the freeze is over.

You think this is a good model?

**Comment by Doxify** [comment]
Yeah, sounds good.

**Comment by nsporillo** [comment]
To allow people to kick w/o penalty on DTR freeze: 
##### Set kick-penalty to -1

Builds 21 and up will have settings to block:
##### Leaving a frozen faction
##### Joining/Inviting to a frozen faction

Joining frozen faction is defaulted to being allowed. Leaving is defaulted to being blocked (as it can effect DTR when frozen).
