### ISSUE TITLE
[Question] Faction Kills

### ISSUE THREAD

**Issue by TemptingMC** [drtshock/HCFProblems#300]
Ok, I have version 60. I'm a bit confsued on how to set up these variables.
http://i.gyazo.com/a0188399d1ee80281717ee893c577cc9.png
They are using build 53: http://i.gyazo.com/1fdb528da0dc91994654f4a922bea296.png

How do I setup those variables? This is my config and server. So lost lol.
http://i.imgur.com/jsMU9Gv.png
http://hastebin.com/majisaxica.xml

Thanks :D

**Comment by SaiCoFlu** [comment]
They have another plugin hooking into it in I'm guessing.

**Comment by drtshock** [comment]
which variables?

**Comment by SaiCoFlu** [comment]
@drtshock Hes talking about the player kills. In the first screenshot, you see both players kills being displayed in the "name[<player-kills>]" on their server, however, it doesnt work on this current version of HCFactions as @nsporillo found it to difficult or something along those lines, and it would only display one players kills, not every single player. He's asking how does he do what they done.

**Comment by TemptingMC** [comment]
correct @SaiCoFlu @drtshock @nsporillo

**Comment by TemptingMC** [comment]
I currently have it set to show if you hover over players, but if you can add it to the side of their name then that would be cool

**Comment by nsporillo** [comment]
I could not find a way to accomplish the desired output without adding a bunch of code just so kills are in brackets next to the name instead of in the fancy message. Whoever has their /f show modified in the screenshot likely just has it hard-coded instead of configurable.
