### ISSUE TITLE
Tab Lag

### ISSUE THREAD

**Issue by TemptingMC** [drtshock/HCFProblems#301]
So basically, I had like 500 people connecting to the server on our SOTW and we have a filter system to make it where they all cant join at once. Everyone's tab name is RED and whenever someone joins the server, it updates everyones tags. It was lagging so bad we had to change to WHITE and that fixed it.

I really want to use RED, is it possible to make it where it doesn't lag/update whenever someone new joins?

**Comment by MoeXIV** [comment]
@TemptingMC Timings?

**Comment by TemptingMC** [comment]
no need for a timings, I just told you the problem @MoeXIV

**Comment by MoeXIV** [comment]
@TemptingMC Could easily be the simple fact you have to any players constantly logging in during SOTW. Every server lags during that point so I wouldn't expect yours not too. May not even be the tab if you refuse to show the timings.

**Comment by TemptingMC** [comment]
@MoeXIV reread what i said, i changed it to white, and it was fine, ik it's that cause you can see the tab update, your not a developer - please don't offer help towards me, I'd like Trent and Nick to help me.

**Comment by SaiCoFlu** [comment]
I can actually vouch for this as a similar scenario happened on another server. It was making the server lag, and would take atleast a few seconds for their name to go from white to red.

**Comment by MoeXIV** [comment]
@temptingmc Well my mistake then. Sorry for trying to offer my help to you as I though that's what you were looking for, help. I tried my best through what I've seen using this plugin. 

Once again, my apologies.

**Comment by drtshock** [comment]
Can you get timings as well as hcfactions and spigot versions + list of other plugins.

**Comment by TemptingMC** [comment]
@drtshock i cannot get timings as I refuse to revert to the same stuff since it lags. I can do everything else if that's ok

**Comment by drtshock** [comment]
Will be hard to do anything without timings. Regardless, give me everything you can.

**Comment by TemptingMC** [comment]
Ok
Version: http://i.imgur.com/XGUYYsR.jpg
Build for factions: latest

**Comment by drtshock** [comment]
what does /f version say. latest isn't a version.

**Comment by TemptingMC** [comment]
60

**Comment by nsporillo** [comment]
To touch upon your final question in the issue: 
It is not currently possible to prevent the "tab" from being updated on player join / player quit without losing functionality. Basically it's 100% required for the relation color player name tags above head. 

However, the sidebar does not necessarily require the components which drive the "tablist/nametag" features. Which means you could in theory have a sidebar that's leaner.. it will do less but also take less resources.

When I mean in theory, I suggest that it's not possible to do currently without a custom plugin and a custom hcf.

**Comment by drtshock** [comment]
You can always disable the default-prefixes which disables the tab names but keeps the sidebar.

**Comment by nsporillo** [comment]
Closing this because as @drtshock mentioned, setting default-prefixes to false will disable the tablist names (and above head nametags) but keep the sidebar.
