### ISSUE TITLE
HCFactions + HCFEssentials bug

### ISSUE THREAD

**Issue by ItsDovah** [drtshock/HCFProblems#302]
To be able to use HCFactions with HCFEssentials you need to do the following: http://pastebin.com/x0kuuALi

**Comment by ItsMonkeyyy** [comment]
:)

I have found out what the issue with HCFE's scoreboard. I did not know, but apparently I am using DRTShock's same scoreboard class. I am going to push an update on HCFE soon fixing this, but for now what you posted above can be a temporary fix.

**Comment by zBombard** [comment]
The pastebin has been removed how can i resolve?
