### ISSUE TITLE
RelationColor on Chat. Problem :/

### ISSUE THREAD

**Issue by iOxf** [drtshock/HCFProblems#303]
I need it so, as in the following image: http://imgur.com/eO1mKYK

I need to edit the color of the brackets  :/ ex:
&8[RelationColor&8] But I have this result: http://imgur.com/91JiUuP

i need help. :(

**Comment by ItsMonkeyyy** [comment]
Are you using Essentials?

**Comment by iOxf** [comment]
Yes :/

**Comment by nsporillo** [comment]
@iOxf sorry for the late reply, but you say you're using essentials chat? Changing the color of the braces isn't really an HCF problem as far as I know. So i'm going to close this so we can focus on other issues.
