### ISSUE TITLE
How do I prevent this?

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#304]
people are complaining about being able to use other peoples buttons, pressure plates and levers in other peoples claim.

**Comment by drtshock** [comment]
ok..?

**Comment by Lilmac12312** [comment]
I asked how do I prevent it within your plugin not for you to close the issue with a pathetic "ok"

**Comment by SaiCoFlu** [comment]
There was no use of how or prevent used in your issue, this is the reason he didn't help you, as when I first read this I didn't understand it either.

**Comment by Lilmac12312** [comment]
Alright then I'll edit it then.

**Comment by drtshock** [comment]
`territoryDenyUseage = true;`
Leave that as true.
`territoryEnemyDenyUseage = true`
Leave that as true.
Then add the materials you want to `territoryDenyUseageMaterials` and `territoryDenyUseageMaterialsWhenOffline`

**Comment by Lilmac12312** [comment]
Alright thanks. I'll reply back if I have any issues.
