### ISSUE TITLE
HCFEssentials is compatible with DrtShockHCF?

### ISSUE THREAD

**Issue by iOxf** [drtshock/HCFProblems#306]
i buy the last version of drtshock hcf b59, and have problem with the plugin of ItsMonkey , the scoreboard of HCFEssentials, removes colors tab, try everything but when threw a enderpearl colors come out when it is replaced by the Scoreboard HCFEssentials  :'/, http://imgur.com/qirUSLD

**Comment by drtshock** [comment]
Should talk to him. My scoreboard should work with his plugin if his scoreboard is disabled.
