### ISSUE TITLE
F Homing Bug

### ISSUE THREAD

**Issue by Scarcee** [drtshock/HCFProblems#308]
When players do ./f home it sometimes works.

For example sometime it will tp in 10 seconds. Another time 1 second to TP. But then it also stops working. And also players can run around while tping.

Video to show the issue: https://www.youtube.com/watch?v=3gRIRXV_N3E&feature=youtu.be

Factions version: v0.0.7-b59
Sever ip to see for yourself: quantumhcf.com

**Comment by Scarcee** [comment]
Mc market username : Scrarcee , to prove that i bought it...

**Comment by Scarcee** [comment]
@nsporillo

**Comment by nsporillo** [comment]
This issue has been resolved here: https://github.com/drtshock/HCFProblems/issues/307

If for some reason you are still having issues, make a new issue.
