### ISSUE TITLE
People dont lose DTR on death

### ISSUE THREAD

**Issue by nscwalk** [drtshock/HCFProblems#31]
Dont know why ,but whenever someone dies in the latest version of hcfactions they do not lose dtr. even when set to 1 the faction loses no dtr. I thought it may have been because I edited the /f show
but it wasnt that because I rest the config file and people dont lost dtr. I feel as if this doesnt have to do with the plugin just something setup wrong. because I would imagine someone would have reported this sooner

**Comment by nsporillo** [comment]
Can anyone else confirm this issue? 

When I tested, it appeared to be working just fine. 

Will apply a label and investigate once confirmed.

**Comment by Doxify** [comment]
Worked for me.. Players lost dtr when I killed them.

**Comment by nsporillo** [comment]
Looks like an issue with the setup then, like @nscwalk guessed in the op. 

@nscwalk could you try the latest build and a clean plugin directory and see if the problem persists?

**Comment by nscwalk** [comment]
Ok I seem to have lost DTR On a clean plugin directory Ill have to look for some issues that are possibly causing this to not work

**Comment by nscwalk** [comment]
So this was somehow fixed I just deleted tons of plugins and plugin configs that I didnt use or need. overall it was fixed thanks for the support

**Comment by nsporillo** [comment]
@nscwalk Glad it is working for you. Sometimes a overhaul of your plugins will somehow fix issues like that. Ofcourse it is not practical to wipe a production servers data like that, but that is what test servers are for :p

**Comment by nscwalk** [comment]
ISSUE HAS BEEN REOPENED* 
I figured out how I was testing this DTR this was wrong. There is a problem where you do not lose DTR if you die to a player. Any other cause via /kill /suicide burning in lava suffocating dying to a mob you do. Don't understand why this is happening I now believe this a legitament issue and not an error with my plugins

**Comment by nsporillo** [comment]
@nscwalk I just tested this and a player in a faction will lose DTR when they die from pvp.

**Comment by nscwalk** [comment]
hmmm
this seems weird especially since another person reported this issue ill have to take another look

**Comment by nsporillo** [comment]
@nscwalk try latest build. If you continue to have issues, enable debug in config and then send me some output so I can see what's wrong.
