### ISSUE TITLE
Pressure Plates Are Lethal

### ISSUE THREAD

**Issue by WFloydBoy** [drtshock/HCFProblems#310]
This isn't a big bug but I thought it was quite funny and then the pessimistic side of me thought how this can actually be abused
http://gyazo.com/395445c4f87605ff027cf0d00555305e
As you can see, players are unable to interact with pressure plates in territory. Players could use then use pressure plates to just be the cause of death in traps.

**Comment by Lilmac12312** [comment]
Can you paste how you disabled pressure plates please as I'm having issues getting it working.

On the side note, this needs to be fixed

**Comment by WFloydBoy** [comment]
https://gist.github.com/WFloydBoy/71ba67aee2f64f5e03ca

**Comment by Lilmac12312** [comment]
Cheers.

**Comment by drtshock** [comment]
You can make it so it doesn't deal them damage.

**Comment by WFloydBoy** [comment]
How? I have PainBuild set to false on all available options and I have actionDeniedPainAmount set to 0.

**Comment by WFloydBoy** [comment]
@drtshock 
How? I have PainBuild set to false on all available options and I have actionDeniedPainAmount set to 0.

**Comment by WFloydBoy** [comment]
@nsporillo @drtshock

**Comment by Lilmac12312** [comment]
bump

**Comment by drtshock** [comment]
Confirmed this was an issue with furiouspvp.

**Comment by drtshock** [comment]
Fixed http://git.io/vOQKl

**Comment by WFloydBoy** [comment]
I don't have access to the page or development builds. Could I please have access?

**Comment by WFloydBoy** [comment]
Was the fix for this meant to stop players from taking damage and the interaction spam because right now it just stops taking damage but still spams https://gyazo.com/68a56866565c49b532191ca3431c88f2 @drtshock
