### ISSUE TITLE
Same F home Bug

### ISSUE THREAD

**Issue by ItsPotions** [drtshock/HCFProblems#312]
For some reason when players do /f home it allows them to continue running and still will teleport them out, also when players do f home sometimes it take 3 seconds-15 seconds and sometimes doesnt even work.

video: https://www.youtube.com/watch?v=3gRIRXV_N3E&feature=youtu.be (same as scarcee)

**Comment by nsporillo** [comment]
This issue has been resolved here: https://github.com/drtshock/HCFProblems/issues/307

If for some reason you are still having issues, make a new issue.
