### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#313]
http://prntscr.com/7xws2t

Why is this happening when I try to download latest updates.

**Comment by drtshock** [comment]
Are you logged in..?

**Comment by KriticalPvP** [comment]
yeah

**Comment by KriticalPvP** [comment]
?...

**Comment by KriticalPvP** [comment]
bump

**Comment by nsporillo** [comment]
The link exists still so you're definitely just not logged in. Try re-logging.

**Comment by drtshock** [comment]
Fixed.
