### ISSUE TITLE
Feature Request: Different DTR loss per world

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#316]
Add the option for us to set how much DTR is lost in a world.

For example, 1 DTR would be lost in the overworld and only .50 would be lost in the nether.

**Comment by drtshock** [comment]
I like it.

**Comment by KriticalPvP** [comment]
Possibly places where DTR is NOT lost on death?

**Comment by nsporillo** [comment]
@KriticalPvP places as in worlds..?

**Comment by drtshock** [comment]
Added. You'll need to update the dtr loss section in your config to https://gist.github.com/drtshock/f162f7b18b03809bb669

**Comment by Doxify** [comment]
Thanks!

**Comment by Doxify** [comment]
I don't think you pushed the update?

https://imgur.com/7udbW5j.png

**Comment by drtshock** [comment]
I did but it looks like it's not building. I just manually built.

**Comment by KriticalPvP** [comment]
@nsporillo Yeah, so in world "a" I lose 0.5 DTR per death and in world "b" I lose 1 DTR per death

**Comment by Doxify** [comment]
@KriticalPvP That's exactly what this post is about... it was already added.

**Comment by drtshock** [comment]
Yes it was added in build 61 on jenkins.
