### ISSUE TITLE
Minor lang file bugs

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#318]
So I was changing stuff in my lang file when I noticed some things that were off.

For reference, the user "Sainly" is not in my faction. 

I ran /f admin sainly and the message I got was "The target player musn't be yourself".
I also ran /f mod sainly and the message I got was "The target is a faction admin. Demote them first."

Not anything big but just wanted to bring it up, not sure if there's anything else like this but if there is I'll update this post.

**Comment by nsporillo** [comment]
The issue before was if you were in a solo faction and ran /f admin then it'd disband the faction. 

When promoting a new leader, if there exists no other mods or admins in a faction - it will be disbanded. So, what I did was prevent using /f admin if you're in a solo faction. That's all. 

Add sainly to your faction, and then /f admin him.

As far as /f mod goes, I never touched that. I'm guessing you need to /f admin sainly again to demote him and then run /f mod. Try that out.

**Comment by nsporillo** [comment]
@Doxify is this resolved?

**Comment by Doxify** [comment]
Yes, all good
