### ISSUE TITLE
RelationColor on Tab, lost colors, with custom scoreboards

### ISSUE THREAD

**Issue by iOxf** [drtshock/HCFProblems#319]
API, for this?, have a custom scoreboard for hcf, and the TAB, lost the relationcolor, change to White. help (?, TemptingMC have a hcf and not lost the colors with a custom scoreboard...

**Comment by drtshock** [comment]
Relation color in tab is done via scoreboards.

**Comment by iOxf** [comment]
http://imgur.com/qirUSLD custom scoreboard. and lost the colors ....

**Comment by Doxify** [comment]
Well yeah... of course you lose the relation colors if you use a custom scoreboard..

**Comment by iOxf** [comment]
:/
