### ISSUE TITLE
Enemy territory 

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#32]
On the latest build I was doing some tests and was not in a faction. When I tried to hit someone while they were on their claimed land I got this message. https://imgur.com/WRW8GlS However on HCF everyone should be enemies.

**Comment by nsporillo** [comment]
`However on HCF everyone should be enemies.`

That's what you have in config, correct?

Thank you for reporting this, again-will work on this when I'm back home :)

**Comment by Doxify** [comment]
I do have that set as the default relation of course, its the plugin that is recognizing everyone as enemies when you are trying to hit people in their territory.

**Comment by nscwalk** [comment]
Set max truce and neutrals to -1 maybe that might help

**Comment by nsporillo** [comment]
This is being fixed now, it was a issue with relations. 

Try now with the latest build. I just tried and it seems to be working fine.
