### ISSUE TITLE
Leaked

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#321]
https://leakforums.net/thread-584092

Apparently someone leaked my CUSTOM hcf plugin.

I downloaded it and it turns out to be an outdated version of HCFactions.

I don't even have a plugin named hydrahcf.jar ..

Just wanted to report this.

**Comment by drtshock** [comment]
Should send me the jar on Skype since I always browse via a VPN that is blocked on that site and don't want an account. If I have the jar I can figure out who leaked it.

**Comment by Doxify** [comment]
Sent.
