### ISSUE TITLE
BUG: People have more DTR than they are allowed.

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#327]
Not sure how this happened... but this isn't the first time it's happened.

![vx9v6ad](https://cloud.githubusercontent.com/assets/9636316/9217656/33ececd8-407f-11e5-9359-c052d88e9e06.png)

**Comment by nsporillo** [comment]
Are they usually over on DTR by a small amount?

**Comment by Doxify** [comment]
The only other time I saw it happen they were over by 1

**Comment by nsporillo** [comment]
Turn on debug in config and let it be for a little while. 

Paste the log and link. (you can privately if you really want)

We've had built in debugging for DTR for a good while now, since there was so many issues awhile back.

**Comment by nsporillo** [comment]
No reply. Consider this resolved/no issue.
