### ISSUE TITLE
faction-land-max issue

### ISSUE THREAD

**Issue by WFloydBoy** [drtshock/HCFProblems#328]
# Max land a faction can have claimed
  faction-land-max: 36
  
  # How much additional land a faction gets per member
  land-per-player: 3

  # How much land a solo faction starts off with
  initial-land: 9

https://gyazo.com/9a1cad5ba89598ff47aee9c29c07fe4a

It appears that as I change the "initial-land" value, the max land goes up or down. The amount set as "initial-land" simply adds ontop of the configured "faction-land-max" value.

**Comment by drtshock** [comment]
It does which I think was an odd way to implement it.
