### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by iOxf** [drtshock/HCFProblems#329]

**Comment by drtshock** [comment]
what

**Comment by SmileyyyFaceee** [comment]
I'm assuming he means a warning message when your faction's DTR is in the raidable limits, similar to Towny's warning message when funds are too low to handle the upkeep. I could definitely see this being a neat little add-on.

And me being me, I enjoy making sarcastic messages. Something like "lelele, your faction is getting #rekt m8. Gonna get raided soon ooo"
