### ISSUE TITLE
./f login Default?

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#33]
Can u make it where we can set it to default: true rather than false in the config or something?

**Comment by nsporillo** [comment]
This feature was already added in the latest build on the CI. 
Builds #13 and up should contain the feature you're looking for.

**Comment by TMNetwork** [comment]
That isn't true, I have the most up to date build and it doesn't show me where I can set this to default
@nsporillo

**Comment by nsporillo** [comment]
It should automatically be on by default. Not configurable. This was https://github.com/drtshock/HCFProblems/issues/28

**Comment by TMNetwork** [comment]
@nsporillo It's set to false.

This is my plugin version:
http://i.imgur.com/ig1dFJX.png
