### ISSUE TITLE
Question for Trent/Nick

### ISSUE THREAD

**Issue by TemptingMC** [drtshock/HCFProblems#333]
Hey Trent/Nick,

In build 62, you added this push in (Add async saving from FactionsUUID. Addresses drtshock/HCFProblems#286 (commit: 6dffdaba70e2c030bbe2bec0e2d1e2c0e9a159ce) (detail)); I wanted to ask if that will fix the tab/above player head thing updates or does this have nothing to do with that :dancer:

**Comment by drtshock** [comment]
That update just adds a better saving method.
