### ISSUE TITLE
Chat has "< >" looks weird.

### ISSUE THREAD

**Issue by bywaco** [drtshock/HCFProblems#335]
@drtshock my chat looks like this after buying your "HCFACTIONS" plugin and putting it in my plugins folder, https://gyazo.com/53ec3ce7c39e977927220af74a0894c7 where can I remove the "< >" and add "[ ]" outside there faction names such as, ([FactionName] playername: message) please respond back.

And also how can i remove there faction title from tab.

**Comment by drtshock** [comment]
Use a chat plugin and disable default-prefixes in the config.yml for the faction title from tab.
