### ISSUE TITLE
DTR Freeze

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#336]
Haven't tested this we in away, if you set the DTR loss to a custom world to nothing and someone dies, does that trigger your DTR Freeze?

Can't test as I'm away

**Comment by nsporillo** [comment]
You can't currently because it's not even implemented yet, but when it is then no if the DTR loss is 0 then it shouldnt trigger DTR freeze IMO. But i guess this is a good issue for discusion.

**Comment by nsporillo** [comment]
Not sure why I didn't answer this way back when you asked, but the answer is no based on the reasoning in my comment from August.
