### ISSUE TITLE
Feature Request: Stop the claimed land for warzone spam

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#337]
So this isn't a big request but it'd be a nice addon.

We claim a lot of land as warzone for our resets and it literally spams your chat so much. Can you possibly just have it like tell you when it starts claiming and then again when it's done claiming..? and this would only be for warzone claims.

Example:
On start: "You have started claiming X warzone chunks".
On finish: "You have successfully claimed X warzone chunks."

**Comment by ZenithPvP** [comment]
or /f claim [amountofchunks from position] WarZone @doxify its like a one time spam and you can clear your own chat

**Comment by MoeXIV** [comment]
Not when you're claiming WarZone for your whole warzone. It could easily be spamming your chat for 10 minutes or more.

**Comment by Doxify** [comment]
Yeah it's a one time spam that lasts 10+ minutes lol.

I'm saying that a message for each chunk that is claimed is NOT needed.

**Comment by nsporillo** [comment]
By "on start" are you referring to the auto claim where you walk around and you claim land as you enter a new unclaimed chunk?
