### ISSUE TITLE
Teleportation Problem.

### ISSUE THREAD

**Issue by PatManGames** [drtshock/HCFProblems#340]
When players use /f home, it says wait 10 seconds, but if you get hit or move, it still teleports you after the 10 seconds. Am I missing something?

**Comment by nsporillo** [comment]
https://github.com/drtshock/HCFProblems/issues/307

Check if the information provided there solves your issue. If not please let me know and i'll look further into this.

**Comment by PatManGames** [comment]
Ok thanks.
