### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#341]
![image](https://cloud.githubusercontent.com/assets/9636316/9701992/1b630390-53fe-11e5-87ee-0d3a3b1ef8af.png)

**Comment by MoeXIV** [comment]
Same for me, was doing timings - everything was minuscule and I see my saveTask at 139%.

**Comment by drtshock** [comment]
The pct total is still at around just 2%. How long of a period were these timings from? Are you actually noticing any lag or just seeing this in the timings? A lot of the stuff in that report is done async anyway.

**Comment by MoeXIV** [comment]
For me, (with just 3 players) I noticed no command lag but player movement was somewhat skippy.
