### ISSUE TITLE
Proble With F Show Config Using {online} variable

### ISSUE THREAD

**Issue by KinkiPvp** [drtshock/HCFProblems#342]
Hi, i purchased HCFactions on spigot. My problem is when i try to put the variable {offline} or {online} in   
f show config i got Internal Error Occured or similar. I think the Spigot versions are outdated pls help me.
Pd. srry for my bad english im spanish xD

**Comment by KinkiPvp** [comment]
Can u add me to buyers List? I Purchased it on spigot -.-

**Comment by drtshock** [comment]
You can't purchase this plugin on spigot. Can you link me to where you got it?

**Comment by KinkiPvp** [comment]
I mean McExchange https://mcexchange.org/resources/hcfactions.2
https://gyazo.com/46b53224139b048fe43e4a155a6ac303 pls can u help me :C

**Comment by drtshock** [comment]
What's the error?

**Comment by KinkiPvp** [comment]
When i use the Variable {offline} or {online} in the f show config when i use /f show ingame this say Internal Error Occurred https://gyazo.com/ec3d61ea214a1b1d2d6be166d1532592

**Comment by drtshock** [comment]
What's the error in console?

**Comment by KinkiPvp** [comment]
https://gyazo.com/b7a3e946fc86d1faf586e0a14bcbdd2e Srry for not be Accurate im new in this and i cant say u the Error just send a gyazo xD

**Comment by nsporillo** [comment]
@KinkiPvp next time please post your error log using gist.github.com. It is much easier for us. 

Can you paste your entire server startup log to a gist please? It appears to be an issue with your permissions plugin, but I need to know some more details.

**Comment by KinkiPvp** [comment]
Wait i gonna Delete the Permissions Plugin

**Comment by KinkiPvp** [comment]
I removed PermissionsEx and i still getting the same error 
this is the start of Factions https://gyazo.com/153afd5574b7705bf3569b4253504747
but i get this when i use /f show https://gyazo.com/e6e2b7695db22f89651d8b7509564501

**Comment by nsporillo** [comment]
The error you are getting means vault is not finding a permissions plugin. @KinkiPvp

**Comment by KinkiPvp** [comment]
Thank U i gonna try Fix it

**Comment by KinkiPvp** [comment]
I got a doubt How can i put The factions prefix in chat into [ ] Like [Kinki]Mathh: Hi
Srry for this but im begineer
