### ISSUE TITLE
Problem with /f show {online}

### ISSUE THREAD

**Issue by PatManGames** [drtshock/HCFProblems#344]
For some reason when you use /f show, it shows an internal error instead of the listed players online or offline. Any idea why?

**Comment by nsporillo** [comment]
Without the stacktrace (error in console) won't be able to help much. 

Please paste your entire error log to gist.github.com and link as a reply.

**Comment by PatManGames** [comment]
https://gist.github.com/PatManGames/5a930b63037f786c9522

**Comment by drtshock** [comment]
Get a permissions plugin with super perms (basically any).
