### ISSUE TITLE
Question about kills

### ISSUE THREAD

**Issue by CharlieClewer** [drtshock/HCFProblems#345]
Hey! I recently purchased this plugin and It's working really good, but I just wonder about something.

How can you add the kills that a player has before their names in /f show?

Thanks <3

**Comment by nsporillo** [comment]
You can't, you can only add them as a member of the list when you hover over their name. 

This has been asked before, and was/still is a request to clone another feature in a different plugin. However due to how configurable HCF is, it'd take more work then it's worth to allow kills before names.
