### ISSUE TITLE
Problem with crashing.

### ISSUE THREAD

**Issue by PatManGames** [drtshock/HCFProblems#347]
So, every time a player uses /f create or /f disband they crash. Heres the crash report.
https://gist.github.com/PatManGames/1974975a3f92e2bc08c0

**Comment by nsporillo** [comment]
What version of HCF and Spigot are you using? (latest isnt a version)

**Comment by PatManGames** [comment]
HCF: 0.0.7-b59main
Spigot: git-Spigot-1649

**Comment by nsporillo** [comment]
Okay, thank you. Will work on a fix.

**Comment by PatManGames** [comment]
Alright cool.

**Comment by nsporillo** [comment]
@PatManGames Spent some time trying to find the source of this issue but failed.

Is this still happening? Have you noticed a specific build where it started or a specific more recent build where it no longer occurs?
