### ISSUE TITLE
Tab coloured names

### ISSUE THREAD

**Issue by CharlieClewer** [drtshock/HCFProblems#348]
Heey!

I wonder if its possible to put on the name colours/tab colours for enemies/allies without the faction name before the name. It looks bad when people have their fac names before their names in the tab list or in the name.

Thanks!

(Tried to find if this was asked before but didn't find it)

**Comment by nsporillo** [comment]
Yes, find `default-prefix` in your lang.yml file.

Use `default-prefix: '{relationcolor}'`

This is the default setting, so i'm not sure why it wasn't like this originally for you..

**Comment by CharlieClewer** [comment]
Thanks!
