### ISSUE TITLE
./f invite and /f show issue

### ISSUE THREAD

**Issue by TemptingMC** [drtshock/HCFProblems#349]
Hey,

All of a sudden, my server has a problem where some people that you /f show that are in a faction, don't show up that there in a faction. It replies with the msg as if the player isn't in a faction...

/f invite:
Some players cannot be invited to a faction. I did /f deinvite {playername} and it revoked it and all, but when i invited them, it doesn't reply anything not even unknown command, just nothing.

No errors in console :/

**Comment by MoeXIV** [comment]
For the second issue (f invite), that's happened on my servers before; you can restart to fix it, but that's not really a fix :/

**Comment by TemptingMC** [comment]
@MoeXIV yea that won't be happening xD

**Comment by MoeXIV** [comment]
Haha, yeah. Definitely not ideal, hope they find the cause of this.

**Comment by HeyImYellow** [comment]
+1 have noticed the bug on my server & Tempting's hcf server, it's pretty annoying when trying to gank people because you're thinking they're not in a faction then you get 20v1'd not cool :P

**Comment by TemptingMC** [comment]
It was an issue with factions saving, etc.

I'm rereleasing my entire network and this problem will be fixed.

Lol I'm overkilling my network in order to handle everything. 14 new dedi's
LOOOOOOL

**Comment by MoeXIV** [comment]
....

Overkill x2

**Comment by TemptingMC** [comment]
close this; it's fixed :dancer:

**Comment by drtshock** [comment]
how

**Comment by TemptingMC** [comment]
Did a reset. Our server crashed and the factions data didn't save properly.
I'm assuming that was the issue.
