### ISSUE TITLE
HCFEssentials problem

### ISSUE THREAD

**Issue by CharlieClewer** [drtshock/HCFProblems#354]
I'm using HCFEssentials and it just removed the coloured tag... Is there a fix for that?

**Comment by nsporillo** [comment]
Can you explain a little more?

What is the expected functionality, what is the actual functionality. What's not working..

What do you mean by "tag", etc

**Comment by CharlieClewer** [comment]
By tag I mean the coloured tag that players get when enemy/faction/ally. It was working correctly but after I added HCFEssentials it got removed and now it seems white. (as normal). Did you see this problem before? know how to fix it? I understand that the problem is obviously something with HCFessentials but just wanted to know if you know what's wrong.

Thanks

**Comment by drtshock** [comment]
Likely because their scoreboard conflicts.
