### ISSUE TITLE
Faction tags

### ISSUE THREAD

**Issue by roastingnigrs** [drtshock/HCFProblems#355]
Hello when I speak in chat or any of my community members, it says : https://gyazo.com/124fed6649969affde15affd9d4a56e9 can I change this?

**Comment by nsporillo** [comment]
Sorry for the late reply. But yes you can change those in the conf.json file. 

Below is a screenshot of the values in the source code, the variable names match the values in the conf.json file. 

![pic](http://puu.sh/kKsGC/80b6317856.png)
