### ISSUE TITLE
Developer API

### ISSUE THREAD

**Issue by HeyImYellow** [drtshock/HCFProblems#357]
Hello I am creating this post on behalf of my friend who is a developer and I was wondering where to find the developer API for HCFactions (I'm not so experienced so correct me if I'm wrong about this).

We were looking into adding walls around claims with PvP Protection etc but couldn't find an API anywhere, if someone could show me where it is, would be most grateful.

Thanks.

**Comment by nsporillo** [comment]
There exists events (in the package `com.massivecraft.factions.event`) that are mostly for developer purposes.

The classes FPlayers, Factions, Conf, and Board can be used for developer purposes. 

If you're friend is curious the source for FactionsUUID is [here](https://github.com/drtshock/Factions/tree/1.6.x/src/main/java/com/massivecraft/factions) and is very similar to HCF.
