### ISSUE TITLE
** removal?

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#36]
I am trying to remove the stars from the chatTag
NOT THE /f SHOW or anything else,

http://gyazo.com/58adf5708be5ae9e35a7471d2cbc6118

Just the tag.

It will not remove properly or I am just doing something wrong.

**Comment by Doxify** [comment]
config.json

**Comment by TMNetwork** [comment]
"chatTagFormat": "%s",
makes no sense to me.
Tell me what i should put instead of %s
@Doxify

**Comment by Doxify** [comment]
The highlighted area is what you edit to change the stars.

![3euutik](https://cloud.githubusercontent.com/assets/9636316/6766937/1ddd9694-cfd8-11e4-8a0c-43fad0229b51.png)

**Comment by TMNetwork** [comment]
Yes, but that removes it from /f show which i don't want @Doxify

**Comment by MoeXIV** [comment]
@Doxify that's not what he's asking. He's trykng to make everyone's "*" remove for the chat tag, as in when they speak in chat, not the "f show", as this is in HCF/Kohi.

**Comment by TMNetwork** [comment]
@nsporillo @drtshock in hcf, the tag in chat should be different than the /f show
http://i.imgur.com/PweVlSM.png
It shouldnt show the prefix in the chat tag, only in /f show

**Comment by TMNetwork** [comment]
@nsporillo when should this be fixed?

**Comment by TMNetwork** [comment]
@nsporillo please add this dude

**Comment by drtshock** [comment]
I personally don't see why we should differentiate.
