### ISSUE TITLE
System faction relation issue. 

### ISSUE THREAD

**Issue by Eternalrealms** [drtshock/HCFProblems#360]
Hello, with the newest update to HC Factions (B64) system factions are using the default relation option in the config rather then being in truce with everyone like the previous versions. This is an issue for my server due to the fact that I want to deny teleportation commands in enemy territory but not wilderness, safezone etc. I'm not sure if this was intended but I thought I would get a definite answer here. 

Thank you for the help! If you need proof of purchase let me know. 

Using spigot 1.8.8

**Comment by nsporillo** [comment]
I don't see your username on the buyers list so let me know what it is on mcexchange.

As far as your issue goes, I don't quite understand what you mean. If you want the default relation to be truce, you can set that in the config.yml. If you want to deny tp commands in enemy territory you can do that as well. The default relation is just what a faction defaults relation to everyone else is when they are first created.

**Comment by Eternalrealms** [comment]
Basically what i'm trying to accomplish is, having all player factions be enemy by default. But have Wilderness, Safezone and Warzone truced so players can use commands in those factions that they wouldn't be able to use in enemy territory. 

For example you're not able to /f home in enemy territory but you should be able to in wilderness. In all previous updates, this worked but with the current release it does not.

Username/Email is Ambrewgaming@yahoo.com

**Comment by Eternalrealms** [comment]
Any update on this?

**Comment by nsporillo** [comment]
Build 64 did not change anything related to what this issue is regarding compared to Build 63.

**Comment by Eternalrealms** [comment]
Well the issue i'm having is not happening on build 63 only on build 64.

**Comment by Eternalrealms** [comment]
Any update on this?

**Comment by nsporillo** [comment]
There wasn't anything changed between 63 and 64 that could cause this issue. 

In order for me to go in and test this, i'll need some time. Unfortunately, this is not the best time during the semester for that.
