### ISSUE TITLE
Issues & additions.

### ISSUE THREAD

**Issue by HeyImYellow** [drtshock/HCFProblems#363]
Hello, sorry for asking the same question but my server have been requesting many new features which relate to factions such as subclaims, kill stats but the only problem is updates are released very irregularly and you stated before you will not be fixing the kill stats.

As I have purchased the plugin would it be possible for me to gain access to the source code so we could implement some new features, I and my players would appreciate it a lot.

Please do not take this post the wrong way, I am simply asking if we could access the source so we can update our server and add new things without having to wait for them to be added.

Thanks.

**Comment by Vamure** [comment]
You will not gain access to the source code, I can promise you that

**Comment by HeyImYellow** [comment]
Thanks for the ever-waited reply of 18 days.
