### ISSUE TITLE
42 max land but it's set to 36?

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#364]
https://gyazo.com/b1818b4615d6ac241ff28ba65722bcb2

**Comment by nsporillo** [comment]
Sorry for the very late reply. Not sure if I'll be of much help this much later on, but..

Is this still an issue? Can you link to a gist of your config.yml?

I took a look into the source back when this was created to see if there was any possible way for max land to exceed what is in config, and didn't see anything - but also didn't reply to this issue.

**Comment by Lilmac12312** [comment]
Yeah it's still an issue. I'll send you my config.yml now.

https://gist.github.com/Lilmac12312/dda912cea8298e287534

**Comment by nsporillo** [comment]
So the code in question is here: 
    public int getMaxLand() {
        int landPerPlayer = P.p.getConfig().getInt("hcf.land-per-player", 6);
        int maxFactionLand = P.p.getConfig().getInt("hcf.faction-land-max", 36);
        int initialLand = P.p.getConfig().getInt("hcf.initial-land", 6);
        return isPermanent() && isNormal() ? maxFactionLand : Math.min(initialLand + ((getSize() - 1) * landPerPlayer), maxFactionLand);
    }

What I think is happening is the max land you're getting is initialLand (6) + the size of the faction - 1 times how much land per player.

I don't quite understand your settings however. If your max is 36, then why is it 36 per player..? That just means every faction by default has 36 and thus your initialLand should be 36 and your landPerPlayer should be 0.

**Comment by Lilmac12312** [comment]
The land per player is for solo factions?

**Comment by Lilmac12312** [comment]
Never mind I fixed the issue by using a older version of the plugin. Hopefully it doesn't occur again :P

**Comment by nsporillo** [comment]
You just reverted to a version before initial land was added. I don't quite understand how using an older version makes more sense then fixing your config. 

The land per player is not for solo factions, the initial land is. So if you have 1 player in a faction, you can configure how much land they start off with, and then each additional member adds a certain amount of land.

I pointed out that giving 36 land per player, while having 36 max land - doesnt make any sense. You can set the initial land to 36, and the land per player to 0 and achieve what you're looking for without exceeding the land max.

**Comment by Lilmac12312** [comment]
The way my configuration file is setup has worked till 1 month ago. I've always had it so each player and faction get 36 land.

**Comment by nsporillo** [comment]
Yes, we added initial-land to the config.yml which greatly increases the options.

For instance, if you want solo factions to have 6 land, but dont want the land to grow by a factor of 6 with each new member, you can set it to 2. 

1 player: 6 land
2 players: 8 land
3 players: 10 land

Instead of:

1->6, 2->12, 3->18, and so on.

You're welcome to use older builds, but they're not necessarily supported. Especially when the functionality you wanted is as easy as changing two values in the config.

**Comment by Lilmac12312** [comment]
Yeah I would use newer builds but the HCFCore I run doesn't support the new builds and breaks completely so I'm stuck on lower builds :P

**Comment by nsporillo** [comment]
If you reported the issues, I could most likely add compatibility...

**Comment by Lilmac12312** [comment]
I mean like, issues with the HCFCore I use. The developer for the plugin isn't active anymore.
