### ISSUE TITLE
Help with /f show.

### ISSUE THREAD

**Issue by iOxf** [drtshock/HCFProblems#366]
I get the latest version of hcfactions. and i have a problema with /f show.
the dtr is
0,001 / 1,01 (Solo Faction)
I need fix this. to
DTR  0.1 / 1.01 (with point, and repair the more zeros in  the regeration (0,001).
Screen of the problem: http://prntscr.com/9hjn2q
I need this: http://prntscr.com/9hjrny

**Comment by nsporillo** [comment]
That is most definitely not default configuration. You need to go into your lang.yml and change GENERIC_DECIMALFORMAT to `#.#`. 

By default it is `#.###`. Which means there is 1 digit on the left of the decimal, and 3 on the right.

**Comment by iOxf** [comment]
Okay i fix. but i need Replace the , for . in the /f show in game. y change to #.## but in game i have #,## (with comma) i need a (point .)
