### ISSUE TITLE
Faction kills tracking

### ISSUE THREAD

**Issue by ghost** [drtshock/HCFProblems#37]
Add kills to /f show

http://i.imgur.com/DIR3hr2.png 

Most HCF servers have that and it's saved flat, not MYSQL.

**Comment by nsporillo** [comment]
If total kills were added, it would be saved in the factions.json, not flat or mysql. 

Going to set this as enchantment and waiting. I can only provide issue support and critical fixes as i'm away from home for the weekend. Thank you for the report.

**Comment by nsporillo** [comment]
Should HCF care about who made the kills, or just keep a simple kill counter?

**Comment by Surgatations** [comment]
Just a kill counter, so if Bob had 1 kill, and Jack had 3 kills it would show 4 kills in /f show or were ever he has it configed to :+1:

**Comment by drtshock** [comment]
We aren't a kill tracking plugin.

**Comment by nsporillo** [comment]
We'll investigate a way to add this in.

**Comment by MoeXIV** [comment]
@drtshock The more the better?

**Comment by TMNetwork** [comment]
I agree.

**Comment by Quizzes** [comment]
BUMP: Didn't want this thread to get closed due to inactivity, here is just some text to keep this alive.
Hope to see this added very very soon!

**Comment by ArchDaWiz** [comment]
:+1: @nsporillo I think this should also be added.

**Comment by KriticalPvP** [comment]
Vouch +1

**Comment by Lilmac12312** [comment]
:+1:

**Comment by drtshock** [comment]
Notice "on hold". Please stop bumping tickets.

**Comment by TemptingMC** [comment]
@drtshock can we remove the hold on this now that I'm back?

**Comment by TheS7W** [comment]
Note: That server is parapots, which have HCTeams' plugins. They are getting sued in the summer by John.

**Comment by HeyImYellow** [comment]
Woah really?

How much for?, or is that unknown :o

**Comment by Lilmac12312** [comment]
@HeyImYellow HCTeam's plugin is all over but ParaPots happens to be one of the servers using their code therefor it's illegal and Jon is taking action be sending a lawsuit etc.

**Comment by HeyImYellow** [comment]
Wait so ParaPots stole HCTeams plugins and is now using them?

Or have they just copied their style such as the:

Leafy[4] was slain by itsjhalt[2].

-----------------------------------------------
Para - [1/1] - HQ: Cords, Cords
Faction Leader: Leafy
Faction Officers: 
Online Members:
Faction Bank: 
-----------------------------------------------


And stuff? Or their initial plugins?

**Comment by Lilmac12312** [comment]
@HeyImYellow They stole their code, did I not make it sound simple enough to understand?

**Comment by HeyImYellow** [comment]
Sorry was just curious xD

**Comment by SaiCoFlu** [comment]
@TheS7W He can't, he already tried before and the reason he can't is because he used bukkit code meaning he'd be suing someone for a part of code which doesn't belong to him which belongs to Bukkit.

**Comment by TheS7W** [comment]
@SaiCoFlu I don't think you realise, his code is copyrighted under FrozenOrb. Therefore no one has permission to use it unless John gives them permission. When PlasmaHCF opened we bought the HCTeams plugin for a lot of money (not saying). ParaPots, did not buy this. They're developers ripped off the leaked version.

**Comment by drtshock** [comment]
@TheS7W Funny how you're talking about all this redistributing plugins thing when you did it with my plugin. Get off my issue tracker.

As for everyone else, keep the issue tracker to discussion of THIS plugin.
