### ISSUE TITLE
HCFactions is not compatible with ScoreBoard Plugins

### ISSUE THREAD

**Issue by Juanoo** [drtshock/HCFProblems#370]
I have big problems with Scoreboard plugins!
My scoreboard plugin shows combattag timer, enderpearl, and koth timer

The scoreboard is not showing if HCFactions is in my plugins folder, if i delete HCF, scoreboard works

What can i do?

**Comment by drtshock** [comment]
You can disable the scoreboard in the config.yml

**Comment by zBombard** [comment]
How? How can i disable scoreboard?I don't where can I disable it

**Comment by drtshock** [comment]
in the config.yml
