### ISSUE TITLE
FancyMessage commands show up as chat messages when allowNoSlashCommand is set to false

### ISSUE THREAD

**Issue by gsand** [drtshock/HCFProblems#372]
This Ooopsie only appears in HCFactions as FactionsUUID has the correct function format.
`"blahblah.command("/" + Conf.baseCommandAliases.get(0) + " kick " + s)"`
https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/cmd/CmdKick.java#L40

**Comment by nsporillo** [comment]
Thanks for the issue, this was fixed back in September upstream and wasn't added here yet. 

Pulled the fixes thanks to @cnr

**Comment by gsand** [comment]
@nsporillo 

I don't mean to be *that guy*, but the clickable message for /f invite wasn't updated.

:stuck_out_tongue: :stuck_out_tongue: :stuck_out_tongue: :stuck_out_tongue:
