### ISSUE TITLE
[Config.Json]

### ISSUE THREAD

**Issue by ItzWid13** [drtshock/HCFProblems#376]
So, I can't modify the conf.json (  "chatTagFormat": "[%s]",) cause I need to put it like this: §7[%s§7]
The problem is that in minecraft ingame i cannot put this character: §

**Comment by drtshock** [comment]
what

**Comment by ItzWid13** [comment]
I need this:  "chatTagFormat": "§7[%s§7]"
 /f config chatTagFormat §7[%s§7] 

but in minecraft you cant put this character § (you can only put &)

**Comment by drtshock** [comment]
You need a chat plugin.
