### ISSUE TITLE
Error on PlayerQuitEvent

### ISSUE THREAD

**Issue by Manehh** [drtshock/HCFProblems#377]
I keep getting an error when a player gets banned by my DeathBan plugin

http://hastebin.com/kexawegafo.avrasm

The DeathBan plugin bans the player when the click the respawn button if that helps

**Comment by nsporillo** [comment]
It looks like the plugin you're using is causing the player to be null when HCF doesn't expect it to be, so if that is the case then I can add some null checks to fix the issue.

**Comment by nsporillo** [comment]
The fix should be in build 69 on the CI. Let me know how it works for you, as I can't really test it under your unique conditions.

**Comment by Manehh** [comment]
sorry for the late reply but this issue has not been fixed for me. I'm willing to send the the DeathBan plugin so you can fix the issue easier. It's up to you

**Comment by nsporillo** [comment]
@Manehh what is the error you're getting with build 69 and up?

**Comment by Manehh** [comment]
The same error as in the OP 
http://hastebin.com/kexawegafo.avrasm

**Comment by nsporillo** [comment]
@Manehh no, the logout method was removed in build 69 so it's not possible to have the same stack trace. Need the latest error.

**Comment by nsporillo** [comment]
Also need to know what version of Bukkit / Spigot / Paperspigot / etc you're trying this on.

**Comment by Manehh** [comment]
This is the error I get on build #70 http://hastebin.com/ukanaqeyis.avrasm

I'm using: PaperSpigot-4b7fb38 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by nsporillo** [comment]
Feel free to link the deathban plugin too. From the stack trace can't really see what the issue is, except that it is definitely different than the original.

**Comment by Manehh** [comment]
What is your skype so i can send it. don't wanna release it publicly

**Comment by nsporillo** [comment]
milky-wayz
