### ISSUE TITLE
LWC or Any Chest Locking Integration

### ISSUE THREAD

**Issue by Malvagio87** [drtshock/HCFProblems#381]
Is there a way to integrate LWC or another Chest Locking plugin into HCF so that when a Factions DTR is less than 0 it unlocks the chests?  Also if land is claimed it would unlock chests as well?

**Comment by nsporillo** [comment]
There is no existing way to do this in the plugin right now. 

However, it's an interesting idea and I may write a separate plugin that hooks into LWC and HCF to accomplish this and include it as a free download with purchase of HCF.

**Comment by Malvagio87** [comment]
I posted on the spigot forums looking for a dev to build this plug-in for me. If you have the time I would gladly pay you to make the plug-in and would not mind if you offered it for free after the fact.

**Comment by nsporillo** [comment]
@Malvagio87 sure, I'm working on it now. Should have something by the end of today, just need to do some testing but also want to get some more sleep at some point.

**Comment by Malvagio87** [comment]
@nsporillo  I added you on skype if that is ok

**Comment by nsporillo** [comment]
Functionality was added as a separate resource here:
https://mcexchange.org/resources/hclocks.28/
