### ISSUE TITLE
Help with faction prefixes.

### ISSUE THREAD

**Issue by PatManGames** [drtshock/HCFProblems#383]
I need help making these faction prefixes work. I want it to show the prefix for my faction in green like this https://gyazo.com/72373c5b097664d40d6a7dded6086721 
But instead it shows my faction, as well as all other factions like this https://gyazo.com/134a79094448f7b99f2c92f336fa2715
My faction tag should be green and all other faction tags should be yellow. What am I doing wrong here. https://gist.github.com/PatManGames/cc9dc3271e3a2ea12571

**Comment by nsporillo** [comment]
Your issue is here: `"chatTagFormat": "Â§6[Â§e%sÂ§6]",`

The &6 color code corresponds to gold. Change it to green and you should be good.

**Comment by PatManGames** [comment]
That makes every faction tag green to me. I want it so that every enemy faction looks yellow, except for my own faction which should look green. I also need it to be in brackets.
My faction: &6[&2MyFaction&6]
Other/enemy Factions: &6[&eFaction&6]
