### ISSUE TITLE
Disband Faction and Unclaim Land after a period of time?

### ISSUE THREAD

**Issue by Malvagio87** [drtshock/HCFProblems#385]
Is this possible?

Due to other additions I had requested such as HCLocks having inactive factions disbanded and there land unclaimed after a configurable amount of time would be nice.  

It would give incentives to players to keep playing on the server and allow current players to raid the bases of players that quit.

Just a suggestion.

**Comment by nsporillo** [comment]
Yes, go into the conf.json

    autoLeaveAfterDaysOfInactivity
