### ISSUE TITLE
Request: /f stuck

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#39]
Since you cannot teleport while an enemy is within 32 blocks of you, /f stuck would allow you to teleport out. However you would have to say still a minute without moving or pvping of course. And after that minute is up you'd be taken to your /f home/

**Comment by MoeXIV** [comment]
I too would like this. ^.^

**Comment by mbax** [comment]
A full minute without... moving? That sounds like a rather painful minute.

**Comment by Doxify** [comment]
It's better than being stuck in a trap which you cannot get out of forever.

**Comment by MoeXIV** [comment]
It's usually 5 minutes. It should be configurable.

**Comment by Doxify** [comment]
any updates on this being added?

**Comment by Surgatations** [comment]
:+1: Would be a nice feature, like @MoeXIV said, it should be configurable.

**Comment by nsporillo** [comment]
@Doxify @Surgatations since this seems like it'd be a nice addition, it's something i'll shift my focus to in the next few days.

**Comment by Surgatations** [comment]
TIP: /f stuck is basicly a command that allows users to teleport out of traps so admins don't have to do it, when a user types /f stuck it teleports them 5-10 blocks away from were there standing to a safe location in that radius (Should be configurable as well). So lets say bob is stuck in a hole in someones land, he types /f stuck and waits the configured time and then gets teleported to a safe location around the spot he typed /f stuck.

**Comment by mbax** [comment]
You should define what "wait" means in this context. Do they have to stay completely still? Not use the WASD keys? Not move the mouse? Stick to a small (1 block? 2x2 block?) radius?

**Comment by Surgatations** [comment]
No, they are allowed to move around (usually 10x10 area) and they can't take damage or the /f stuck teleportation gets canceled.

**Comment by MoeXIV** [comment]
@NauruMC No offense, but that's a horrible idea. I like the part in which it teleport you to a safe-ish spot of where you're standing, but it's hella hard to accomplish that. How will the plugin know what is safe or not land? Maybe teleporting them to the nearest wilderness claim ^.^

P.S, I think they shouldn't move or be in combat at all, despite the moving of the mouse. That seems like a reasonable result of this.

**Comment by NauruMC** [comment]
Pushed to build #25 on the CI.
