### ISSUE TITLE
How to disable claiming in certain worlds

### ISSUE THREAD

**Issue by ImRealsy** [drtshock/HCFProblems#390]
Hello, 
So I have recently brought your Hc factions plugin and I need a bit of help with something. I want to disable claiming in the nether and in the end so people can only claim in the overworld, I found the option to do so in the conf.json but when I can't seem to get it to work

  "bankEnabled": true,
  "bankMembersCanWithdraw": false,
  "bankFactionPaysCosts": true,
  "bankFactionPaysLandCosts": true,
  "playersWhoBypassAllProtection": [],
  "worldsNoClaiming": [],
  "worldsNoDtrLoss": [],
  "worldsIgnorePvP": [],
  "worldsNoWildernessProtection": [],
  "backEnd": "JSON"

How to I add the world factions2_nether and factions2_the_end to "worldsnoclaiming". [],

thanks and I hope you can help

**Comment by nsporillo** [comment]
Try adding the worldnames between the [] separated by commas.

[factions2_nether, factions2_the_end]

**Comment by ImRealsy** [comment]
I have just tried, when I do /f reload it turns it into conf.json_bad

**Comment by nsporillo** [comment]
"worldsNoClaiming": ["factions2_nether", "factions2_the_end"]

Sorry, use double quotes.

**Comment by ImRealsy** [comment]
still doesn't work :/

**Comment by nsporillo** [comment]
Post your conf.json into a gist and link here.

**Comment by ImRealsy** [comment]
https://gist.github.com/ImRealsy/1c6ebcd33fd200951cac

**Comment by nsporillo** [comment]
You're missing a comma at the end of that line, but I guess that may have been my fault.

In the future, run JSON through a validator if you aren't sure if theres a formatting error. 

https://gist.github.com/nsporillo/6fa0b69402f3fb7b2441

**Comment by ImRealsy** [comment]
Thank you for the support man 10/10, It finally worked :)

**Comment by nsporillo** [comment]
No problem
