### ISSUE TITLE
DTR Loss Options

### ISSUE THREAD

**Issue by Malvagio87** [drtshock/HCFProblems#395]
Is there or can there be a way to set different values for DTR loss when the player dies due to PvE or PvP

For instance if the player dies in PvP the DTR loss is 5 but if the player dies to a creeper the DTR loss is 1?

**Comment by MoeXIV** [comment]
What's kind of hard to judge. Let's say I'm being killed, what's stopping me from jumping off a wall and losing 1 DTR then fighting and losing all 5?

**Comment by Malvagio87** [comment]
Maybe hook into a combat tag plugin so if you are combat tagged you cant do that

OR

Make it a radius based thing where if you die due to PvE within X amount of blocks of an enemy player, you still get charged the full amount.

**Comment by nsporillo** [comment]
This is out of the scope for this HCF plugin.
