### ISSUE TITLE
Freeze when f show

### ISSUE THREAD

**Issue by williambraecky** [drtshock/HCFProblems#396]
Hello, so recently my server was getting really big freezes, after some testing with whitelist on, i saw that f show with a lot of players offline makes the server freeze. (when showing offline players in the f show)

**Comment by drtshock** [comment]
Can you provide timings, version info for spigot and for factions

**Comment by williambraecky** [comment]
Timings will take a time, for now i disabled online players in f show, i'm using a custom version of paperspigot, and the latest version of hcfactions, i'm hosting my server on a dedicated server with ssd's so it shouldn't be that, and i think players where abusing the f show to make my server lag.
By the way, i had this issue for 2 or 3 days and my timings where not showing anything on the command:factions so timings might be inaccurate but i'm 100% sure it was f show.

Can it come from the fact that i'm using mysql to store groups data and that for some reason it needs to load permissions on them ? Thanks.

**Comment by drtshock** [comment]
If your permission plugin queries mysql each time it's asked for a player's group then yes, that'd be an issue. Which permissions plugin are you using?

**Comment by williambraecky** [comment]
I'm using permissionsEx with sexypex premium addon for group sync

**Comment by williambraecky** [comment]
Closing this issue since it doesn't come from the plugin itself.
Thanks.
