### ISSUE TITLE
neutral color

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#40]
I set the neutral color to red and people without a faction are still white. Please help?

**Comment by TMNetwork** [comment]
Example:
The kid in the white doesn't have a fac and nor do I so we see each other as white. Can we make that default color red? That's how HCF works.

**Comment by nsporillo** [comment]
Very similar to https://github.com/drtshock/HCFProblems/issues/17 , you are correct in saying that HCF should still color names of factionless players.

**Comment by MoeXIV** [comment]
When do you think this could be complete?

**Comment by nsporillo** [comment]
I'm looking into it now, so a reasonable timeline estimate would be 20 minutes or up to tomorrow.
