### ISSUE TITLE
Problem with HCFEssentials Scoreboard

### ISSUE THREAD

**Issue by zBombard** [drtshock/HCFProblems#401]
Hello, I have these 2 plugins: drtshock factions and itzmonkey HCFE.
Then the problem is:
I disabled scoreboard like this http://pastebin.com/MKcLXGRq
But the HCFEssentials's scoreboard don't come out

Pls help me.

**Comment by ItsMonkeyyy** [comment]
You wouldn't be having this problem if you bought the plugin and not download the leaked version.

**Comment by drtshock** [comment]
rekt

**Comment by zBombard** [comment]
No problem just modify it :)
