### ISSUE TITLE
HCFactions - DTR Not showing in /f show

### ISSUE THREAD

**Issue by BelongoTheBelog** [drtshock/HCFProblems#409]
HCFactions DTR No working, you've people over and over again you would fix it.
![image](https://cloud.githubusercontent.com/assets/17752560/13652339/d8724fc6-e608-11e5-9b0a-4265419c5bdb.png)
![image](https://cloud.githubusercontent.com/assets/17752560/13652742/22bdfccc-e60b-11e5-9ffc-f05271e2b04d.png)

**Comment by drtshock** [comment]
You need to get HCFactions, not regular factionsuuid.

**Comment by BelongoTheBelog** [comment]
I have HCFactions

**Comment by BelongoTheBelog** [comment]
![image](https://cloud.githubusercontent.com/assets/17752560/13653198/6dd8908a-e60d-11e5-9077-d35189dcfaa3.png)

**Comment by drtshock** [comment]
Then you're doing something wrong. Let the config regenerate. 

Also note that it's no longer supported.
