### ISSUE TITLE
people type "f home" in chat and get teleported home even in combat

### ISSUE THREAD

**Issue by ImRealsy** [drtshock/HCFProblems#410]
ok so when people try do /f home in enemy territory or whilst in combat it doesn't allow them, But whenever they type just f home in chat they can bypass the the pvp timer and teleport home, please help people are getting out of others traps and abusing this like crazy,

Thanks

**Comment by ReeceZ** [comment]
Just disable it in the config.

**Comment by ImRealsy** [comment]
where?

**Comment by drtshock** [comment]
conf.json
