### ISSUE TITLE
Lost access to Jenkins

### ISSUE THREAD

**Issue by Lotteries** [drtshock/HCFProblems#413]
Hi, I've recently came back from a long break.

I've forgot all info to my account on the CI (email, and password) but I still know the username and full name on the account (if that can help you recover it), could drtshock or Nick help me please? :)

Thanks, feels good to be back.

**Comment by Lilmac12312** [comment]
I've lost mine too lmao

**Comment by drtshock** [comment]
Project has currently been discontinued. See #412.

Jenkins user database was wiped when we moved off of staminus onto a new machine.

**Comment by Lilmac12312** [comment]
Can I have access via mcexchange then? lol

**Comment by drtshock** [comment]
that site is down
