### ISSUE TITLE
30% Reduced Damage

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#42]
I'm not sure if this is an issue as I don't have the abilities to test this as of now, but on Factions if you hit an enemy in enemy territory they get 30% reduced damage. If this is still a thing with the Enemy relationship it needs to be taken out.

Sorry for not being able to clarify this, I'm trying to keep my project low key, and I have no working alts.

**Comment by nsporillo** [comment]
I only have two paid usernames, so if I need to test things with more players I had to get a cracked client and set my test server to offline. I suggest you try the same if you find you need it.

However, I just checked the event and it does not appear to modify damage dealt based on relations.

I'll set this to help wanted so others can maybe help.

**Comment by nscwalk** [comment]
Look in the default factions config and make sure the server is offline when you edit it. I don't know it by heart and I do not have access to a CPU right now but, go into the regular conf file and go down to enemy  Sheild in territory or something by default it is set to .3 set it to 0 fixes problems

**Comment by drtshock** [comment]
That hasn't been used in like... 8 months.
