### ISSUE TITLE
DTR is no longer lost on death in build 18

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#44]
Title.

Went back to 17 because it does there.

**Comment by Surgatations** [comment]
DTR Works fine in build 18, try looking over you're config.. I'll run some tests to make sure my statement is correct now.

**Comment by Doxify** [comment]
![wgruam2](https://cloud.githubusercontent.com/assets/9636316/6794243/be93fdc0-d18c-11e4-87ec-9a4e2a82dd69.png)
Look at chat, user dies and DTR is not lost. This is on build 17, for some reason I can kill my alt and they lose DTR but not other players?

**Comment by Surgatations** [comment]
Seems to work fine on my server? I could give the IP to show you?

**Comment by Surgatations** [comment]
![ba937fc48a89f8ea0ad08bd1fcf4ff6e](https://cloud.githubusercontent.com/assets/9434234/6794285/56392cfe-d1a6-11e4-957d-dd5b0d0def34.png)

**Comment by Doxify** [comment]
Yes I know this bug is VERY weird, it works perfectly with my alt on the same server, just not for the other users... ALT is not opped but I am, maybe they only lose DTR if an OP kills them? That could be why DEVS think they have fixed the problem..

**Comment by Surgatations** [comment]
If you would like to come on my server we can test it, but other wise i fail to see the problem as it works fine on my test server and my public server.

**Comment by Doxify** [comment]
My mod has a theory that DTR is only lost for new factions, or factions created after the update that fixed DTR. We tested this and it seemed to be true.

Another theory is that since each player has 1 DTR and max DTR is 5.1,  and if there's 10 people in a faction, maybe the MAX DTR is 10, but it just says 5.1 since that's the MAX in config, and when they die the DTR gets lowered to 9 but since it's greater than 5.1 it will still say 5.1.

**Comment by Surgatations** [comment]
The first theory might be true, but the second one i highly doubt is true.
At this level of confuison i can't help anymore sorry :/
Wait till @nsporillo or @drtshock has some input on this..

**Comment by Doxify** [comment]
![qngw0cp](https://cloud.githubusercontent.com/assets/9636316/6794859/11d27f40-d195-11e4-9f74-bcdcbe660523.png)

Killed everyone in this faction, DTR still 5.1

**Comment by Doxify** [comment]
On player kick, DTR is also not lost.

![pykyix1](https://cloud.githubusercontent.com/assets/9636316/6794949/59c67dbe-d196-11e4-81cc-71de34d900fa.png)

**Comment by Surgatations** [comment]
I'm in Hydra's teamspeak in support room. I'll be glad to talk and try to find the issue.
My Teamspeak name is: Nauru

**Comment by MoeXIV** [comment]
It's nothing you can help with. It's the way the DTR is stored in the newer versions then the old. My theory is that it corrupts old factions.

**Comment by Doxify** [comment]
It doesn't corrupt them, it just doesn't call for the correct event I believe. Trent is already looking into this.

**Comment by MoeXIV** [comment]
Oh, my mistake. In the update on the CI, it clearly states that it only calls a DTR change event when DYLTR is actually lost. This is most likely using a different event ^.^

Sorry for my confusion, but still not among anyone's help other then the developers themselves.
What does this mean for already created Factions?

**Comment by Doxify** [comment]
Raiding on my factions server is non-existent at this moment, hope this gets fixed fast.

**Comment by nsporillo** [comment]
![2015-03-24_10 00 06](https://cloud.githubusercontent.com/assets/1480197/6803250/b342dc40-d20c-11e4-98ff-28356f2b2dba.png)

DTR looks to be working perfectly fine in my testing. 

Will definitely be taking some time to fully flesh out issues with our current system. It works fine in testing and fine for others, but some builds don't run right according to these issues.

@MoeXIV There was no change in how things are saved. The event update was simply an additional check so we don't call a dtr change event from the dtr doesnt change (from is equal to to).

**Comment by Doxify** [comment]
Please explain why my players do not lose DTR.

Test this:

Make a faction with build 14 or whatever the build was before you changed the way it saved, then upgrade to build 18 and see if you lose DTR.

**Comment by nsporillo** [comment]
@Doxify we never changed how it was saved.

**Comment by Doxify** [comment]
Okay, I understand. Sorry about that but you guys did change something and DTR is still not being lost on death.

**Comment by nsporillo** [comment]
@Doxify Try setting a factions DTR to 5.51 exactly using /f dtr , and then see if DTR is lost on death.

If so then your previous comments are true, we know adding up all the faction members DTRs does go above the faction dtr max, and is just set back to 5.51 because that is the max. 

Going to add debug messages to these functions so users can enable debug and get important information regarding dtr changes.

**Comment by nscwalk** [comment]
Well doxify isn't the only one with this problem I am also in the same situation as him

**Comment by Doxify** [comment]
They are working on a fix, should be out soon ^
