### ISSUE TITLE
major dtr bug.

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#46]
DTR doesn't change for factions created before you guys changed the way DTR is called / stored.

**Comment by Doxify** [comment]
To add on:

DTR seems to work perfectly fine for factions that have less than 5.51 DTR as that is my max DTR. If they have less than 5.51 and die, they lose DTR however if they have 5.51 DTR they don't lose DTR on death.

**Comment by nsporillo** [comment]
@Doxify test out the latest build, try enabling the debug in config and then check out console.

![fix](https://cloud.githubusercontent.com/assets/1480197/6807190/6092985c-d223-11e4-9740-2505e6121627.png)

This was the fix. It keeps the DTR for individual players from ever going above the max. Before it could, but only by the DTR regeneration- it was not constrained and thus went above the max and caused your issues.

Please let me know if you continue to have problems, luckily with debug messages you can see what is happening behind the scenes :smile:

**Comment by Doxify** [comment]
I will try this when I get home in a couple hours.
