### ISSUE TITLE
Request: Max Allys and Set Allys

### ISSUE THREAD

**Issue by Surgatations** [drtshock/HCFProblems#47]
Basically, what i want is 2 variables that can show the number of allies a faction has currently set, and the max allies specified in the config's max relation areas.

Example (A line in /f show): Allys (0/2): AllyFacName1, AllyFacName2 etc..

**Comment by MoeXIV** [comment]
So say I had 1 ally of 2 it would say:

Allies (1/2): Test

**Comment by Surgatations** [comment]
Yes, this feature would be a nice thing to have added just because most pepole don't understand that you can only have 2 allies on most HCF servers.

**Comment by nsporillo** [comment]
I like this request, will work on this soon.

**Comment by MoeXIV** [comment]
Sounds good, Nick. Looking forward to it.

Cheers ~

**Comment by Surgatations** [comment]
Good to see the waiting tag :+1: My players will enjoy this, this should help the new HCF players :)

**Comment by nsporillo** [comment]
With max relations off: 
![ex2](https://cloud.githubusercontent.com/assets/1480197/6808928/68d35d12-d22d-11e4-8fcd-91641f0de84e.png)
With max relations on and allies set to 2:
![ex1](https://cloud.githubusercontent.com/assets/1480197/6808939/784581f8-d22d-11e4-8a95-b8e2610f6a2f.png)

The same was added for enemies, just to be consistent. Try build 20 for these.

**Comment by nsporillo** [comment]
Variables:
# {alliescount} - # of allies faction has. {maxenemies} - max # of enemies faction can have. 
# {maxallies} - max # of allies faction can have. {enemiescount} - how many enemies faction has.

If you set any value to -1, it will disable a max relation and show the GENERIC_INFINITY lang as the max. If you don't have max relations, it will also show the GENERIC_INFINITY lang message.

**Comment by Surgatations** [comment]
Woah, that was a speedy build! Great feature! :+1: $30 was worth it
