### ISSUE TITLE
Color tags/variables won't work on Allies line.

### ISSUE THREAD

**Issue by Surgatations** [drtshock/HCFProblems#49]
^ Title explains it all. Here is a screenshot.
![31ea1125f08a60c13e280dfc67b6a3fb](https://cloud.githubusercontent.com/assets/9434234/6809444/bb5c1a58-d230-11e4-8844-c2abafb84363.png)

**Comment by nsporillo** [comment]
This is an issue with fancy messages (the tooltip stuff).

Working on a fix right now, sorry for that :person_frowning:

**Comment by Surgatations** [comment]
Thank you, also Build #20 was very helpful :) :+1:

**Comment by Surgatations** [comment]
EDIT: Also, it's not just the Allies line, Its everyline below the Allies & Enemies line

**Comment by nsporillo** [comment]
Yeah, I'm working on a way to allow color coding with tags to work with the fancy messages. 

Build 20 and below, tags are not parsed (so they arent converted to color) and then we've just applied the gold to it hardcoded. This is definitely an issue.

**Comment by Surgatations** [comment]
Do you have a ETA on when you might be done?

**Comment by nsporillo** [comment]
10 minutes, looks like I already have it fixed.

I've been trying to product higher quality commits and thus better builds, but theres just a lot to test and I'm not neglecting testing. It's just shortsightedness at the time of implementation.

The fix will allow color tags on allies, enemies, online, offline (those with fancy messages for tooltips)

**Comment by Surgatations** [comment]
Sweet! Looking forward to this!
