### ISSUE TITLE
Resource Removed

### ISSUE THREAD

**Issue by drtshock** [drtshock/HCFProblems#5]
The resource was approved and then deleted by md5 later. I'm working on figuring out a new, viable option to sell it. If you purchased it and didn't download, contact me on skype.

**Comment by SnakeDaoust1232** [comment]
md5 removed it. wtf why

**Comment by SnakeDaoust1232** [comment]
Make a website just for your plugins. Link people your website on the factions uuid page.

**Comment by drtshock** [comment]
I'm working on a solution

**Comment by drtshock** [comment]
Working on a new panel. Will hopefully have something up and running soon. Not sure on an extra ETA.

**Comment by drtshock** [comment]
See https://gist.github.com/drtshock/d3105986088775fc6c20 for now
