### ISSUE TITLE
deaths till raidable tag

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#50]
I think it'd be cool if we had a new variable added called {deathsTillRaidable} and it would display how many times faction members have to die before their faction goes raidable. It would also update as someone dies.

**Comment by Surgatations** [comment]
Doxify, that's what DTR is, if you config it how it was on Kohi, it would be helpful :P

**Comment by Doxify** [comment]
no, I want it like this.

http://i.imgur.com/DIR3hr2.png

Look at the bottom.

**Comment by Surgatations** [comment]
Contact me on skype, i can do this already in the config

**Comment by KriticalPvP** [comment]
@Quizzes what is your skype? I am also looking to get this done! :P

**Comment by drtshock** [comment]
STOP BUMPING ISSUES FFS
