### ISSUE TITLE
Factionless Symbol Broken

### ISSUE THREAD

**Issue by NauruMC** [drtshock/HCFProblems#51]
^ Title explains it all, i'm using the latest build and it just shows the boxes and not a symbol, do i have to config it or is it default?

![7f1e835d1c4fca8a97ffc49fe9d2b90e](https://cloud.githubusercontent.com/assets/9434234/6811953/09bf1e82-d242-11e4-90db-e22a1ca37e0e.png)

On most HCF Servers (Not all but most) there is a symbol for factionless members, usually it is a -
I don't know if i looked over the config or it is broken..

**Comment by nsporillo** [comment]
This is similar to #17, a symbol for factionless members is a feature i'll be working on soon.

**Comment by Surgatations** [comment]
It was said to be added in a update on the CI though?

**Comment by nsporillo** [comment]
@Surgatations those dealt with scoreboards, not chat

**Comment by Surgatations** [comment]
ahh.. lol.. silly me.. ^.^
