### ISSUE TITLE
Allies color is white in /f show

### ISSUE THREAD

**Issue by clerkk** [drtshock/HCFProblems#52]
![ugvhp9y](https://cloud.githubusercontent.com/assets/11637343/6812398/859db2b0-d266-11e4-85fb-77e557b9c75a.png)
What title is.

**Comment by Surgatations** [comment]
New update, use this as you're config.

  - '<a>Allies (<i>{alliescount}<a>/<i>2<a>): {allies} '
  - '<a>Members online: {online}'
  - '<a>Members offline: {offline}'

In you're config.yml under f show config area :)

**Comment by Surgatations** [comment]
You have to add the color codes, in config.yml.
Color codes are listed below..
<a> = Gold
<i> = Yellow

**Comment by Surgatations** [comment]
If you config it correctly it should look somthing like this..

![f7c195e885ae5d3a170ad77ec5d2e34b](https://cloud.githubusercontent.com/assets/9434234/6812685/c5418c4a-d246-11e4-99c3-0a16db70f37a.png)
