### ISSUE TITLE
REQUEST: Default faction home message

### ISSUE THREAD

**Issue by Surgatations** [drtshock/HCFProblems#53]
Basicly, if a faction does not have there faction home set, instead of showing just nothing it will say something along the lines of Faction Home: Currently not set.. (It should be configurable) The blank line looks sloppy in my opinion Here is a example from another HCFactions server..

![d0c7491a38ba25c7871b4d85ec4c14dc](https://cloud.githubusercontent.com/assets/9434234/6813883/bf7701c4-d24f-11e4-8cc7-a02e267b26d7.png)

**Comment by nsporillo** [comment]
![lang](http://puu.sh/gOeo1/461597bd40.png)

Line 408 should be where you can configure this.

**Comment by Surgatations** [comment]
Sweet, thanks. lang.yml correct?
