### ISSUE TITLE
Faction un-set message

### ISSUE THREAD

**Issue by NauruMC** [drtshock/HCFProblems#54]
I changed the no faction home message on line 408 of the lang.yml config. I saved the file and restarted my server, and i still have a blank line as shown here. In the config it already default had 'Not set' in the language file but failed to show up..
![b02ba0c70973f70215234fb5c9ef5d73](https://cloud.githubusercontent.com/assets/9434234/6814371/680ee550-d254-11e4-9da2-06d81298f3e5.png)

**Comment by MoeXIV** [comment]
I found this hard to understand coming from what you said. What I'm inferring is that when you see the "Faction Home" with no coordinates, if there is no home set, make it say "Not set"  instead of it being blank

**Comment by Surgatations** [comment]
Yes, @nsporillo told me how to edit this. But the config failed to make the text show up. This was another issue to ask him if its a bug or if i did somthing wrong.

**Comment by nsporillo** [comment]
@Surgatations 

In your config.yml, make sure you leave:

    - '<a>Faction Home: <i>{world}, {x}, {y}, {z}'

At least leave {world}, as it is replaced with the message from the lang file.

            if (faction.hasHome()) {
                Location home = faction.getHome();
                raw = raw.replace("{world}", home.getWorld().getName());
                raw = raw.replace("{x}", String.valueOf(home.getBlockX()));
                raw = raw.replace("{y}", String.valueOf(home.getBlockY()));
                raw = raw.replace("{z}", String.valueOf(home.getBlockZ()));
            } else {
                // if no home exists, use home unset tl for "not set"
                raw = raw.replace("{world},", TL.COMMAND_SHOW_HOME_UNSET.toString()).replace("{x},", "").replace("{y},", "").replace("{z}", "");
            }

The x, y, z can be removed, but you can see that {world} is replaced with "Not set", and then the x,y,z are just replaced with nothing. This is done to allow us to use the same line in the fshow list for faction home.

**Comment by Surgatations** [comment]
But i don't want the {world} tag to show what world it is in, because you can only claim in the Overworld which makes it very obvious, i think the world name is just more clutter, :/

**Comment by Surgatations** [comment]
This is what i get.
![d4992b82006cbbdc1d1b5851f3c5e9bd](https://cloud.githubusercontent.com/assets/9434234/6816375/d460fcfc-d268-11e4-92fa-81151d76b831.png)

**Comment by nsporillo** [comment]
@Surgatations I'm home now and have a chance to investigate if something is wrong or not.

**Comment by Surgatations** [comment]
Okay, that would be great :)

**Comment by nsporillo** [comment]
@Surgatations Thinking about just not showing anything if the faction home is not set otherwise it's going to take two different lines in fshow. One for set and one for unset and it seems a bit unnecessary at that point. 

A minimalist approach to f show (only show what you need to) seems like the best way to approach this issue. If we get requests in the future which ask for it back I guess I'd have to revisit and see what we could do.

**Comment by MoeXIV** [comment]
@nsporillo or...
You could add a variable that gets replaced by ' ', a space when you have your home set, and when it's not set, the variable says "Not set". Not sure how one would accomplish this, but it seems like a reasonable idea.

**Comment by nsporillo** [comment]
This was added.
