### ISSUE TITLE
Version command..

### ISSUE THREAD

**Issue by NauruMC** [drtshock/HCFProblems#55]
This is just a suggestion, basically the current /f version sates useful
 info, but you should make the default /f version something along the lines like this screenshot, this should help server owners quickly find out what build of the plugin they are on! (I changed the lang.yml for this example)

![5c9b6f76ce1f7d9a62c8a18da0e79de4](https://cloud.githubusercontent.com/assets/9434234/6815316/a2903652-d25e-11e4-87b1-edbc0665dc69.png)

Then change the build number every time a new build is posted. This is just my idea and i think it would help me a lot when i'm trying to fix bugs etc..

**Comment by nsporillo** [comment]
This is a legitimate issue and would like to see this myself. :+1:

**Comment by Surgatations** [comment]
Oh wow, didn't expect that lol. :+1:  I like this :)

**Comment by nsporillo** [comment]
Added as of Build [#22](https://ci.drtshock.net/job/HCFactions/22/) and up!

Thanks :smile:

**Comment by NauruMC** [comment]
No problem :+1:

**Comment by MoeXIV** [comment]
Yas
