### ISSUE TITLE
Tab doesn't update when you leave a faction

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#56]
![fafjqvj](https://cloud.githubusercontent.com/assets/9636316/6816119/1d52aea0-d24c-11e4-9296-7738572f668c.jpg)

**Comment by nsporillo** [comment]
Try re-logging, but there is some lingering annoyances with the way scoreboards are handled since it was updated to support faction-less players formatting. 

This is a problem, things should work seamlessly. Similar to https://github.com/drtshock/HCFProblems/issues/48

**Comment by MoeXIV** [comment]
@nsporillo will it be fixed, or is it just a bug that's not really an issue as of now.
