### ISSUE TITLE
/f thaw Error

### ISSUE THREAD

**Issue by NauruMC** [drtshock/HCFProblems#57]
^ Title explains it, here is a example on build #23 when i type /f thaw

![835abe1465319a23a146bee31e8bdf29](https://cloud.githubusercontent.com/assets/9434234/6831064/6cd81e9e-d2f4-11e4-82ca-713a50b65e65.gif)

**Comment by nsporillo** [comment]
Can you send the stacktrace? 

/f thaw should thaw your faction. /f thaw tag would thaw the faction named 'tag'.

**Comment by NauruMC** [comment]
'stacktrace' english please, would could i find this?
:P

**Comment by NauruMC** [comment]
EDIT: Oh, i see the issue. I get the error because i was not on DTR Freeze, you should add a message saying that.. :P

**Comment by nsporillo** [comment]
COMMAND_THAW_NOTFROZEN("<a>%s <b>is not frozen!"),

In CmdThaw: 

    if(!faction.isFrozen()) {
        msg(TL.COMMAND_THAW_NOTFROZEN.toString());
        return;
    }

If you have the stacktrace, I can figure out why this is happening despite the check.
