### ISSUE TITLE
dtr not updating?

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#58]
I was aware that this was a bug, but is it still a bug in the newest build?

**Comment by nsporillo** [comment]
I've noticed that DTR sometimes doesn't update temporarily, and then shortly after will start updating normally.

**Comment by Doxify** [comment]
No, it's not temp, I had to manually give them the DTR.

**Comment by NauruMC** [comment]
As @nsporillo said, it's temp. I've seen the same issue. There are many events that can cause a DTR update.

**Comment by nsporillo** [comment]
Should be fixed as of build 27 and up.
