### ISSUE TITLE
console gets spammed with errors

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#59]
![gk48snw](https://cloud.githubusercontent.com/assets/9636316/6837633/e6d55a92-d30b-11e4-8b2e-c4d6ea958235.png)

**Comment by NauruMC** [comment]
Can i please see you're debug? Go to config.yml and enable debug. It looks like a different plugin is causing it, i'm not so sure. If i could see the debug i could see if DTR updates is causing the spam

**Comment by NauruMC** [comment]
@nsporillo will need to put some input on this, as far as i can see i fail to see the source of the error.
