### ISSUE TITLE
DTR GOES OVER THE MAX DTR IN V0.03 SNAPSHOT

### ISSUE THREAD

**Issue by nscwalk** [drtshock/HCFProblems#6]
here is a picture of it 
![bandicam 2015-03-07 11-05-01-068](https://cloud.githubusercontent.com/assets/10702752/6542798/e8554072-c4b9-11e4-9333-5dadb0d815c8.jpg)

**Comment by drtshock** [comment]
jeez calm down. @nsporillo will take a look when he gets online.

**Comment by nsporillo** [comment]
This issue was already fixed, but did exist in older versions, yes.

Sorry about that!

**Comment by nscwalk** [comment]
Sorry for caps ,but is it fixed now???

**Comment by nscwalk** [comment]
In a newer version??

**Comment by nsporillo** [comment]
@nscwalk yes, it was actually already fixed when I was working on the fshow features.

**Comment by nscwalk** [comment]
Oh so all I will have to do is talk to Trent over Skype for the new version I guess?

**Comment by nscwalk** [comment]
Cause I'm using the 0.0.3 - SNAPSHOT ver

**Comment by nsporillo** [comment]
He's working to restore our dev builds, the CI has been having issues.

**Comment by nscwalk** [comment]
How do I get acces to the CI

**Comment by nsporillo** [comment]
https://ci.drtshock.net/job/HCFactions/

If you don't have access, contact @drtshock 

The latest build is not up there yet, we still need to fix the what is making the last few builds fail, set version to v0.0.4 and then that should be a good download.

Thank you for your patience.

**Comment by nscwalk** [comment]
Link is broken
