### ISSUE TITLE
Allies

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#60]
In HCF, your suppose to be able to hit allies.

**Comment by NauruMC** [comment]
Thats incorrect, that was disabled soon after Map #16 on Kohi.
I may be wrong so don't be mad if i'm wrong but i think i'm correct..

**Comment by MoeXIV** [comment]
No, on HCF you're meant to hit allies, but a message comes back to you saying "Be carful, that's your ally: **MoeXIV"

**Comment by nsporillo** [comment]
@MoeXIV does it deal damage?

Are you allowed to kill allies?

**Comment by MoeXIV** [comment]
@nsporillo Yes. You just get the message I said above.

**Comment by nsporillo** [comment]
@MoeXIV and when you kill allies, they lose dtr too? So what is the point of being allies if it doesn't mean anything

**Comment by MoeXIV** [comment]
The point of being allies is a mutual truce. "Don't kill allies".

On Kohi youre able to hit them to make it more "Hardcore".

**Comment by nsporillo** [comment]
Going to make this configurable somewhere.

**Comment by Doxify** [comment]
please don't make it default though.

**Comment by TMNetwork** [comment]
Thank you. Please make it config.

**Comment by TMNetwork** [comment]
is this fixed @nsporillo ?

**Comment by nsporillo** [comment]
@TMNetwork If an issue is closed, it's been resolved.

That being said, check the CI for the latest build and you can even click on the commits to see what changed since last build

In short, yes.
