### ISSUE TITLE
Solo Fac

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#61]
Solo factions should have 1.01 max DTR so they don't go raidable on first time death.

**Comment by NauruMC** [comment]
That can be done in the config, please look around before you post.

**Comment by TMNetwork** [comment]
@NauruMC no, i dont wanna set the DTR per player to 1.01, the DTR per player is .51

**Comment by NauruMC** [comment]
Not everyone likes this, @nsporillo is giving everyone the same thing. He won't just make it special for you.

**Comment by nsporillo** [comment]
@TMNetwork it's sort of an incentive to not have a solo faction, if you think about it. Gives players a reason to band together (maybe invite their friends...?) 

If you're still looking to have this added, reply to this issue with some more reasoning as to why we should clutter config with another variable for a single case (solo factions). I understand they shouldn't be really raidable after just one death, but it is "Hardcore Factions". 

For now I will close, but if you really want this added please provide some more details on how this would be a good addition into HCF as a whole.

**Comment by TMNetwork** [comment]
This is on all hcf servers. Tons of YouTubers do solo facs and the majority of factions on kohi and HCF are solo and active.

**Comment by NauruMC** [comment]
EDIT: This is not on all HCF servers.. Kohi does not have it, HCFactions (Shotbow) does not have it, HyogenHCF does not have it.. This should also be configurable..

**Comment by TMNetwork** [comment]
@NauruMC your 100% wrong. Stop commenting on all my posts as I don't care for your support. You have no idea what ur talking about.

**Comment by Doxify** [comment]
Changing the max player dtr shouldn't be an issue.. I don't see why you don't want to change it. I allow solo factions, max player dtr is 1.51 and they lose 1.00 on death.

**Comment by nsporillo** [comment]
@Doxify @NauruMC doing that messes with a delicate ratio that is player-dtr to max-faction-dtr.

Adding this is relatively straight forward, look to see it by tonight.

**Comment by TMNetwork** [comment]
Ok, can you make it config. soon?

**Comment by TMNetwork** [comment]
@nsporillo can u please add this?
