### ISSUE TITLE
Players Online

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#62]
Do you guys have the players online support?
http://gyazo.com/24f8718dc4e54fb6c236608e6f66e2b3

Like in the new update.
I'm about to check, but if not, you should add how many people are online in the fac.

**Comment by Doxify** [comment]
There's nothing I hate more than people saying something is broken or not there without checking first.

**Comment by nsporillo** [comment]
Not currently, I just added that for allies / enemies. 

Will add the same for online / offline soon.

**Comment by TMNetwork** [comment]
@Doxify who said something is broken?

**Comment by MoeXIV** [comment]
This is already added, @nsporillo .
I have it setup on my server already. ^.^

**Comment by Doxify** [comment]
@tmnetwork that's why there's a "or" in the sentence.

**Comment by TMNetwork** [comment]
@Doxify fuck off

**Comment by Doxify** [comment]
@tmnetwork There's no need to be upset, sorry if I did anything to cause you to become angry. Have a nice day.

**Comment by TMNetwork** [comment]
Yes @nsporillo close this.

**Comment by Doxify** [comment]
Has it been resolved?? Why did you close it? Should I make a new thread?

**Comment by TMNetwork** [comment]
@Doxify it's resolved.

**Comment by Doxify** [comment]
Oh ok
