### ISSUE TITLE
Disbanding on DTR freeze

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#63]
You can disband factions in DTR freeze.

**Comment by TMNetwork** [comment]
Is this fixed? @nsporillo

**Comment by TMNetwork** [comment]
why was this closed @nsporillo ?

**Comment by lol768** [comment]
The close text states "@nsporillo nsporillo closed this in b4e85ee 22 hours ago". This indicates that a commit (a change in the code of the project) with hash starting b4e85ee triggered the close of the commit. Whilst you cannot see the code changed or the commit message (the repo is private), to me this would suggest that the code change fixed the bug in question and that is why it triggered the close of the issue.

**Comment by nsporillo** [comment]
@lol768 is exactly correct, and awesome. 

@TMNetwork this was added. Please stop asking if closed issues are complete. If it was closed then it's resolved.
