### ISSUE TITLE
/f stuck Message

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#66]
Can you make the /f stuck message configurable:
http://gyazo.com/578862bfa9808f5b357c5f1aea88964d

That looks ugly in my opinion and there is no need for seconds nor the 2 different colors of dots.

**Comment by nsporillo** [comment]
All these messages are configurable. Every command. Visit lang.yml

![](http://puu.sh/gR1QB/5fe18cece9.png)
