### ISSUE TITLE
Faction Relationship Disabled.

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#68]
When you do /f neutral {faction}
it says You can only have 0%s, can you make that configurable in lang.yml?

**Comment by nsporillo** [comment]
RELATIONS:
      ALLTHENOPE: <b>Nope! You can't.
      MORENOPE: <b>Nope! You can't declare a relation to yourself :)
      ALREADYINRELATIONSHIP: <b>You already have that relation wish set with %1$s.
      TOMARRY: to change a relation wish
      FORMARRY: for changing a relation wish
      MUTUAL: <i>Your faction is now %1$s<i> to %2$s
      PEACEFUL: <i>This will have no effect while your faction is peaceful.
      PEACEFULOTHER: <i>This will have no effect while their faction is peaceful.
      DESCRIPTION: Set relation wish to another faction
      EXCEEDS:
        MAX: <i>Failed to set relation wish. You can only have %1$d %2%s.
