### ISSUE TITLE
Pretty /f help command syntax.

### ISSUE THREAD

**Issue by NauruMC** [drtshock/HCFProblems#69]
Recently I've noticed how dull the /f help is, that's the same f help we have had for 3-4 years pretty much, I've transitioned over from a different DTR plugin to here just because this one had more customization features to it, here is a example of a /f help i PERSONALLY  enjoy. 
![1dd890e4dbdb0b52bbb611fd1097bcb5](https://cloud.githubusercontent.com/assets/9434234/6859832/3d44a098-d3f4-11e4-9179-bb940aa0b337.gif)

In my opinion /f help should have a customization feature added to it, many owners do not like the f help we have seen and gotten used to for 3-4 years.

**Comment by drtshock** [comment]
Good idea ;D

**Comment by NauruMC** [comment]
:+1: Great to see the waiting tag, hope we can customize this soon as well :)

**Comment by nsporillo** [comment]
@NauruMC 

Should there be pages still or should the whole /f help be on one page?

I'm fairly certain it'd be quite the stretch to fit everything on one, so perhaps a nice structure that allows multiple pages of help output would be nice.

**Comment by Kakifrucht** [comment]
What character did you use for the lines?

**Comment by nsporillo** [comment]
@Kakifrucht I'm pretty sure it is just >> 

I'm working on adding this feature tonight, so hopefully ready by tomorrow.

**Comment by Kakifrucht** [comment]
I mean the yellow lines.
I couldn't find the character in the symbol table, thats why I'm wondering ;)

**Comment by nsporillo** [comment]
@Kakifrucht 
Perhaps try http://www.fileformat.info/info/unicode/char/0097/index.htm

I'll get back to you when I do some testing, I was just using --- as a placeholder in the config.

**Comment by Kakifrucht** [comment]
Oh okay, if is just use --- it will have a litte space in between. It would be pretty neat if you could get the lines without any space in between.

**Comment by nsporillo** [comment]
@Kakifrucht I'll find the character, I just don't know it right now :p

**Comment by nsporillo** [comment]
This was added. Try latest builds for this feature addition.

**Comment by Kakifrucht** [comment]
Did you find the character and are you able to share it? ;)
