### ISSUE TITLE
Disable Claiming

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#71]
I disabled claiming in a world, but people can still claim...

http://pastebin.com/raw.php?i=3ZSWzZRY
Help.

**Comment by NauruMC** [comment]
Run this through a JSON parser to make sure there are no errors. I'm sure this is what you need.

  "bankEnabled": false,
  "bankMembersCanWithdraw": false,
  "bankFactionPaysCosts": true,
  "bankFactionPaysLandCosts": true,
  "playersWhoBypassAllProtection": [],
  "worldsNoClaiming": [
    "world_nether"
  ],
  "worldsNoDtrLoss": [],
  "worldsIgnorePvP": [],
  "worldsNoWildernessProtection": [],
  "backEnd": "JSON"
}

All i did was change "true world_nether" to "world_nether"

**Comment by nsporillo** [comment]
Please use [gists](https://gist.github.com/) when you make an issue and need to link test.

You should not put a `true` next to the world name, it will not work correctly with that.

Use:

    "worldsNoClaiming": [
      "world_nether"
    ],
