### ISSUE TITLE
Solo Factions

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#73]
Has this been implemented cause my last git ticket was closed so I'm assuming your not adding it or you have added it?

Cause HCT has this and this is something wanted by a lot of people so they can solo fac..
also ParaPvP has it.

**Comment by nsporillo** [comment]
This. Was. Added.

Already said to check the CI for the latest download and then regenerate your config for the new field to be present. 

The issue was closed because it was added. If it was closed for a reason other than it was added, I would have explicitly informed the issue author why.
