### ISSUE TITLE
New Version bug

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#74]
When you do /f show without a faction it says nothing, it replies nothing.

It also no longer has the top bar.
http://gyazo.com/0433296415b5f4f0116092e898156535

**Comment by nsporillo** [comment]
This is not a bug. We recently introduced /f show header configuration.

If you want old functionality, made the 1st line in your fshow section 

    '{header}'

Of you can do something like 

    '========={tag}========='

and the {tag} will be replaced with the faction tag.

**Comment by TMNetwork** [comment]
What about the typing /f show while not having a fac?
@nsporillo
