### ISSUE TITLE
DTR Change

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#75]
I've set the DTR to .67 per player
and it still hasn't changed from .51

http://gyazo.com/bbc06dd84fd63a959c6f01da7bc67cf1

I've restarted the server and deleted the factions.json and players.json.

http://hastebin.com/perenuzeru.vbs

**Comment by Doxify** [comment]
What build are you using?

**Comment by TMNetwork** [comment]
Most updated @Doxify

**Comment by nsporillo** [comment]
Turn on your debug in config, feel free to link the output in a https://gist.github.com/. 

I just tested this on the latest and changing player-dtr works absolutely fine. 
You can just make the change and then /f reload and expect the changes momentarily.

**Comment by TMNetwork** [comment]
https://gist.github.com/TMNetwork/0ba50f19fce3a8171806

That's my config. What should I do to test w/ debugging?

**Comment by nsporillo** [comment]
![READ](http://puu.sh/gSsyM/5a98bf1a30.png)

Set 

    debug: false
to

    debug: true

This will toggle debug messages (typically DTR change events), if DTR is not changing for anyone you wont get any output. 

I had working dtr during my tests, and I can confirm other servers have working DTR too. However it is possible when I added solo-faction-dtr, I messed something up.. but I still tested latest and it worked fine.

**Comment by TMNetwork** [comment]
This is my config:
http://hastebin.com/depizixewi.vbs

Do I need to change the max-dtr for this to take effect?
@nsporillo 
I reset everything to test this out again.

**Comment by TMNetwork** [comment]
Here is the debug:
@nsporillo 
http://gyazo.com/ba69bc50b4a24c9835b7e7e2f33b53c1

**Comment by nsporillo** [comment]
@TMNetwork found the bug, it was an typo in the code that was looking for 'max-player-dtr' instead of the new 'player-dtr'. 

Everyone will need to make sure their config is correct with this update... since they might still have the old value and thus the default player dtr of 0.51 will be used.

**Comment by TMNetwork** [comment]
@nsporillo is my config correct? u saw it in my hastbin above.
