### ISSUE TITLE
./f show (no fac)

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#76]
When your not in a fac and you do /f show then it replies with nothing.

Not even a blank input.

**Comment by nsporillo** [comment]
Duplicate of https://github.com/drtshock/HCFProblems/issues/74

**Comment by TMNetwork** [comment]
@nsporillo you closed the last one....

**Comment by Doxify** [comment]
which means it's either going to be fixed or its already fixed, he already knows about the issue, making another thread won't fix anything.

**Comment by nsporillo** [comment]
Latest build resolves this.
