### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#77]
What is the frozen lang.yml line that allows me to change the &6You may not disaband while frozen

**Comment by nsporillo** [comment]
Open a decent text editor and

    ctrl-f -> find 'frozen'.

First result:

    Command.Disband.Frozen

If you didn't want to do that, you could remember that all the lang is categorized. Lang for commands are broken up into their own sections.

![disband frozen](http://puu.sh/gSyVs/70e780f821.png)
