### ISSUE TITLE
Block Glitching

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#82]
People can block glitch through like glass and hit the person inside the fac. This is a major issue and I'd like it to be fixed.

**Comment by drtshock** [comment]
maybe try building a thicker base?

**Comment by TMNetwork** [comment]
@drtshock that's ridiculous, u guys need to fix this.

**Comment by drtshock** [comment]
This isn't the problem of my plugin. It's the server (spigot, craftbukkit, or w/e you are using).
