### ISSUE TITLE
Block Glitching #2

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#84]
Hey guys,

Please give your feedback to the devs of this b/c Trent says u should "build thicker bases"... -_-

Anyways, we need to prevent block glitching is my opinion.

**Comment by MoeXIV** [comment]
Maybe they can add support for disabling interaction with Entities behind blocks? idk

**Comment by TMNetwork** [comment]
@MoeXIV !!!!! love it!

@drtshock @nsporillo

**Comment by drtshock** [comment]
This isn't within the scope of the plugin. Go talk to spigot.

**Comment by Doxify** [comment]
This is part of minecraft. It has NOTHING to do with the factions plugin itself.

**Comment by TMNetwork** [comment]
@Doxify become unique and think of your own ideas

**Comment by Doxify** [comment]
@tmnetwork All of your suggestions for this plugin have been based on kohis / other HCF servers ideas. Please don't tell me to be unique when you have to pay you tubers to play on your shitty server. You can't even get a shop right, you use a money based economy lol.

I know this is unprofessional but this kid is annoying and has no common sense. 

Sorry again.

**Comment by TMNetwork** [comment]
@Doxify ok, ur in for a surprise

**Comment by Doxify** [comment]
@tmnetwork let me know when you stop hitting my home connection offline.

**Comment by drtshock** [comment]
Stop bickering on my issue tracker or I will have you removed from github (yes, the entire website).

Feel free to keep giving suggestions. If I say that they aren't within the scope of the project, then they aren't going to be added. Being ass holes to each other is really pissing us off and, if it continues, will lead to you no longer getting support or updates.
