### ISSUE TITLE
Whenever I /f show....

### ISSUE THREAD

**Issue by Renovations** [drtshock/HCFProblems#86]
When I f show or f who is just says, An internal error occurred while attempting to perform this command.

**Comment by Renovations** [comment]
http://gyazo.com/62ca6e614bf12b25893d81e20b62534e

**Comment by Renovations** [comment]
When I /f create internal error...

**Comment by nsporillo** [comment]
Post the error you get in console to http://gist.github.com. Saying you get an error with a command means nothing without us knowing what the error is and what version youre using.

**Comment by Renovations** [comment]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks] 
Is the error, What Jar should I be running the server on?

**Comment by nsporillo** [comment]
Post the error you get in console to http://gist.github.com.

**Comment by Renovations** [comment]
I did

**Comment by Renovations** [comment]
https://gist.github.com/Renovations/b2586979bb4ef7a7a3a6

**Comment by nsporillo** [comment]
A single line of the stacktrace tells me nothing. Post the entire error you are getting...

**Comment by Renovations** [comment]
Thats all it says -_-

**Comment by Renovations** [comment]
Could you come on my server so I could show you pls

**Comment by Renovations** [comment]
http://gyazo.com/f9ac49ba5133d4efdad43a7e93934c14
Is that what this plugin is suppose to look like?

**Comment by nsporillo** [comment]
You're using build 29, latest build is [#33](https://ci.drtshock.net/job/HCFactions/33/).

Besides that, commands are working for everyone else. I suggest you make a test server with just hcfactions.jar and see if you get the same issues. 

We build and test for spigot-1.8, so i'm not sure if craftbukkit 1.7.9 will work

**Comment by Renovations** [comment]
Alright thanks for sticking with me :)
