### ISSUE TITLE
Set a Factions DTR.

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/HCFProblems#9]
I'm going to make this short and sweet. All I'm really asking if for a command that could set DTR if something were to happen to a faction, for example: A hacker got into their base, and they got killed, or they get ddosed and they get killed.

/f dtr <faction> <dtr>
For example: 
/f dtr Warzone 5.55
or 
/f dtr Warzone -5.55

Please make this an Admin only command ;)

**Comment by nscwalk** [comment]
There is a command it's /f DTR (faction) (dtr) example /f DTR warzone 5.51 faction will still have DTR freeze but won't be raidable
