### ISSUE TITLE
Ally bug?

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#90]
This fac exceeded allies:

http://i.imgur.com/YaIz0vL.png

**Comment by nsporillo** [comment]
Duplicate of #24 

That issue was closed, but I re-opened it as I did confirm this a few days ago.

This was a bug present in the upstream factions (factionsuuid) as well. It happens when multiple ally requests are sent before reaching the limit, and then accepting them.. allows bypass.
