### ISSUE TITLE
Pressure Plate Bug #2

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#91]
Here is another pressure plate issue.

http://youtu.be/CiwjLKKbU-M

**Comment by drtshock** [comment]
Please describe the issue in your ticket via text. You should include what happens, what went wrong, and what should happen.

**Comment by MoeXIV** [comment]
If you walk on a pressure plate in claimed territory other then your own, it thinks you're trying to use it, and starts making you take damage. If someone has a whole base with pressure plates, if you take 1 step, you're as good as dead.

**Comment by nsporillo** [comment]
@MoeXIV you can disable the damage you take in the conf.json

    "ownedAreaDenyBuild": true,
    "ownedAreaPainBuild": false,

**Comment by TMNetwork** [comment]
I fixed the pain issue.

But when I try to right click a pressure plate (in the video), it says I cannot use it therefore people cannot throw potions to heal themselves.

**Comment by drtshock** [comment]
That's the intended functionality.

**Comment by nsporillo** [comment]
Closing this issue as it seems that is the intended functionality.

Do not open a duplicate issue for this, if you'd like to continue discussing this just do so here. We get the emails.

**Comment by TMNetwork** [comment]
@drtshock @nsporillo  can u guys fix that cause it's part of HCF and this is an hcf factions plugin?
