### ISSUE TITLE
Horses can trample crops in claims

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#98]
Horses can trample crops in claimed territories.

**Comment by TMNetwork** [comment]
@nsporillo @drtshock

**Comment by MoeXIV** [comment]
This has been an issue since the first update of horses.

**Comment by TMNetwork** [comment]
Ok, well fix it?

**Comment by drtshock** [comment]
This is a bug with the original Factions. We'll look at fixing this after our next promoted release.

**Comment by nsporillo** [comment]
https://youtu.be/KvqLRUVQAqA

**Comment by LOOOOOOOL** [comment]
Is this in build 45

**Comment by nsporillo** [comment]
Nope.

**Comment by LOOOOOOOL** [comment]
@nsporillo which build will it be in? Like the fix.

**Comment by Doxify** [comment]
"progress but so far" indicates that it has not yet been added.

**Comment by LOOOOOOOL** [comment]
Hey dumb shit, after you stop copying other servers to attempt to compete
with them, then correct me. For now, start trying to be unique.

**Comment by Doxify** [comment]
Then I don't think you'll be too happy with our new server "hcfpvp.com" coming out this Saturday.

**Comment by LOOOOOOOL** [comment]
@Doxify exactly you copy servers.... why r u so proud of urself? I have many other ways I can take care of that.

**Comment by LOOOOOOOL** [comment]
@Doxify so ur closing hydra to make a replica of my hcf server with my domain?

**Comment by Doxify** [comment]
Yes but don't tell anyone, we're trying to make the release a secret.

**Comment by LOOOOOOOL** [comment]
I cannot tell if your being sarcastic or not. I know you don't own the
domain.

**Comment by drtshock** [comment]
Last warning @Doxify and @LOOOOOOOL. Stop spamming my issue tracker. Leave your childish arguments at daycare and keep this issue tracker for SUPPORT RELATED ISSUES ONLY.

**Comment by drtshock** [comment]
RE this issue: "This is a bug with the original Factions. We'll look at fixing this after our next promoted release." is what I said and is still the status.
